# delucionqa Experiment Runner — OpenRouter variant

RAG ablation sweep for the **delucionqa** subset of `galileo-ai/ragbench`
(automotive owner's-manual QA), with all LLM calls through **OpenRouter**.
Run alongside the other OpenRouter notebooks — it uses its own
`config/`, `reports/`, `temp/`, and `cache_openrouter_delucionqa/` dirs.

Driven by `experiment_configs/delucionqa_openrouter_experiment.yaml`.
**Requires** `OPENROUTER_API_KEY` (comma-separate multiple keys to rotate).

## 1. Setup & Dependencies

In [1]:
get_ipython().system('pip3 install datasets faiss-cpu sentence-transformers torch groq openai python-dotenv nltk pandas -q')

In [ ]:
from google.colab import drive
import os

# 1. Mount Google Drive
drive.mount('/content/drive/')

# 2. Change directory to your uploaded folder
# Update 'Your_Folder_Name' to match your actual folder path in Drive
folder_path = '/content/drive/MyDrive/Capstone/rag_cust_support'
os.chdir(folder_path)

# 3. Verify files in your current working directory
print("Current Directory:", os.getcwd())
print("Files in folder:", os.listdir())

## 2. Imports

In [2]:
import sys
import os
from pathlib import Path
from dotenv import load_dotenv

# --- Point this at wherever THIS repo (rag_cust_support) lives. ---
# On Colab this is typically under your mounted Drive. Adjust if different.
PROJECT_ROOT = Path('/content/drive/MyDrive/Capstone/rag_cust_support')
if not PROJECT_ROOT.exists():
    # Fallback: running locally from the notebooks/ folder.
    PROJECT_ROOT = Path.cwd().parent if 'notebooks' in str(Path.cwd()) else Path.cwd()

os.chdir(PROJECT_ROOT)
project_root = PROJECT_ROOT
# Make THIS repo win on sys.path (avoids importing a stale rag-foundry copy).
sys.path = [p for p in sys.path if 'rag-foundry' not in p]
if str(project_root) in sys.path:
    sys.path.remove(str(project_root))
sys.path.insert(0, str(project_root))

from experiment.experiment_config import ExperimentConfig
from experiment.experiment_runner import ExperimentRunner
import experiment.experiment_runner as _er, core.registry as _reg

load_dotenv(override=True)
print('Current directory:', Path.cwd())
print('experiment_runner loaded from:', _er.__file__)
print('core.registry   loaded from:', _reg.__file__)
assert 'rag-foundry' not in _er.__file__, 'Still importing the old rag-foundry code! Restart runtime.'
print('HuggingFace token loaded:', bool(os.getenv('HF_TOKEN')))
print('Groq API key loaded:', bool(os.getenv('GROQ_API_KEY')))
print('OpenRouter API key loaded:', bool(os.getenv('OPENROUTER_API_KEY')))

Current directory: /content/drive/MyDrive/Capstone/rag_cust_support
experiment_runner loaded from: /content/drive/MyDrive/Capstone/rag_cust_support/experiment/experiment_runner.py
core.registry   loaded from: /content/drive/MyDrive/Capstone/rag_cust_support/core/registry.py
HuggingFace token loaded: True
Groq API key loaded: True
OpenRouter API key loaded: True

## 3. Load Experiment Configuration

The experiment configuration file specifies:
- **data_loader**: How to load data (HuggingFace with dataset_name, subset, split)
- **data_parser**: How to parse documents (title_passage)
- **config_dir**: Directory containing RAG pipeline configs
- **num_queries**: Number of queries to evaluate
- **parallel**: Whether to run configs in parallel

In [3]:
EXPERIMENT_CONFIG_PATH = project_root / "experiment_configs/delucionqa_openrouter_experiment.yaml"

experiment_config = ExperimentConfig.load(EXPERIMENT_CONFIG_PATH)

print("Experiment Configuration:")
print(f"  Config Dir:  {experiment_config.config_dir}")
print(f"  Report Dir:  {experiment_config.report_dir}")
print(f"  Temp Dir:    {experiment_config.temp_dir}")
print(f"  Cache:       {experiment_config.cache}")
print(f"  Num Queries: {experiment_config.end_index}")
print(f"  Parallel:    {experiment_config.parallel}")
print(f"  Max Workers: {experiment_config.max_workers}")
print(f"\nData Loader:")
print(f"  Type: {experiment_config.data_loader['type']}")
print(f"  Config: {experiment_config.data_loader['config']}")
print(f"\nData Parser:")
print(f"  Type: {experiment_config.data_parser}")

Experiment Configuration:
  Config Dir:  rag-experiments/delucionqa-openrouter-experiment/config
  Report Dir:  rag-experiments/delucionqa-openrouter-experiment/reports
  Temp Dir:    rag-experiments/delucionqa-openrouter-experiment/temp
  Cache:       {'enabled': True, 'cache_dir': './cache_openrouter_delucionqa'}
  Num Queries: 20
  Parallel:    False
  Max Workers: 1

Data Loader:
  Type: huggingface
  Config: {'dataset_name': 'galileo-ai/ragbench', 'subset': 'delucionqa', 'split': 'test', 'limit': 184}

Data Parser:
  Type: noop

## 4. Initialize Experiment Runner

The ExperimentRunner will:
- Create report directory if it doesn't exist
- Load RAG configs from the specified directory
- Load and parse data automatically based on YAML config

In [4]:
# Initialize experiment runner
runner = ExperimentRunner(experiment_config)
print("ExperimentRunner initialized")

ExperimentRunner initialized

In [5]:
# Load data automatically based on YAML configuration
print("Loading data based on experiment configuration...")
documents, raw_data = runner.load_data()

print(f"\n✅ Data loaded successfully!")
print(f"  Documents: {len(documents)} parsed documents")
print(f"  Raw Data:  {len(raw_data)} samples")

# Inspect first sample
first_sample = raw_data[0]
print(f"\nFirst Sample:")
print(f"  Question: {first_sample['question'][:100]}...")
print(f"  Documents: {len(first_sample['documents'])}")

Loading data based on experiment configuration...
Loading HuggingFace dataset: galileo-ai/ragbench/delucionqa (test)...
Loaded 184 samples

✅ Data loaded successfully!
  Documents: 235 parsed documents
  Raw Data:  184 samples

First Sample:
  Question: What if I fail to latch the tailgate properly?...
  Documents: 3

## 6. Load RAG Pipeline Configs

Load all RAG pipeline configurations from the config directory specified in the experiment config.

In [6]:
# Load RAG pipeline configs
configs = runner.load_configs()

print(f'Loaded {len(configs)} RAG pipeline configurations:')
for cfg in configs:
    searches = ' + '.join(s.type.value for s in cfg.retrieval.search.searches)
    fusion = cfg.retrieval.fusion.type.value if cfg.retrieval.fusion else '-'
    rerank = cfg.retrieval.rerank.type.value if cfg.retrieval.rerank else '-'
    qx = cfg.retrieval.query_transform.type.value if cfg.retrieval.query_transform else '-'
    gc = cfg.generation.config
    model = gc.get('model') if isinstance(gc, dict) else getattr(gc, 'model', None)
    print(f'  - {cfg.name}')
    print(f'      chunking={cfg.chunking.type.value}  embed={cfg.embedding.type.value}')
    print(f'      search=[{searches}]  fusion={fusion}  rerank={rerank}  q_transform={qx}')
    print(f'      generation_model={model}')

Loaded 8 RAG pipeline configurations:
  - delucionqa_or_v1_baseline
      chunking=fixed_word  embed=sentence_transformer
      search=[dense]  fusion=-  rerank=-  q_transform=-
      generation_model=meta-llama/llama-3.3-70b-instruct
  - delucionqa_or_v2_hybrid_wsum
      chunking=fixed_word  embed=sentence_transformer
      search=[dense + sparse]  fusion=weighted_sum  rerank=-  q_transform=-
      generation_model=meta-llama/llama-3.3-70b-instruct
  - delucionqa_or_v3_embed_bge
      chunking=fixed_word  embed=sentence_transformer
      search=[dense]  fusion=-  rerank=-  q_transform=-
      generation_model=meta-llama/llama-3.3-70b-instruct
  - delucionqa_or_v4_chunk_sentence
      chunking=sentence  embed=sentence_transformer
      search=[dense]  fusion=-  rerank=-  q_transform=-
      generation_model=meta-llama/llama-3.3-70b-instruct
  - delucionqa_or_v5_hybrid_rrf
      chunking=fixed_word  embed=sentence_transformer
      search=[dense + sparse]  fusion=rrf  rerank=-  q_transform=-
      generation_model=meta-llama/llama-3.3-70b-instruct
  - delucionqa_or_v6_rerank_only
      chunking=fixed_word  embed=sentence_transformer
      search=[dense]  fusion=-  rerank=cross_encoder  q_transform=-
      generation_model=meta-llama/llama-3.3-70b-instruct
  - delucionqa_or_v7_hybrid_rerank
      chunking=fixed_word  embed=sentence_transformer
      search=[dense + sparse]  fusion=rrf  rerank=cross_encoder  q_transform=-
      generation_model=meta-llama/llama-3.3-70b-instruct
  - delucionqa_or_v8_hyde
      chunking=fixed_word  embed=sentence_transformer
      search=[dense + sparse]  fusion=rrf  rerank=cross_encoder  q_transform=hyde
      generation_model=meta-llama/llama-3.3-70b-instruct

## 7. Run Experiments

Run all RAG configurations on the loaded data. Each config will:
1. Build a vector index from the documents
2. Run queries against the index
3. Generate responses
4. Evaluate using TRACe metrics

Results are returned as PipelineRunResult objects.

In [7]:
get_ipython().system('pip install rank_bm25 -q')

# Run experiments

In [8]:
# Run experiments

print(f"Running {len(configs)} configurations from {experiment_config.start_index} to {experiment_config.end_index} queries...")
print(f"Parallel mode: {experiment_config.parallel}")

runs = runner.run(documents, raw_data)

print(f"\n✅ Experiments completed!")
print(f"  Ran {len(runs)} configurations")

for run in runs:
    print(f"  - {run['config'].name}: {run['total_written']} queries")

Running 8 configurations from 0 to 20 queries...
Parallel mode: False
OpenRouter provider initialized with 4 key(s) (rotation needs 2+ keys; set OPENROUTER_API_KEY comma-separated).
Loading embedding model: sentence-transformers/all-MiniLM-L6-v2

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 0sUsing key #0: ****f2e4Using key #0: ****f2e4

================================================================================
HTTP 402 (retryable) on ****f2e4
Error code: 402 - {'error': {'message': 'Insufficient credits. This account never purchased credits. Make sure your key is on the correct account or org, and if so, purchase more at https://openrouter.ai/settings/credits', 'code': 402}}
{'provider': 'openrouter', 'current_index': 0, 'keys': [{'key_suffix': 'f2e4', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 25, 1, 1, 49, 991993), 'requests': 2, 'successes': 0, 'failures': 1, '429s': 1}, {'key_suffix': 'e916', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'b076', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'fbdb', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}]}
Using key #1: ****e916
================================================================================
HTTP 402 (retryable) on ****f2e4
Error code: 402 - {'error': {'message': 'Insufficient credits. This account never purchased credits. Make sure your key is on the correct account or org, and if so, purchase more at https://openrouter.ai/settings/credits', 'code': 402}}
{'provider': 'openrouter', 'current_index': 1, 'keys': [{'key_suffix': 'f2e4', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 25, 1, 1, 50, 124324), 'requests': 2, 'successes': 0, 'failures': 2, '429s': 2}, {'key_suffix': 'e916', 'available': True, 'cooldown_until': None, 'requests': 1, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'b076', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'fbdb', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}]}
Using key #1: ****e916
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 4sUsing key #1: ****e916
Progress: 1/20 (5.0%) | QPS: 0.11 | ETA: 2.9m | Elapsed: 9sUsing key #1: ****e916
Progress: 2/20 (10.0%) | QPS: 0.20 | ETA: 1.5m | Elapsed: 10sUsing key #1: ****e916
Progress: 3/20 (15.0%) | QPS: 0.13 | ETA: 2.2m | Elapsed: 23sUsing key #1: ****e916
Progress: 4/20 (20.0%) | QPS: 0.15 | ETA: 1.7m | Elapsed: 26sUsing key #1: ****e916
Progress: 5/20 (25.0%) | QPS: 0.18 | ETA: 1.4m | Elapsed: 27sUsing key #1: ****e916
Progress: 6/20 (30.0%) | QPS: 0.21 | ETA: 1.1m | Elapsed: 28sUsing key #1: ****e916
Progress: 7/20 (35.0%) | QPS: 0.22 | ETA: 60s | Elapsed: 32sUsing key #1: ****e916
Progress: 8/20 (40.0%) | QPS: 0.18 | ETA: 1.1m | Elapsed: 44sUsing key #1: ****e916
Progress: 9/20 (45.0%) | QPS: 0.19 | ETA: 58s | Elapsed: 47sUsing key #1: ****e916
Progress: 10/20 (50.0%) | QPS: 0.21 | ETA: 48s | Elapsed: 48sUsing key #1: ****e916
Progress: 11/20 (55.0%) | QPS: 0.22 | ETA: 41s | Elapsed: 50sUsing key #1: ****e916
Progress: 12/20 (60.0%) | QPS: 0.20 | ETA: 39s | Elapsed: 59sUsing key #1: ****e916
Progress: 13/20 (65.0%) | QPS: 0.20 | ETA: 36s | Elapsed: 1.1mUsing key #1: ****e916
Progress: 14/20 (70.0%) | QPS: 0.21 | ETA: 29s | Elapsed: 1.1mUsing key #1: ****e916
Progress: 15/20 (75.0%) | QPS: 0.22 | ETA: 23s | Elapsed: 1.2mUsing key #1: ****e916
Progress: 16/20 (80.0%) | QPS: 0.22 | ETA: 18s | Elapsed: 1.2mUsing key #1: ****e916
Progress: 17/20 (85.0%) | QPS: 0.22 | ETA: 14s | Elapsed: 1.3mUsing key #1: ****e916
Progress: 20/20 (100.0%) | QPS: 0.21 | ETA: 0s | Elapsed: 1.6m
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 0sUsing key #1: ****e916Using key #1: ****e916

Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 3sUsing key #1: ****e916
Progress: 1/20 (5.0%) | QPS: 0.25 | ETA: 1.3m | Elapsed: 4sUsing key #1: ****e916
Progress: 2/20 (10.0%) | QPS: 0.05 | ETA: 6.0m | Elapsed: 40sUsing key #1: ****e916
Progress: 3/20 (15.0%) | QPS: 0.07 | ETA: 4.1m | Elapsed: 43sUsing key #1: ****e916
Progress: 4/20 (20.0%) | QPS: 0.08 | ETA: 3.2m | Elapsed: 48sUsing key #1: ****e916
Progress: 5/20 (25.0%) | QPS: 0.10 | ETA: 2.6m | Elapsed: 52sUsing key #1: ****e916
Progress: 6/20 (30.0%) | QPS: 0.11 | ETA: 2.2m | Elapsed: 57sUsing key #1: ****e916
Progress: 7/20 (35.0%) | QPS: 0.11 | ETA: 2.0m | Elapsed: 1.1mUsing key #1: ****e916
Progress: 8/20 (40.0%) | QPS: 0.12 | ETA: 1.7m | Elapsed: 1.1mUsing key #1: ****e916
Progress: 9/20 (45.0%) | QPS: 0.12 | ETA: 1.5m | Elapsed: 1.2mUsing key #1: ****e916
Progress: 10/20 (50.0%) | QPS: 0.13 | ETA: 1.3m | Elapsed: 1.3mUsing key #1: ****e916
Progress: 11/20 (55.0%) | QPS: 0.14 | ETA: 1.1m | Elapsed: 1.3mUsing key #1: ****e916
Progress: 12/20 (60.0%) | QPS: 0.12 | ETA: 1.1m | Elapsed: 1.7mUsing key #1: ****e916
Progress: 13/20 (65.0%) | QPS: 0.11 | ETA: 1.1m | Elapsed: 2.0mUsing key #1: ****e916
Progress: 14/20 (70.0%) | QPS: 0.12 | ETA: 51s | Elapsed: 2.0mUsing key #1: ****e916
Progress: 15/20 (75.0%) | QPS: 0.12 | ETA: 42s | Elapsed: 2.1mUsing key #1: ****e916
Progress: 16/20 (80.0%) | QPS: 0.12 | ETA: 33s | Elapsed: 2.2mUsing key #1: ****e916
Progress: 17/20 (85.0%) | QPS: 0.12 | ETA: 24s | Elapsed: 2.3mUsing key #1: ****e916
Progress: 20/20 (100.0%) | QPS: 0.14 | ETA: 0s | Elapsed: 2.3m
Loading embedding model: BAAI/bge-base-en-v1.5

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/94.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/777 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  438MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 0sUsing key #1: ****e916
Using key #1: ****e916
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 1sUsing key #1: ****e916
Progress: 1/20 (5.0%) | QPS: 0.50 | ETA: 38s | Elapsed: 2sUsing key #1: ****e916
Progress: 2/20 (10.0%) | QPS: 0.40 | ETA: 45s | Elapsed: 5sUsing key #1: ****e916
Progress: 3/20 (15.0%) | QPS: 0.43 | ETA: 40s | Elapsed: 7sUsing key #1: ****e916
Progress: 4/20 (20.0%) | QPS: 0.50 | ETA: 32s | Elapsed: 8sUsing key #1: ****e916
Progress: 6/20 (30.0%) | QPS: 0.54 | ETA: 26s | Elapsed: 11sUsing key #1: ****e916
Progress: 6/20 (30.0%) | QPS: 0.16 | ETA: 1.5m | Elapsed: 38sUsing key #1: ****e916
Using key #1: ****e916
Progress: 8/20 (40.0%) | QPS: 0.20 | ETA: 1.0m | Elapsed: 40sUsing key #1: ****e916
Progress: 9/20 (45.0%) | QPS: 0.19 | ETA: 58s | Elapsed: 47sUsing key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Progress: 12/20 (60.0%) | QPS: 0.23 | ETA: 34s | Elapsed: 51sUsing key #1: ****e916
Progress: 13/20 (65.0%) | QPS: 0.21 | ETA: 33s | Elapsed: 1.0mUsing key #1: ****e916
Progress: 14/20 (70.0%) | QPS: 0.20 | ETA: 30s | Elapsed: 1.2mUsing key #1: ****e916
Progress: 15/20 (75.0%) | QPS: 0.21 | ETA: 24s | Elapsed: 1.2mUsing key #1: ****e916
Using key #1: ****e916
Progress: 18/20 (90.0%) | QPS: 0.24 | ETA: 8s | Elapsed: 1.3mUsing key #1: ****e916
Progress: 20/20 (100.0%) | QPS: 0.25 | ETA: 0s | Elapsed: 1.3m
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 0sUsing key #1: ****e916
Using key #1: ****e916
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 2sUsing key #1: ****e916
Progress: 1/20 (5.0%) | QPS: 0.25 | ETA: 1.3m | Elapsed: 4sUsing key #1: ****e916
Progress: 2/20 (10.0%) | QPS: 0.10 | ETA: 3.0m | Elapsed: 20sUsing key #1: ****e916
Progress: 3/20 (15.0%) | QPS: 0.08 | ETA: 3.6m | Elapsed: 38sUsing key #1: ****e916
Progress: 4/20 (20.0%) | QPS: 0.10 | ETA: 2.7m | Elapsed: 40sUsing key #1: ****e916
Progress: 5/20 (25.0%) | QPS: 0.10 | ETA: 2.6m | Elapsed: 51sUsing key #1: ****e916
Progress: 6/20 (30.0%) | QPS: 0.11 | ETA: 2.1m | Elapsed: 54sUsing key #1: ****e916
Progress: 7/20 (35.0%) | QPS: 0.12 | ETA: 1.8m | Elapsed: 59sUsing key #1: ****e916
Progress: 8/20 (40.0%) | QPS: 0.13 | ETA: 1.5m | Elapsed: 1.0mUsing key #1: ****e916
Progress: 9/20 (45.0%) | QPS: 0.13 | ETA: 1.4m | Elapsed: 1.1mUsing key #1: ****e916
Progress: 10/20 (50.0%) | QPS: 0.15 | ETA: 1.1m | Elapsed: 1.1mUsing key #1: ****e916
Progress: 11/20 (55.0%) | QPS: 0.13 | ETA: 1.1m | Elapsed: 1.4mUsing key #1: ****e916
Progress: 12/20 (60.0%) | QPS: 0.14 | ETA: 59s | Elapsed: 1.5mUsing key #1: ****e916
Progress: 13/20 (65.0%) | QPS: 0.13 | ETA: 52s | Elapsed: 1.6mUsing key #1: ****e916
Progress: 14/20 (70.0%) | QPS: 0.13 | ETA: 45s | Elapsed: 1.8mUsing key #1: ****e916
Progress: 15/20 (75.0%) | QPS: 0.14 | ETA: 35s | Elapsed: 1.8mUsing key #1: ****e916
Progress: 16/20 (80.0%) | QPS: 0.14 | ETA: 29s | Elapsed: 1.9mUsing key #1: ****e916
Progress: 17/20 (85.0%) | QPS: 0.14 | ETA: 22s | Elapsed: 2.0mUsing key #1: ****e916
Progress: 20/20 (100.0%) | QPS: 0.16 | ETA: 0s | Elapsed: 2.1m
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 0sUsing key #1: ****e916
Using key #1: ****e916
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 2sUsing key #1: ****e916
Progress: 1/20 (5.0%) | QPS: 0.25 | ETA: 1.3m | Elapsed: 4sUsing key #1: ****e916
Progress: 2/20 (10.0%) | QPS: 0.40 | ETA: 45s | Elapsed: 5sUsing key #1: ****e916
Progress: 3/20 (15.0%) | QPS: 0.37 | ETA: 45s | Elapsed: 8sUsing key #1: ****e916
Progress: 4/20 (20.0%) | QPS: 0.40 | ETA: 40s | Elapsed: 10sUsing key #1: ****e916
Progress: 5/20 (25.0%) | QPS: 0.26 | ETA: 57s | Elapsed: 19sUsing key #1: ****e916
Progress: 6/20 (30.0%) | QPS: 0.30 | ETA: 47s | Elapsed: 20sUsing key #1: ****e916
Progress: 7/20 (35.0%) | QPS: 0.23 | ETA: 58s | Elapsed: 31sUsing key #1: ****e916
Progress: 8/20 (40.0%) | QPS: 0.23 | ETA: 53s | Elapsed: 35sUsing key #1: ****e916
Progress: 9/20 (45.0%) | QPS: 0.19 | ETA: 58s | Elapsed: 47sUsing key #1: ****e916
Progress: 10/20 (50.0%) | QPS: 0.20 | ETA: 49s | Elapsed: 49sUsing key #1: ****e916
Progress: 11/20 (55.0%) | QPS: 0.22 | ETA: 41s | Elapsed: 50sUsing key #1: ****e916
Progress: 12/20 (60.0%) | QPS: 0.23 | ETA: 35s | Elapsed: 52sUsing key #1: ****e916
Progress: 13/20 (65.0%) | QPS: 0.21 | ETA: 33s | Elapsed: 1.0mUsing key #1: ****e916
Progress: 14/20 (70.0%) | QPS: 0.20 | ETA: 30s | Elapsed: 1.2mUsing key #1: ****e916
Progress: 15/20 (75.0%) | QPS: 0.19 | ETA: 26s | Elapsed: 1.3mUsing key #1: ****e916
Progress: 16/20 (80.0%) | QPS: 0.19 | ETA: 21s | Elapsed: 1.4mUsing key #1: ****e916
Progress: 17/20 (85.0%) | QPS: 0.20 | ETA: 15s | Elapsed: 1.4mUsing key #1: ****e916
Progress: 20/20 (100.0%) | QPS: 0.16 | ETA: 0s | Elapsed: 2.1m
Loading reranker model: BAAI/bge-reranker-v2-m3

config.json:   0%|          | 0.00/795 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 2.27GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

sentencepiece.bpe.model: reconstructing file:   0%|          |  0.00B / 5.07MB

sentencepiece.bpe.model: downloading bytes:           |  0.00B

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.1MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 1.8mUsing key #1: ****e916
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 1.9mUsing key #1: ****e916
Progress: 2/20 (10.0%) | QPS: 0.01 | ETA: 34.5m | Elapsed: 3.8mUsing key #1: ****e916
Using key #1: ****e916
Progress: 4/20 (20.0%) | QPS: 0.01 | ETA: 21.9m | Elapsed: 5.5mUsing key #1: ****e916
Progress: 5/20 (25.0%) | QPS: 0.01 | ETA: 17.3m | Elapsed: 5.8mUsing key #1: ****e916
Progress: 6/20 (30.0%) | QPS: 0.01 | ETA: 17.6m | Elapsed: 7.6mUsing key #1: ****e916
Progress: 7/20 (35.0%) | QPS: 0.02 | ETA: 14.2m | Elapsed: 7.6mUsing key #1: ****e916
Progress: 8/20 (40.0%) | QPS: 0.01 | ETA: 14.2m | Elapsed: 9.5mUsing key #1: ****e916
Using key #1: ****e916
Progress: 10/20 (50.0%) | QPS: 0.01 | ETA: 11.4m | Elapsed: 11.4mUsing key #1: ****e916
Progress: 11/20 (55.0%) | QPS: 0.02 | ETA: 9.6m | Elapsed: 11.7mUsing key #1: ****e916
Progress: 12/20 (60.0%) | QPS: 0.02 | ETA: 8.8m | Elapsed: 13.3mUsing key #1: ****e916
Progress: 13/20 (65.0%) | QPS: 0.02 | ETA: 7.3m | Elapsed: 13.5mUsing key #1: ****e916
Progress: 14/20 (70.0%) | QPS: 0.02 | ETA: 6.4m | Elapsed: 14.8mUsing key #1: ****e916
Progress: 15/20 (75.0%) | QPS: 0.02 | ETA: 5.1m | Elapsed: 15.2mUsing key #1: ****e916
Progress: 16/20 (80.0%) | QPS: 0.02 | ETA: 4.2m | Elapsed: 16.8mUsing key #1: ****e916
Progress: 16/20 (80.0%) | QPS: 0.02 | ETA: 4.2m | Elapsed: 17.0mUsing key #1: ****e916
Progress: 18/20 (90.0%) | QPS: 0.02 | ETA: 2.1m | Elapsed: 18.9mUsing key #1: ****e916
Progress: 19/20 (95.0%) | QPS: 0.02 | ETA: 1.0m | Elapsed: 19.0mUsing key #1: ****e916
Progress: 20/20 (100.0%) | QPS: 0.02 | ETA: 0s | Elapsed: 19.1m
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 55sUsing key #1: ****e916
Using key #1: ****e916
Progress: 2/20 (10.0%) | QPS: 0.02 | ETA: 13.8m | Elapsed: 1.5mUsing key #1: ****e916
Progress: 3/20 (15.0%) | QPS: 0.02 | ETA: 13.1m | Elapsed: 2.3mUsing key #1: ****e916
Progress: 3/20 (15.0%) | QPS: 0.02 | ETA: 13.6m | Elapsed: 2.4mUsing key #1: ****e916
Progress: 5/20 (25.0%) | QPS: 0.03 | ETA: 9.6m | Elapsed: 3.2mUsing key #1: ****e916
Progress: 5/20 (25.0%) | QPS: 0.02 | ETA: 10.1m | Elapsed: 3.4mUsing key #1: ****e916
Progress: 7/20 (35.0%) | QPS: 0.03 | ETA: 7.9m | Elapsed: 4.2mUsing key #1: ****e916
Progress: 7/20 (35.0%) | QPS: 0.03 | ETA: 8.0m | Elapsed: 4.3mUsing key #1: ****e916
Progress: 9/20 (45.0%) | QPS: 0.03 | ETA: 6.3m | Elapsed: 5.1mUsing key #1: ****e916
Progress: 10/20 (50.0%) | QPS: 0.03 | ETA: 5.3m | Elapsed: 5.3mUsing key #1: ****e916
Progress: 11/20 (55.0%) | QPS: 0.03 | ETA: 5.0m | Elapsed: 6.2mUsing key #1: ****e916
Progress: 12/20 (60.0%) | QPS: 0.03 | ETA: 4.1m | Elapsed: 6.2mUsing key #1: ****e916
Progress: 13/20 (65.0%) | QPS: 0.03 | ETA: 3.8m | Elapsed: 7.0mUsing key #1: ****e916
Progress: 14/20 (70.0%) | QPS: 0.03 | ETA: 3.0m | Elapsed: 7.1mUsing key #1: ****e916
Progress: 15/20 (75.0%) | QPS: 0.03 | ETA: 2.6m | Elapsed: 7.7mUsing key #1: ****e916
Progress: 15/20 (75.0%) | QPS: 0.03 | ETA: 2.7m | Elapsed: 8.0mUsing key #1: ****e916
Progress: 17/20 (85.0%) | QPS: 0.03 | ETA: 1.6m | Elapsed: 8.9mUsing key #1: ****e916
Progress: 18/20 (90.0%) | QPS: 0.03 | ETA: 1.0m | Elapsed: 9.1mUsing key #1: ****e916
Progress: 19/20 (95.0%) | QPS: 0.03 | ETA: 30s | Elapsed: 9.6mUsing key #1: ****e916
Progress: 20/20 (100.0%) | QPS: 0.03 | ETA: 0s | Elapsed: 9.6m
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 0sUsing key #1: ****e916
Using key #1: ****e916
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 33sUsing key #1: ****e916
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 42sUsing key #1: ****e916
Progress: 1/20 (5.0%) | QPS: 0.01 | ETA: 31.1m | Elapsed: 1.6mUsing key #1: ****e916
Progress: 1/20 (5.0%) | QPS: 0.01 | ETA: 33.0m | Elapsed: 1.7mUsing key #1: ****e916
Progress: 2/20 (10.0%) | QPS: 0.02 | ETA: 15.8m | Elapsed: 1.8mUsing key #1: ****e916
Using key #1: ****e916
Progress: 3/20 (15.0%) | QPS: 0.02 | ETA: 15.3m | Elapsed: 2.7mUsing key #1: ****e916
Progress: 3/20 (15.0%) | QPS: 0.02 | ETA: 15.5m | Elapsed: 2.7mUsing key #1: ****e916
Progress: 4/20 (20.0%) | QPS: 0.02 | ETA: 11.3m | Elapsed: 2.8mUsing key #1: ****e916
Progress: 4/20 (20.0%) | QPS: 0.02 | ETA: 11.4m | Elapsed: 2.9mUsing key #1: ****e916
Progress: 5/20 (25.0%) | QPS: 0.02 | ETA: 11.7m | Elapsed: 3.9mUsing key #1: ****e916
Progress: 5/20 (25.0%) | QPS: 0.02 | ETA: 12.0m | Elapsed: 4.0mUsing key #1: ****e916
Progress: 6/20 (30.0%) | QPS: 0.02 | ETA: 9.4m | Elapsed: 4.0mUsing key #1: ****e916
Progress: 6/20 (30.0%) | QPS: 0.02 | ETA: 9.6m | Elapsed: 4.1mUsing key #1: ****e916
Progress: 7/20 (35.0%) | QPS: 0.02 | ETA: 9.2m | Elapsed: 5.0mUsing key #1: ****e916
Progress: 7/20 (35.0%) | QPS: 0.02 | ETA: 9.3m | Elapsed: 5.0mUsing key #1: ****e916
Progress: 8/20 (40.0%) | QPS: 0.03 | ETA: 7.8m | Elapsed: 5.2mUsing key #1: ****e916
Progress: 8/20 (40.0%) | QPS: 0.03 | ETA: 7.9m | Elapsed: 5.3mUsing key #1: ****e916
Progress: 9/20 (45.0%) | QPS: 0.03 | ETA: 7.3m | Elapsed: 5.9mUsing key #1: ****e916
Progress: 9/20 (45.0%) | QPS: 0.02 | ETA: 7.5m | Elapsed: 6.1mUsing key #1: ****e916
Progress: 9/20 (45.0%) | QPS: 0.02 | ETA: 7.6m | Elapsed: 6.2mUsing key #1: ****e916
Progress: 10/20 (50.0%) | QPS: 0.03 | ETA: 6.3m | Elapsed: 6.3mUsing key #1: ****e916
Progress: 11/20 (55.0%) | QPS: 0.03 | ETA: 5.9m | Elapsed: 7.2mUsing key #1: ****e916
Progress: 11/20 (55.0%) | QPS: 0.03 | ETA: 5.9m | Elapsed: 7.2mUsing key #1: ****e916
Progress: 12/20 (60.0%) | QPS: 0.03 | ETA: 4.9m | Elapsed: 7.3mUsing key #1: ****e916
Progress: 12/20 (60.0%) | QPS: 0.03 | ETA: 4.9m | Elapsed: 7.3mUsing key #1: ****e916
Progress: 13/20 (65.0%) | QPS: 0.03 | ETA: 4.4m | Elapsed: 8.1mUsing key #1: ****e916
Progress: 13/20 (65.0%) | QPS: 0.03 | ETA: 4.4m | Elapsed: 8.2mUsing key #1: ****e916
Progress: 13/20 (65.0%) | QPS: 0.03 | ETA: 4.4m | Elapsed: 8.3mUsing key #1: ****e916
Progress: 14/20 (70.0%) | QPS: 0.03 | ETA: 3.6m | Elapsed: 8.4mUsing key #1: ****e916
Progress: 15/20 (75.0%) | QPS: 0.03 | ETA: 3.1m | Elapsed: 9.4mUsing key #1: ****e916
Progress: 15/20 (75.0%) | QPS: 0.03 | ETA: 3.1m | Elapsed: 9.4mUsing key #1: ****e916
Progress: 16/20 (80.0%) | QPS: 0.03 | ETA: 2.4m | Elapsed: 9.5mUsing key #1: ****e916
Progress: 16/20 (80.0%) | QPS: 0.03 | ETA: 2.4m | Elapsed: 9.5mUsing key #1: ****e916
Progress: 17/20 (85.0%) | QPS: 0.03 | ETA: 1.9m | Elapsed: 10.5mUsing key #1: ****e916
Progress: 17/20 (85.0%) | QPS: 0.03 | ETA: 1.9m | Elapsed: 10.5mUsing key #1: ****e916
Progress: 17/20 (85.0%) | QPS: 0.03 | ETA: 1.9m | Elapsed: 10.6mUsing key #1: ****e916
Progress: 19/20 (95.0%) | QPS: 0.03 | ETA: 36s | Elapsed: 11.4mUsing key #1: ****e916
Progress: 20/20 (100.0%) | QPS: 0.03 | ETA: 0s | Elapsed: 11.4m

✅ Experiments completed!
  Ran 8 configurations
  - delucionqa_or_v1_baseline: 20 queries
  - delucionqa_or_v2_hybrid_wsum: 20 queries
  - delucionqa_or_v3_embed_bge: 20 queries
  - delucionqa_or_v4_chunk_sentence: 20 queries
  - delucionqa_or_v5_hybrid_rrf: 20 queries
  - delucionqa_or_v6_rerank_only: 20 queries
  - delucionqa_or_v7_hybrid_rerank: 20 queries
  - delucionqa_or_v8_hyde: 20 queries

## 7b. Evaluate Existing JSONL Files

Run offline evaluation on already-generated JSONL files.
Uses experiment-level evaluation config — all configs are scored with the same judge model.

- `parallel_runs=True` — evaluate multiple configs simultaneously
- `parallel_config_run=True` — evaluate records within each config in parallel

In [9]:
# Discover all configs and build run dicts from existing JSONL files
configs = runner.load_configs()
runs = []
for cfg in configs:
    jsonl_path = experiment_config.temp_dir / f"{cfg.name}.jsonl"
    if jsonl_path.exists():
        runs.append({"config_name": cfg.name, "config": cfg, "jsonl_path": jsonl_path})
    else:
        print(f"  Skipping {cfg.name} — no JSONL found")

print(f"Found {len(runs)} configs with JSONL files")

# Evaluate all configs: parallel across configs + parallel within each config
eval_runs = runner.evaluate_runs(
    runs,
    parallel_runs=True,
    parallel_config_run=True,
)

# Use eval_runs for report generation downstream
runs = eval_runs
print(f"\n✅ Evaluation complete: {len(eval_runs)} configs")

Found 8 configs with JSONL files

WARNING:evaluation.runner:Record 2 evaluation failed: [Errno 17] File exists: '/root/nltk_data/tokenizers/punkt'

Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
[delucionqa_or_v1_baseline] Evaluation complete → rag-experiments/delucionqa-openrouter-experiment/temp/delucionqa_or_v1_baseline.jsonl
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916

WARNING:evaluation.runner:Record 9 evaluation failed: Expecting value: line 17 column 25 (char 1145)

Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916

WARNING:evaluation.runner:Record 20 evaluation failed: Judge did not return valid JSON:

```
{
  "relevance_explanation": "The question asks about using the key fob to unlock all the doors. Relevant sentences are those that describe the key fob's unlock functionality, particularly in relation to unlocking all doors.",
  "all_relevant_sentence_keys": ["d0s0", "d0s

[delucionqa_or_v2_hybrid_wsum] Evaluation complete → rag-experiments/delucionqa-openrouter-experiment/temp/delucionqa_or_v2_hybrid_wsum.jsonl
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
[delucionqa_or_v3_embed_bge] Evaluation complete → rag-experiments/delucionqa-openrouter-experiment/temp/delucionqa_or_v3_embed_bge.jsonl
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916

WARNING:evaluation.runner:Record 3 evaluation failed: 'NoneType' object has no attribute 'strip'

Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
[delucionqa_or_v4_chunk_sentence] Evaluation complete → rag-experiments/delucionqa-openrouter-experiment/temp/delucionqa_or_v4_chunk_sentence.jsonl
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916

WARNING:evaluation.runner:Record 15 evaluation failed: Judge did not return valid JSON:

```
{
  "relevance_explanation": "The question asks for steps to jump start a car. Relevant sentences are those that provide instructions or precautions for jump starting a vehicle.",
  "all_relevant_sentence_keys": ["d0s1", "d0s2", "d0s3", "d0s4", "d0s5", "d0s6", "d0s7", "d0s8", "d0s9", "d1s1", "d1s2", "d1s3", "d1s4", "d1s5", "d1s6", "d1s7", "d1s8", "d2s0", "d2s1", "d2s2", "d2s3", "d2s

Using key #1: ****e916
Using key #1: ****e916

WARNING:evaluation.runner:Record 16 evaluation failed: Expecting ',' delimiter: line 60 column 6 (char 3515)

Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
[delucionqa_or_v5_hybrid_rrf] Evaluation complete → rag-experiments/delucionqa-openrouter-experiment/temp/delucionqa_or_v5_hybrid_rrf.jsonl
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916

WARNING:evaluation.runner:Record 5 evaluation failed: Expecting value: line 11 column 25 (char 996)

Using key #1: ****e916

WARNING:evaluation.runner:Record 6 evaluation failed: Expecting ',' delimiter: line 90 column 6 (char 3946)

Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
[delucionqa_or_v6_rerank_only] Evaluation complete → rag-experiments/delucionqa-openrouter-experiment/temp/delucionqa_or_v6_rerank_only.jsonl
Using key #1: ****e916
Using key #1: ****e916

WARNING:evaluation.runner:Record 1 evaluation failed: Judge did not return valid JSON:

```
{
  "relevance_explanation": "The question asks about the consequences of failing to latch the tailgate properly. The relevant sentences in the documents discuss the importance of securely latching the tailgate and the potential damage that could result from failure to do so.",
  "all_relevant_sentence_keys": ["d0s1", "d0s2", "d1s1", "d1s

Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
[delucionqa_or_v7_hybrid_rerank] Evaluation complete → rag-experiments/delucionqa-openrouter-experiment/temp/delucionqa_or_v7_hybrid_rerank.jsonl
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
Using key #1: ****e916
[delucionqa_or_v8_hyde] Evaluation complete → rag-experiments/delucionqa-openrouter-experiment/temp/delucionqa_or_v8_hyde.jsonl

✅ Evaluation complete: 8 configs

## 8. Generate Reports

Generate detailed reports for each configuration including:
- Per-query table with all TRACe scores
- Aggregate statistics (mean, std, MAE)
- Comparison with ground truth

In [10]:
# Generate reports
print("Generating reports...")
reports = runner.generate_reports(runs)

print(f"\n✅ Reports generated!")
print(f"  Saved to: {experiment_config.report_dir}")

Generating reports...

✅ Reports generated!
  Saved to: rag-experiments/delucionqa-openrouter-experiment/reports

## 9. Display Reports

Display the generated reports with per-query and aggregate metrics.

In [11]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 80)

for report in reports:
    print(f"\n{'='*80}")
    print(f"Configuration: {report.config_name}")
    print(f"{'='*80}")

    # Display per-query results
    print("\nPer-Query Results:")
    display(report.display())

================================================================================
Configuration: delucionqa_or_v1_baseline
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `delucionqa_or_v1_baseline`

**name**: delucionqa_or_v1_baseline  •  **mode**: test  •  **providers**: {'openrouter': {'type': 'openrouter', 'api_key_env': 'OPENROUTER_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'fixed_word', 'config': {'max_words': 160, 'overlap_words': 24}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'sentence-transformers/all-MiniLM-L6-v2', 'dimension': 384}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 384}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 5}}]}, 'query_transform': None, 'fusion': None, 'rerank': None}  •  **generation**: {'strategy': 'default', 'provider': 'openrouter', 'config': {'model': 'meta-llama/llama-3.3-70b-instruct', 'temperature': 0.0, 'max_tokens': 512, 'system_prompt': 'You are an automotive owner\'s-manual support assistant. Answer questions\nabout vehicle features, controls, and procedures using ONLY the provided\nowner\'s-manual passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use outside knowledge.\n2. Give exact, step-by-step procedures. Preserve exact control names, button\n   names, warning/CAUTION text, and feature labels verbatim.\n3. Include any safety warnings (WARNING/CAUTION) that the passages attach to\n   the procedure.\n4. Be concise and procedural - give the steps, not background.\n5. If the passages do not contain the answer, respond with exactly:\n   "The passages do not provide sufficient information to answer this question."\n6. Every claim must be directly supported by the passages provided.\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, give exact steps, control names, and any safety warnings):\n'}}  •  **evaluation**: {'type': 'trace', 'provider': 'openrouter', 'config': {'model': 'meta-llama/llama-3.3-70b-instruct', 'temperature': 0.0, 'max_tokens': 2000}}  •  **cache**: {'enabled': True, 'cache_dir': './cache_openrouter_delucionqa'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,What if I fail to latch the tailgate properly?,"[{'text': '', 'title': '', 'content': 'If the Tonneau Cover is installed, ma...",Failure to securely latch the tailgate could result in damage to the vehicle...,0.2500,0.1111,0.1389,0.3333,0.1111,0.2222,1.0000,1.0000,0.0000,0.0,1.0,-1.0
1,What kind of safety features are implemented in this car?,"[{'text': '', 'title': '', 'content': 'OCCUPANT RESTRAINT SYSTEMS Some of th...",The passages mention the following safety features: \n1. Restraint systems (...,NaN,0.2500,NaN,NaN,0.2500,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
2,When will the Automatic SOS be triggered?,"[{'text': '', 'title': '', 'content': 'Automatic SOS — If Equipped Automatic...",The passages do not provide sufficient information to answer this question.,0.3214,0.0244,0.2970,0.0357,0.0244,0.0113,0.1111,1.0000,-0.8889,1.0,1.0,0.0
3,What happens if I accidentally push the SOS Call button?,"[{'text': '', 'title': '', 'content': 'Connected Services SOS FAQs — If Equi...","If you accidentally push the SOS Call button, you have 10 seconds to cancel ...",0.3750,0.0820,0.2930,0.1875,0.0656,0.1219,0.3333,0.8000,-0.4667,0.0,1.0,-1.0
4,What is the DEF?,"[{'text': '', 'title': '', 'content': 'DEF tank DEF pump DEF injector Electr...","The passages do not provide a direct definition of DEF, but according to Doc...",0.1600,0.0625,0.0975,0.2000,0.0625,0.1375,0.5000,1.0000,-0.5000,0.0,1.0,-1.0
5,What may cause erratic or noisy performance of the radio?,"[{'text': '', 'title': '', 'content': 'Under certain conditions, the mobile ...","According to Document 1, the mobile phone being on in your vehicle can cause...",0.2759,0.1143,0.1616,0.2759,0.1143,0.1616,1.0000,1.0000,0.0000,0.0,1.0,-1.0
6,how to calculate the gross trailer weight?,"[{'text': '', 'title': '', 'content': 'Gross Trailer Weight (GTW) The GTW is...","To calculate the Gross Trailer Weight (GTW), follow these steps:\n\n1. Put y...",0.1579,0.2727,-0.1148,0.2105,0.2727,-0.0622,1.0000,1.0000,0.0000,0.0,1.0,-1.0
7,What can the ASIST button do?,"[{'text': '', 'title': '', 'content': 'If equipped, the ASSIST Button is use...","The ASSIST Button is used for contacting Roadside Assistance, Vehicle Care, ...",0.1818,0.4348,-0.2530,0.0303,0.4348,-0.4045,0.1667,1.0000,-0.8333,0.0,1.0,-1.0
8,What does the Door Off Mirror Kit do?,"[{'text': '', 'title': '', 'content': 'Door Off Mirror Kit — If Equipped If ...",The Door Off Mirror Kit allows exterior rearview mirrors to be installed ont...,0.3571,0.1304,0.2267,0.3571,0.1304,0.2267,0.7000,1.0000,-0.3000,0.0,1.0,-1.0
9,Can I manually activate or deactivate the air conditioner?,"[{'text': '', 'title': '', 'content': 'The Air Conditioning (A/C) button all...","To manually activate or deactivate the air conditioner, press and release th...",0.2553,0.0811,0.1742,0.5319,0.1351,0.3968,1.0000,0.6667,0.3333,0.0,1.0,-1.0
10,what does the The cartridge block heater do?,"[{'text': '', 'title': '', 'content': 'The cartridge block heater clips into...",The cartridge block heater clips into the engine block near the water jacket...,0.3659,0.0492,0.3167,0.3659,0.0492,0.3167,1.0000,1.0000,0.0000,0.0,1.0,-1.0
11,When will the illuminated entry system be activated?,"[{'text': '', 'title': '', 'content': 'and will remain fully illuminated unt...",The passages do not provide sufficient information to answer this question.,0.2258,0.0541,0.1717,0.0000,0.0811,-0.0811,0.0000,1.0000,-1.0000,1.0,1.0,0.0
12,"If the light remains on after the bulb check, it indicates what problem?","[{'text': '', 'title': '', 'content': 'Your vehicle is equipped with a sophi...","If the Vehicle Security Light remains on after the bulb check, it indicates ...",0.1053,0.1042,0.0011,0.0526,0.0208,0.0318,0.5000,0.2000,0.3000,0.0,1.0,-1.0
13,What is special about power windows?,"[{'text': '', 'title': '', 'content': 'The power windows feature allows for ...",The power windows feature allows for movement of the windows with the push o...,0.2444,0.2759,-0.0315,0.2222,0.1379,0.0843,0.8182,0.5000,0.3182,0.0,1.0,-1.0
14,What should I do to jump start the car?,"[{'text': '', 'title': '', 'content': 'of the engine compartment. If your ve...","To jump start the car, follow these steps: \n1. Apply the parking brake, \n2...",1.0000,0.4127,0.5873,0.6486,0.2063,0.4423,0.6486,0.5000,0.1486,0.0,1.0,-1.0
15,How to deactivate the cruise control?,"[{'text': '', 'title': '', 'content': 'Cruise Control can be dangerous where...","To deactivate the Cruise Control, follow these steps:\n\n1. A soft tap on th...",0.3571,0.4667,-0.1096,0.3571,0.4667,-0.1096,0.5000,0.8571,-0.3571,0.0,1.0,-1.0
16,Is it safe for me to park the vehicle in somewhere very hot?,"[{'text': '', 'title': '', 'content': 'Transporting Passengers NEVER TRANSPO...",WARNING: Do not leave children or animals inside parked vehicles in hot weat...,0.2143,0.1622,0.0521,0.1667,0.1892,-0.0225,0.7778,1.0000,-0.2222,0.0,1.0,-1.0
17,Any tips for driving downhill?,"[{'text': '', 'title': '', 'content': 'Driving Up Hill Once you have determi...","To drive downhill, follow these steps:\n1. Determine if the hill is too stee...",0.2619,0.5000,-0.2381,0.2619,0.5000,-0.2381,1.0000,1.0000,0.0000,1.0,1.0,0.0
18,what can the dimmer controls adjust?,"[{'text': '', 'title': '', 'content': 'Dimmer Control The dimmer control is ...",The dimmer control can adjust the following:\n\n1. Brightness of the instrum...,0.2857,0.5000,-0.2143,0.2143,0.5000,-0.2857,0.7500,1.0000,-0.2500,0.0,1.0,-1.0
19,how to use the key fob to unlock all the doors?,"[{'text': '', 'title': '', 'content': 'To Lock/Unlock The Doors And Tailgate...","To unlock all the doors using the key fob, push and release the unlock butto...",0.2647,0.0312,0.2334,0.0588,0.0312,0.0275,0.2222,1.0000,-0.7778,0.0,1.0,-1.0

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.2979,0.2060,0.1810,0.1651,0.1954
1,utilization_score,0.2374,0.1892,0.1668,0.1589,0.1781
2,completeness_score,0.6330,0.8762,0.3312,0.2242,0.3524
3,adherence_score,0.1579,1.0000,0.3646,0.0000,0.8421

None

================================================================================
Configuration: delucionqa_or_v2_hybrid_wsum
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `delucionqa_or_v2_hybrid_wsum`

**name**: delucionqa_or_v2_hybrid_wsum  •  **mode**: test  •  **providers**: {'openrouter': {'type': 'openrouter', 'api_key_env': 'OPENROUTER_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'fixed_word', 'config': {'max_words': 160, 'overlap_words': 24}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'sentence-transformers/all-MiniLM-L6-v2', 'dimension': 384}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 384}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 20}}, {'type': 'sparse', 'config': {'top_k': 20}}]}, 'query_transform': None, 'fusion': {'type': 'weighted_sum', 'config': {'top_k': 10, 'weights': [0.5, 0.5]}}, 'rerank': None}  •  **generation**: {'strategy': 'default', 'provider': 'openrouter', 'config': {'model': 'meta-llama/llama-3.3-70b-instruct', 'temperature': 0.0, 'max_tokens': 512, 'system_prompt': 'You are an automotive owner\'s-manual support assistant. Answer questions\nabout vehicle features, controls, and procedures using ONLY the provided\nowner\'s-manual passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use outside knowledge.\n2. Give exact, step-by-step procedures. Preserve exact control names, button\n   names, warning/CAUTION text, and feature labels verbatim.\n3. Include any safety warnings (WARNING/CAUTION) that the passages attach to\n   the procedure.\n4. Be concise and procedural - give the steps, not background.\n5. If the passages do not contain the answer, respond with exactly:\n   "The passages do not provide sufficient information to answer this question."\n6. Every claim must be directly supported by the passages provided.\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, give exact steps, control names, and any safety warnings):\n'}}  •  **evaluation**: {'type': 'trace', 'provider': 'openrouter', 'config': {'model': 'meta-llama/llama-3.3-70b-instruct', 'temperature': 0.0, 'max_tokens': 2000}}  •  **cache**: {'enabled': True, 'cache_dir': './cache_openrouter_delucionqa'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,What if I fail to latch the tailgate properly?,"[{'text': '', 'title': '', 'content': 'If the Tonneau Cover is installed, ma...",Failure to securely latch the tailgate could result in damage to the vehicle...,0.1228,0.1111,0.0117,0.1579,0.1111,0.0468,1.0000,1.0000,0.0000,1.0,1.0,0.0
1,What kind of safety features are implemented in this car?,"[{'text': '', 'title': '', 'content': 'OCCUPANT RESTRAINT SYSTEMS Some of th...",The passages mention the following safety features:\n\n1. Occupant Restraint...,0.3091,0.2500,0.0591,0.2727,0.2500,0.0227,0.5882,1.0000,-0.4118,0.0,1.0,-1.0
2,When will the Automatic SOS be triggered?,"[{'text': '', 'title': '', 'content': 'Automatic SOS — If Equipped Automatic...",The passages do not provide sufficient information to answer this question.,0.0149,0.0244,-0.0095,0.0000,0.0244,-0.0244,0.0000,1.0000,-1.0000,0.0,1.0,-1.0
3,What happens if I accidentally push the SOS Call button?,"[{'text': '', 'title': '', 'content': 'Connected Services SOS FAQs — If Equi...","If you accidentally push the SOS Call button, you have 10 seconds to cancel ...",0.1067,0.0820,0.0247,0.1067,0.0656,0.0411,0.7500,0.8000,-0.0500,0.0,1.0,-1.0
4,What is the DEF?,"[{'text': '', 'title': '', 'content': 'vehicle's steering, handling and trac...","The passages do not provide a direct definition of DEF. However, according t...",0.1266,0.0625,0.0641,0.0380,0.0625,-0.0245,0.3000,1.0000,-0.7000,0.0,1.0,-1.0
5,What may cause erratic or noisy performance of the radio?,"[{'text': '', 'title': '', 'content': 'Under certain conditions, the mobile ...",The mobile phone being on in the vehicle can cause erratic or noisy performa...,0.1067,0.1143,-0.0076,0.0933,0.1143,-0.0210,0.8750,1.0000,-0.1250,0.0,1.0,-1.0
6,how to calculate the gross trailer weight?,"[{'text': '', 'title': '', 'content': 'Gross Trailer Weight (GTW) The GTW is...","To calculate the Gross Trailer Weight (GTW), follow these steps:\n\n1. Put y...",0.0811,0.2727,-0.1916,0.1081,0.2727,-0.1646,1.0000,1.0000,0.0000,0.0,1.0,-1.0
7,What can the ASIST button do?,"[{'text': '', 'title': '', 'content': 'Connected Services SOS FAQs — If Equi...",The ASSIST button is used to automatically connect you to any one of the fol...,0.0870,0.4348,-0.3478,0.0870,0.4348,-0.3478,0.3333,1.0000,-0.6667,0.0,1.0,-1.0
8,What does the Door Off Mirror Kit do?,"[{'text': '', 'title': '', 'content': 'For information on the Door Off Mirro...",The Door Off Mirror Kit allows exterior rearview mirrors to be installed ont...,NaN,0.1304,NaN,NaN,0.1304,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
9,Can I manually activate or deactivate the air conditioner?,"[{'text': '', 'title': '', 'content': 'The Air Conditioning (A/C) button all...","To manually activate or deactivate the air conditioner, press and release th...",0.3158,0.0811,0.2347,0.1842,0.1351,0.0491,0.5833,0.6667,-0.0834,0.0,1.0,-1.0
10,what does the The cartridge block heater do?,"[{'text': '', 'title': '', 'content': 'The cartridge block heater clips into...",The cartridge block heater clips into the engine block near the water jacket...,0.2632,0.0492,0.2140,0.3158,0.0492,0.2666,1.0000,1.0000,0.0000,0.0,1.0,-1.0
11,When will the illuminated entry system be activated?,"[{'text': '', 'title': '', 'content': 'Keyless Enter ‘n Go™ — Passive Entry ...","To activate the illuminated entry system, follow these steps:\n1. Push and r...",0.0968,0.0541,0.0427,0.0484,0.0811,-0.0327,0.1667,1.0000,-0.8333,0.0,1.0,-1.0
12,"If the light remains on after the bulb check, it indicates what problem?","[{'text': '', 'title': '', 'content': 'system cannot reprogram a key fob obt...","If the Vehicle Security Light remains on after the bulb check, it indicates ...",0.0278,0.1042,-0.0764,0.0417,0.0208,0.0209,1.0000,0.2000,0.8000,0.0,1.0,-1.0
13,What is special about power windows?,"[{'text': '', 'title': '', 'content': 'The power windows feature allows for ...",The power windows feature allows for movement of the windows with the push o...,0.1410,0.2759,-0.1349,0.1538,0.1379,0.0159,0.8182,0.5000,0.3182,0.0,1.0,-1.0
14,What should I do to jump start the car?,"[{'text': '', 'title': '', 'content': 'of the engine compartment. If your ve...","To jump start the car, follow these steps:\n\n1. Apply the parking brake, sh...",0.7333,0.4127,0.3206,0.4133,0.2063,0.2070,0.5455,0.5000,0.0455,0.0,1.0,-1.0
15,How to deactivate the cruise control?,"[{'text': '', 'title': '', 'content': 'Adaptive Cruise Control Off When ACC ...","To deactivate the cruise control, follow these steps:\n\n1. A soft tap on th...",0.2388,0.4667,-0.2279,0.2836,0.4667,-0.1831,0.3125,0.8571,-0.5446,0.0,1.0,-1.0
16,Is it safe for me to park the vehicle in somewhere very hot?,"[{'text': '', 'title': '', 'content': 'the vehicle is securely connected to ...",WARNING: Do not leave children or animals inside parked vehicles in hot weat...,0.0988,0.1622,-0.0634,0.0988,0.1892,-0.0904,0.5000,1.0000,-0.5000,0.0,1.0,-1.0
17,Any tips for driving downhill?,"[{'text': '', 'title': '', 'content': 'Off-Road Driving Tips', 'metadata': {...","Before driving down a steep hill, you need to determine if it is too steep f...",0.2469,0.5000,-0.2531,0.2222,0.5000,-0.2778,0.8000,1.0000,-0.2000,1.0,1.0,0.0
18,what can the dimmer controls adjust?,"[{'text': '', 'title': '', 'content': 'Dimmer Control The dimmer control is ...",The dimmer control can adjust the following:\n\n1. Brightness of the instrum...,0.0870,0.5000,-0.4130,0.0870,0.5000,-0.4130,1.0000,1.0000,0.0000,0.0,1.0,-1.0
19,how to use the key fob to unlock all the doors?,"[{'text': '', 'title': '', 'content': 'To Lock/Unlock The Doors And Tailgate...","To unlock all the doors using the key fob, push and release the unlock butto...",NaN,0.0312,NaN,NaN,0.0312,NaN,NaN,1.0000,NaN,NaN,1.0,NaN

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.1780,0.2060,0.1608,0.1651,0.1498
1,utilization_score,0.1507,0.1892,0.1082,0.1589,0.1250
2,completeness_score,0.6429,0.8762,0.3125,0.2242,0.3488
3,adherence_score,0.1111,1.0000,0.3143,0.0000,0.8889

None

================================================================================
Configuration: delucionqa_or_v3_embed_bge
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `delucionqa_or_v3_embed_bge`

**name**: delucionqa_or_v3_embed_bge  •  **mode**: test  •  **providers**: {'openrouter': {'type': 'openrouter', 'api_key_env': 'OPENROUTER_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'fixed_word', 'config': {'max_words': 160, 'overlap_words': 24}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'BAAI/bge-base-en-v1.5', 'dimension': 768}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 768}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 5}}]}, 'query_transform': None, 'fusion': None, 'rerank': None}  •  **generation**: {'strategy': 'default', 'provider': 'openrouter', 'config': {'model': 'meta-llama/llama-3.3-70b-instruct', 'temperature': 0.0, 'max_tokens': 512, 'system_prompt': 'You are an automotive owner\'s-manual support assistant. Answer questions\nabout vehicle features, controls, and procedures using ONLY the provided\nowner\'s-manual passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use outside knowledge.\n2. Give exact, step-by-step procedures. Preserve exact control names, button\n   names, warning/CAUTION text, and feature labels verbatim.\n3. Include any safety warnings (WARNING/CAUTION) that the passages attach to\n   the procedure.\n4. Be concise and procedural - give the steps, not background.\n5. If the passages do not contain the answer, respond with exactly:\n   "The passages do not provide sufficient information to answer this question."\n6. Every claim must be directly supported by the passages provided.\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, give exact steps, control names, and any safety warnings):\n'}}  •  **evaluation**: {'type': 'trace', 'provider': 'openrouter', 'config': {'model': 'meta-llama/llama-3.3-70b-instruct', 'temperature': 0.0, 'max_tokens': 2000}}  •  **cache**: {'enabled': True, 'cache_dir': './cache_openrouter_delucionqa'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,What if I fail to latch the tailgate properly?,"[{'text': '', 'title': '', 'content': 'Closing To close the tailgate, lift u...",Failure to securely latch the tailgate could result in damage to the vehicle...,0.3333,0.1111,0.2222,0.2333,0.1111,0.1222,0.6000,1.0000,-0.4000,0.0,1.0,-1.0
1,What kind of safety features are implemented in this car?,"[{'text': '', 'title': '', 'content': 'SAFETY FEATURES When the Safety/Drivi...",The passages mention the following safety features:\n\n1. Occupant Restraint...,0.3077,0.2500,0.0577,0.5385,0.2500,0.2885,0.6250,1.0000,-0.3750,0.0,1.0,-1.0
2,When will the Automatic SOS be triggered?,"[{'text': '', 'title': '', 'content': 'Automatic SOS — If Equipped Automatic...",The passages do not provide sufficient information to answer this question.,0.0303,0.0244,0.0059,0.0000,0.0244,-0.0244,0.0000,1.0000,-1.0000,1.0,1.0,0.0
3,What happens if I accidentally push the SOS Call button?,"[{'text': '', 'title': '', 'content': 'Connected Services SOS FAQs — If Equi...","If you accidentally push the SOS Call button, you have 10 seconds to cancel ...",0.2857,0.0820,0.2037,0.2000,0.0656,0.1344,0.4000,0.8000,-0.4000,0.0,1.0,-1.0
4,What is the DEF?,"[{'text': '', 'title': '', 'content': 'Adding Diesel Exhaust Fluid The DEF g...","The passages do not provide a direct definition of DEF. However, according t...",0.7778,0.0625,0.7153,0.3889,0.0625,0.3264,0.5000,1.0000,-0.5000,0.0,1.0,-1.0
5,What may cause erratic or noisy performance of the radio?,"[{'text': '', 'title': '', 'content': 'Under certain conditions, the mobile ...",The mobile phone being on in your vehicle can cause erratic or noisy perform...,0.4211,0.1143,0.3068,0.4211,0.1143,0.3068,1.0000,1.0000,0.0000,1.0,1.0,0.0
6,how to calculate the gross trailer weight?,"[{'text': '', 'title': '', 'content': 'Gross Trailer Weight (GTW) The GTW is...","To calculate the Gross Trailer Weight (GTW), follow these steps:\n\n1. Put y...",0.1579,0.2727,-0.1148,0.2105,0.2727,-0.0622,1.0000,1.0000,0.0000,0.0,1.0,-1.0
7,What can the ASIST button do?,"[{'text': '', 'title': '', 'content': 'If equipped, the ASSIST Button is use...",The ASSIST button is used to automatically connect you to any one of the fol...,0.1522,0.4348,-0.2826,0.2174,0.4348,-0.2174,0.8571,1.0000,-0.1429,0.0,1.0,-1.0
8,What does the Door Off Mirror Kit do?,"[{'text': '', 'title': '', 'content': 'For information on the Door Off Mirro...",The Door Off Mirror Kit allows exterior rearview mirrors to be installed ont...,0.4400,0.1304,0.3096,0.4400,0.1304,0.3096,0.6364,1.0000,-0.3636,0.0,1.0,-1.0
9,Can I manually activate or deactivate the air conditioner?,"[{'text': '', 'title': '', 'content': 'The Air Conditioning (A/C) button all...","To manually activate or deactivate the air conditioner, press and release th...",0.2000,0.0811,0.1189,0.3429,0.1351,0.2078,0.8571,0.6667,0.1904,0.0,1.0,-1.0
10,what does the The cartridge block heater do?,"[{'text': '', 'title': '', 'content': 'The cartridge block heater clips into...",The cartridge block heater clips into the engine block near the water jacket...,0.3000,0.0492,0.2508,0.3400,0.0492,0.2908,1.0000,1.0000,0.0000,0.0,1.0,-1.0
11,When will the illuminated entry system be activated?,"[{'text': '', 'title': '', 'content': 'When any of these situations occur, a...",The passages do not provide sufficient information to answer this question.,0.2424,0.0541,0.1883,0.0000,0.0811,-0.0811,0.0000,1.0000,-1.0000,1.0,1.0,0.0
12,"If the light remains on after the bulb check, it indicates what problem?","[{'text': '', 'title': '', 'content': 'If the Brake System Warning Light rem...","According to Document 2, if the Air Bag Warning Light ""stays on"" after the b...",0.3438,0.1042,0.2396,0.0625,0.0208,0.0417,0.1818,0.2000,-0.0182,0.0,1.0,-1.0
13,What is special about power windows?,"[{'text': '', 'title': '', 'content': 'The power windows feature allows for ...",The power windows feature allows for movement of the windows with the push o...,0.3810,0.2759,0.1051,0.3333,0.1379,0.1954,0.8125,0.5000,0.3125,1.0,1.0,0.0
14,What should I do to jump start the car?,"[{'text': '', 'title': '', 'content': 'of the engine compartment. If your ve...","To jump start the car, follow these steps: \n1. Apply the parking brake, \n2...",0.8810,0.4127,0.4683,0.6429,0.2063,0.4366,0.7297,0.5000,0.2297,0.0,1.0,-1.0
15,How to deactivate the cruise control?,"[{'text': '', 'title': '', 'content': 'When ACC is deactivated, the display ...","To deactivate the Cruise Control, follow these steps:\n1. A soft tap on the ...",0.2692,0.4667,-0.1975,0.3462,0.4667,-0.1205,0.7143,0.8571,-0.1428,0.0,1.0,-1.0
16,Is it safe for me to park the vehicle in somewhere very hot?,"[{'text': '', 'title': '', 'content': 'driving in hot weather, up mountain g...",WARNING: Do not leave children or animals inside parked vehicles in hot weat...,0.5800,0.1622,0.4178,0.3000,0.1892,0.1108,0.5172,1.0000,-0.4828,0.0,1.0,-1.0
17,Any tips for driving downhill?,"[{'text': '', 'title': '', 'content': 'Off-Road Driving Tips', 'metadata': {...","To drive downhill, follow these steps:\n1. Determine if the hill is too stee...",0.5366,0.5000,0.0366,0.5366,0.5000,0.0366,0.8182,1.0000,-0.1818,0.0,1.0,-1.0
18,what can the dimmer controls adjust?,"[{'text': '', 'title': '', 'content': 'Dimmer Control The dimmer control is ...",The dimmer control can adjust the following:\n\n1. Brightness of the instrum...,0.2857,0.5000,-0.2143,0.2857,0.5000,-0.2143,1.0000,1.0000,0.0000,1.0,1.0,0.0
19,how to use the key fob to unlock all the doors?,"[{'text': '', 'title': '', 'content': 'To Lock/Unlock The Doors And Tailgate...","To unlock all the doors using the key fob, push and release the unlock butto...",0.1333,0.0312,0.1021,0.0667,0.0312,0.0354,0.5000,1.0000,-0.5000,0.0,1.0,-1.0

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.3530,0.2060,0.2056,0.1651,0.2279
1,utilization_score,0.2953,0.1892,0.1731,0.1589,0.1781
2,completeness_score,0.6375,0.8762,0.3025,0.2242,0.3120
3,adherence_score,0.2500,1.0000,0.4330,0.0000,0.7500

None

================================================================================
Configuration: delucionqa_or_v4_chunk_sentence
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `delucionqa_or_v4_chunk_sentence`

**name**: delucionqa_or_v4_chunk_sentence  •  **mode**: test  •  **providers**: {'openrouter': {'type': 'openrouter', 'api_key_env': 'OPENROUTER_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'sentence', 'config': {'max_words': 150, 'overlap_sentences': 1}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'sentence-transformers/all-MiniLM-L6-v2', 'dimension': 384}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 384}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 5}}]}, 'query_transform': None, 'fusion': None, 'rerank': None}  •  **generation**: {'strategy': 'default', 'provider': 'openrouter', 'config': {'model': 'meta-llama/llama-3.3-70b-instruct', 'temperature': 0.0, 'max_tokens': 512, 'system_prompt': 'You are an automotive owner\'s-manual support assistant. Answer questions\nabout vehicle features, controls, and procedures using ONLY the provided\nowner\'s-manual passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use outside knowledge.\n2. Give exact, step-by-step procedures. Preserve exact control names, button\n   names, warning/CAUTION text, and feature labels verbatim.\n3. Include any safety warnings (WARNING/CAUTION) that the passages attach to\n   the procedure.\n4. Be concise and procedural - give the steps, not background.\n5. If the passages do not contain the answer, respond with exactly:\n   "The passages do not provide sufficient information to answer this question."\n6. Every claim must be directly supported by the passages provided.\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, give exact steps, control names, and any safety warnings):\n'}}  •  **evaluation**: {'type': 'trace', 'provider': 'openrouter', 'config': {'model': 'meta-llama/llama-3.3-70b-instruct', 'temperature': 0.0, 'max_tokens': 2000}}  •  **cache**: {'enabled': True, 'cache_dir': './cache_openrouter_delucionqa'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,What if I fail to latch the tailgate properly?,"[{'text': '', 'title': '', 'content': 'If the Tonneau Cover is installed, ma...","According to the passages, if you fail to securely latch the tailgate, it ""c...",0.2174,0.1111,0.1063,0.2609,0.1111,0.1498,0.8000,1.0000,-0.2000,0.0,1.0,-1.0
1,What kind of safety features are implemented in this car?,"[{'text': '', 'title': '', 'content': 'OCCUPANT RESTRAINT SYSTEMS Some of th...",The passages do not provide sufficient information to answer this question i...,0.6667,0.2500,0.4167,0.3939,0.2500,0.1439,0.5000,1.0000,-0.5000,0.0,1.0,-1.0
2,When will the Automatic SOS be triggered?,"[{'text': '', 'title': '', 'content': 'Automatic SOS — If Equipped Automatic...",The passages do not provide sufficient information to answer this question.,NaN,0.0244,NaN,NaN,0.0244,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
3,What happens if I accidentally push the SOS Call button?,"[{'text': '', 'title': '', 'content': 'Connected Services SOS FAQs — If Equi...","If you accidentally push the SOS Call button, you have 10 seconds to cancel ...",0.3704,0.0820,0.2884,0.1852,0.0656,0.1196,0.4000,0.8000,-0.4000,0.0,1.0,-1.0
4,What is the DEF?,"[{'text': '', 'title': '', 'content': 'DEF tank DEF pump DEF injector Electr...","The passages do not provide a direct definition of DEF. However, according t...",0.6400,0.0625,0.5775,0.2000,0.0625,0.1375,0.3125,1.0000,-0.6875,0.0,1.0,-1.0
5,What may cause erratic or noisy performance of the radio?,"[{'text': '', 'title': '', 'content': 'Under certain conditions, the mobile ...",The mobile phone being on in your vehicle can cause erratic or noisy perform...,0.2105,0.1143,0.0962,0.0526,0.1143,-0.0617,0.2500,1.0000,-0.7500,0.0,1.0,-1.0
6,how to calculate the gross trailer weight?,"[{'text': '', 'title': '', 'content': 'Gross Trailer Weight (GTW) The GTW is...","To calculate the Gross Trailer Weight (GTW), follow these steps:\n\n1. Put y...",0.1875,0.2727,-0.0852,0.2500,0.2727,-0.0227,1.0000,1.0000,0.0000,0.0,1.0,-1.0
7,What can the ASIST button do?,"[{'text': '', 'title': '', 'content': 'These buttons will be located on eith...",The ASSIST Button is used for contacting:\n1 — Roadside Assistance\n2 — Vehi...,0.3750,0.4348,-0.0598,0.2812,0.4348,-0.1536,0.3333,1.0000,-0.6667,0.0,1.0,-1.0
8,What does the Door Off Mirror Kit do?,"[{'text': '', 'title': '', 'content': 'Door Off Mirror Kit — If Equipped If ...",The Door Off Mirror Kit allows exterior rearview mirrors to be installed ont...,0.4444,0.1304,0.3140,0.3704,0.1304,0.2400,0.6667,1.0000,-0.3333,0.0,1.0,-1.0
9,Can I manually activate or deactivate the air conditioner?,"[{'text': '', 'title': '', 'content': 'The Air Conditioning (A/C) button all...","To manually activate or deactivate the air conditioner, press and release th...",0.4500,0.0811,0.3689,0.3750,0.1351,0.2399,0.6667,0.6667,0.0000,0.0,1.0,-1.0
10,what does the The cartridge block heater do?,"[{'text': '', 'title': '', 'content': 'The cartridge block heater clips into...",The cartridge block heater clips into the engine block near the water jacket...,0.8378,0.0492,0.7886,0.5405,0.0492,0.4913,0.6452,1.0000,-0.3548,0.0,1.0,-1.0
11,When will the illuminated entry system be activated?,"[{'text': '', 'title': '', 'content': 'Keyless Enter ‘n Go™ — Passive Entry ...",The passages do not provide sufficient information to answer this question.,0.2727,0.0541,0.2186,0.0000,0.0811,-0.0811,0.0000,1.0000,-1.0000,1.0,1.0,0.0
12,"If the light remains on after the bulb check, it indicates what problem?","[{'text': '', 'title': '', 'content': 'Your vehicle is equipped with a sophi...","According to Document 2, if the Malfunction Indicator Light (MIL) ""will flas...",0.2647,0.1042,0.1605,0.1471,0.0208,0.1263,0.5556,0.2000,0.3556,0.0,1.0,-1.0
13,What is special about power windows?,"[{'text': '', 'title': '', 'content': 'The power windows feature allows for ...",The power windows feature allows for movement of the windows with the push o...,0.4815,0.2759,0.2056,0.3704,0.1379,0.2325,0.7692,0.5000,0.2692,1.0,1.0,0.0
14,What should I do to jump start the car?,"[{'text': '', 'title': '', 'content': 'Preparations For Jump Start The batte...","To jump start the car, follow these steps:\n\n1. Apply the parking brake, \n...",0.9474,0.4127,0.5347,0.6842,0.2063,0.4779,0.7222,0.5000,0.2222,1.0,1.0,0.0
15,How to deactivate the cruise control?,"[{'text': '', 'title': '', 'content': 'To Activate/Deactivate Push and relea...","To deactivate the Cruise Control, follow these steps:\n\n1. A soft tap on th...",0.5862,0.4667,0.1195,0.4138,0.4667,-0.0529,0.5294,0.8571,-0.3277,0.0,1.0,-1.0
16,Is it safe for me to park the vehicle in somewhere very hot?,"[{'text': '', 'title': '', 'content': 'Transporting Passengers NEVER TRANSPO...",CAUTION: Never park your vehicle over dry grass or other combustible materia...,0.2162,0.1622,0.0540,0.2703,0.1892,0.0811,1.0000,1.0000,0.0000,0.0,1.0,-1.0
17,Any tips for driving downhill?,"[{'text': '', 'title': '', 'content': 'Driving Up Hill Once you have determi...","To drive downhill, follow these steps:\n1. Determine if the hill is too stee...",0.3871,0.5000,-0.1129,0.3871,0.5000,-0.1129,1.0000,1.0000,0.0000,0.0,1.0,-1.0
18,what can the dimmer controls adjust?,"[{'text': '', 'title': '', 'content': 'Dimmer Control The dimmer control is ...","According to the passages, the dimmer control can adjust:\n\n1. The brightne...",0.3077,0.5000,-0.1923,0.2308,0.5000,-0.2692,0.7500,1.0000,-0.2500,1.0,1.0,0.0
19,how to use the key fob to unlock all the doors?,"[{'text': '', 'title': '', 'content': 'To Lock/Unlock The Doors And Tailgate...","To unlock all the doors using the key fob, push and release the unlock butto...",0.1429,0.0312,0.1116,0.1071,0.0312,0.0759,0.2500,1.0000,-0.7500,0.0,1.0,-1.0

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.4214,0.2060,0.2196,0.1651,0.2532
1,utilization_score,0.2906,0.1892,0.1612,0.1589,0.1721
2,completeness_score,0.5869,0.8762,0.2724,0.2242,0.3720
3,adherence_score,0.2105,1.0000,0.4077,0.0000,0.7895

None

================================================================================
Configuration: delucionqa_or_v5_hybrid_rrf
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `delucionqa_or_v5_hybrid_rrf`

**name**: delucionqa_or_v5_hybrid_rrf  •  **mode**: test  •  **providers**: {'openrouter': {'type': 'openrouter', 'api_key_env': 'OPENROUTER_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'fixed_word', 'config': {'max_words': 160, 'overlap_words': 24}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'sentence-transformers/all-MiniLM-L6-v2', 'dimension': 384}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 384}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 20}}, {'type': 'sparse', 'config': {'top_k': 20}}]}, 'query_transform': None, 'fusion': {'type': 'rrf', 'config': {'top_k': 10, 'k': 60}}, 'rerank': None}  •  **generation**: {'strategy': 'default', 'provider': 'openrouter', 'config': {'model': 'meta-llama/llama-3.3-70b-instruct', 'temperature': 0.0, 'max_tokens': 512, 'system_prompt': 'You are an automotive owner\'s-manual support assistant. Answer questions\nabout vehicle features, controls, and procedures using ONLY the provided\nowner\'s-manual passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use outside knowledge.\n2. Give exact, step-by-step procedures. Preserve exact control names, button\n   names, warning/CAUTION text, and feature labels verbatim.\n3. Include any safety warnings (WARNING/CAUTION) that the passages attach to\n   the procedure.\n4. Be concise and procedural - give the steps, not background.\n5. If the passages do not contain the answer, respond with exactly:\n   "The passages do not provide sufficient information to answer this question."\n6. Every claim must be directly supported by the passages provided.\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, give exact steps, control names, and any safety warnings):\n'}}  •  **evaluation**: {'type': 'trace', 'provider': 'openrouter', 'config': {'model': 'meta-llama/llama-3.3-70b-instruct', 'temperature': 0.0, 'max_tokens': 2000}}  •  **cache**: {'enabled': True, 'cache_dir': './cache_openrouter_delucionqa'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,What if I fail to latch the tailgate properly?,"[{'text': '', 'title': '', 'content': 'If the Tonneau Cover is installed, ma...",Failure to securely latch the tailgate could result in damage to the vehicle...,0.1579,0.1111,0.0468,0.1579,0.1111,0.0468,0.7778,1.0000,-0.2222,0.0,1.0,-1.0
1,What kind of safety features are implemented in this car?,"[{'text': '', 'title': '', 'content': 'OCCUPANT RESTRAINT SYSTEMS Some of th...","To access the safety features, follow these steps: \n1. Select the Safety/Dr...",0.2143,0.2500,-0.0357,0.2857,0.2500,0.0357,0.9167,1.0000,-0.0833,0.0,1.0,-1.0
2,When will the Automatic SOS be triggered?,"[{'text': '', 'title': '', 'content': 'Automatic SOS — If Equipped Automatic...",The passages do not provide sufficient information to answer this question.,0.1746,0.0244,0.1502,0.0000,0.0244,-0.0244,0.0000,1.0000,-1.0000,0.0,1.0,-1.0
3,What happens if I accidentally push the SOS Call button?,"[{'text': '', 'title': '', 'content': 'Connected Services SOS FAQs — If Equi...","If you accidentally push the SOS Call button, you have 10 seconds to cancel ...",0.0933,0.0820,0.0113,0.0800,0.0656,0.0144,0.8571,0.8000,0.0571,0.0,1.0,-1.0
4,What is the DEF?,"[{'text': '', 'title': '', 'content': 'DEF tank DEF pump DEF injector Electr...","The passages do not provide a direct definition of what DEF is. However, acc...",0.1216,0.0625,0.0591,0.1216,0.0625,0.0591,1.0000,1.0000,0.0000,0.0,1.0,-1.0
5,What may cause erratic or noisy performance of the radio?,"[{'text': '', 'title': '', 'content': 'Under certain conditions, the mobile ...","According to Document 1, the mobile phone being on in the vehicle can cause ...",0.1067,0.1143,-0.0076,0.1067,0.1143,-0.0076,1.0000,1.0000,0.0000,0.0,1.0,-1.0
6,how to calculate the gross trailer weight?,"[{'text': '', 'title': '', 'content': 'Gross Trailer Weight (GTW) The GTW is...","To calculate the Gross Trailer Weight (GTW), follow these steps:\n\n1. Put y...",0.0882,0.2727,-0.1845,0.1176,0.2727,-0.1551,1.0000,1.0000,0.0000,0.0,1.0,-1.0
7,What can the ASIST button do?,"[{'text': '', 'title': '', 'content': 'Connected Services SOS FAQs — If Equi...",The ASSIST button is used to automatically connect you to any one of the fol...,0.0909,0.4348,-0.3439,0.1688,0.4348,-0.2660,0.4286,1.0000,-0.5714,0.0,1.0,-1.0
8,What does the Door Off Mirror Kit do?,"[{'text': '', 'title': '', 'content': 'Door Off Mirror Kit — If Equipped If ...",The Door Off Mirror Kit allows exterior rearview mirrors to be installed ont...,0.3889,0.1304,0.2585,0.3148,0.1304,0.1844,0.7619,1.0000,-0.2381,0.0,1.0,-1.0
9,Can I manually activate or deactivate the air conditioner?,"[{'text': '', 'title': '', 'content': 'The Air Conditioning (A/C) button all...","To manually activate or deactivate the air conditioner, press and release th...",0.1408,0.0811,0.0597,0.2254,0.1351,0.0903,0.9000,0.6667,0.2333,0.0,1.0,-1.0
10,what does the The cartridge block heater do?,"[{'text': '', 'title': '', 'content': 'The cartridge block heater clips into...",The cartridge block heater clips into the engine block near the water jacket...,0.2787,0.0492,0.2295,0.2787,0.0492,0.2295,0.8824,1.0000,-0.1176,0.0,1.0,-1.0
11,When will the illuminated entry system be activated?,"[{'text': '', 'title': '', 'content': 'Keyless Enter ‘n Go™ — Passive Entry ...","To activate the illuminated entry system, follow these steps:\n1. Push and r...",0.0323,0.0541,-0.0218,0.0323,0.0811,-0.0488,0.5000,1.0000,-0.5000,0.0,1.0,-1.0
12,"If the light remains on after the bulb check, it indicates what problem?","[{'text': '', 'title': '', 'content': 'system cannot reprogram a key fob obt...","According to Document 1, if the Vehicle Security Light ""remains on after the...",0.0429,0.1042,-0.0613,0.0286,0.0208,0.0078,0.6667,0.2000,0.4667,0.0,1.0,-1.0
13,What is special about power windows?,"[{'text': '', 'title': '', 'content': 'The power windows feature allows for ...",The power windows feature allows for movement of the windows with the push o...,0.1765,0.2759,-0.0994,0.1647,0.1379,0.0268,0.9333,0.5000,0.4333,0.0,1.0,-1.0
14,What should I do to jump start the car?,"[{'text': '', 'title': '', 'content': 'of the engine compartment. If your ve...","To jump start the car, follow these steps:\n\n1. Apply the parking brake, \n...",NaN,0.4127,NaN,NaN,0.2063,NaN,NaN,0.5000,NaN,NaN,1.0,NaN
15,How to deactivate the cruise control?,"[{'text': '', 'title': '', 'content': 'Adaptive Cruise Control Off When ACC ...","To deactivate the cruise control, follow these steps:\n\n1. A soft tap on th...",NaN,0.4667,NaN,NaN,0.4667,NaN,NaN,0.8571,NaN,NaN,1.0,NaN
16,Is it safe for me to park the vehicle in somewhere very hot?,"[{'text': '', 'title': '', 'content': 'the vehicle is securely connected to ...",WARNING: Do not leave children or animals inside parked vehicles in hot weat...,0.1625,0.1622,0.0003,0.2250,0.1892,0.0358,1.0000,1.0000,0.0000,0.0,1.0,-1.0
17,Any tips for driving downhill?,"[{'text': '', 'title': '', 'content': 'Off-Road Driving Tips', 'metadata': {...","Before driving down a steep hill, you need to determine if it is too steep f...",0.3000,0.5000,-0.2000,0.2375,0.5000,-0.2625,0.7917,1.0000,-0.2083,1.0,1.0,0.0
18,what can the dimmer controls adjust?,"[{'text': '', 'title': '', 'content': 'Dimmer Control The dimmer control is ...",The dimmer control can adjust the following:\n\n1. Brightness of the instrum...,0.1026,0.5000,-0.3974,0.1026,0.5000,-0.3974,1.0000,1.0000,0.0000,0.0,1.0,-1.0
19,how to use the key fob to unlock all the doors?,"[{'text': '', 'title': '', 'content': 'To Lock/Unlock The Doors And Tailgate...","To unlock all the doors using the key fob, push and release the unlock butto...",0.1045,0.0312,0.0732,0.0299,0.0312,-0.0014,0.2857,1.0000,-0.7143,1.0,1.0,0.0

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.1543,0.2060,0.0896,0.1651,0.1245
1,utilization_score,0.1488,0.1892,0.0937,0.1589,0.1052
2,completeness_score,0.7612,0.8762,0.2765,0.2242,0.2692
3,adherence_score,0.1111,1.0000,0.3143,0.0000,0.8889

None

================================================================================
Configuration: delucionqa_or_v6_rerank_only
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `delucionqa_or_v6_rerank_only`

**name**: delucionqa_or_v6_rerank_only  •  **mode**: test  •  **providers**: {'openrouter': {'type': 'openrouter', 'api_key_env': 'OPENROUTER_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'fixed_word', 'config': {'max_words': 160, 'overlap_words': 24}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'sentence-transformers/all-MiniLM-L6-v2', 'dimension': 384}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 384}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 20}}]}, 'query_transform': None, 'fusion': None, 'rerank': {'type': 'cross_encoder', 'config': {'model_name': 'BAAI/bge-reranker-v2-m3', 'top_k': 5}}}  •  **generation**: {'strategy': 'default', 'provider': 'openrouter', 'config': {'model': 'meta-llama/llama-3.3-70b-instruct', 'temperature': 0.0, 'max_tokens': 512, 'system_prompt': 'You are an automotive owner\'s-manual support assistant. Answer questions\nabout vehicle features, controls, and procedures using ONLY the provided\nowner\'s-manual passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use outside knowledge.\n2. Give exact, step-by-step procedures. Preserve exact control names, button\n   names, warning/CAUTION text, and feature labels verbatim.\n3. Include any safety warnings (WARNING/CAUTION) that the passages attach to\n   the procedure.\n4. Be concise and procedural - give the steps, not background.\n5. If the passages do not contain the answer, respond with exactly:\n   "The passages do not provide sufficient information to answer this question."\n6. Every claim must be directly supported by the passages provided.\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, give exact steps, control names, and any safety warnings):\n'}}  •  **evaluation**: {'type': 'trace', 'provider': 'openrouter', 'config': {'model': 'meta-llama/llama-3.3-70b-instruct', 'temperature': 0.0, 'max_tokens': 2000}}  •  **cache**: {'enabled': True, 'cache_dir': './cache_openrouter_delucionqa'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,What if I fail to latch the tailgate properly?,"[{'text': '', 'title': '', 'content': 'Closing To close the tailgate, lift u...",CAUTION: Failure to securely latch the tailgate could result in damage to th...,0.1333,0.1111,0.0222,0.1333,0.1111,0.0222,1.0000,1.0000,0.0000,1.0,1.0,0.0
1,What kind of safety features are implemented in this car?,"[{'text': '', 'title': '', 'content': 'Some of the most important safety fea...","The vehicle has the following safety features: \n1. Restraint systems, \n2. ...",0.5862,0.2500,0.3362,0.7241,0.2500,0.4741,0.7647,1.0000,-0.2353,0.0,1.0,-1.0
2,When will the Automatic SOS be triggered?,"[{'text': '', 'title': '', 'content': 'Automatic SOS — If Equipped Automatic...",The passages do not provide sufficient information to answer this question.,0.0312,0.0244,0.0068,0.0000,0.0244,-0.0244,0.0000,1.0000,-1.0000,0.0,1.0,-1.0
3,What happens if I accidentally push the SOS Call button?,"[{'text': '', 'title': '', 'content': 'Connected Services SOS FAQs — If Equi...","If you accidentally push the SOS Call button, you have 10 seconds to cancel ...",0.2250,0.0820,0.1430,0.1500,0.0656,0.0844,0.4444,0.8000,-0.3556,0.0,1.0,-1.0
4,What is the DEF?,"[{'text': '', 'title': '', 'content': 'System Overview This vehicle is equip...","The passages do not provide a direct definition of what DEF is. However, acc...",NaN,0.0625,NaN,NaN,0.0625,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
5,What may cause erratic or noisy performance of the radio?,"[{'text': '', 'title': '', 'content': 'Under certain conditions, the mobile ...",The mobile phone being on in your vehicle can cause erratic or noisy perform...,NaN,0.1143,NaN,NaN,0.1143,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
6,how to calculate the gross trailer weight?,"[{'text': '', 'title': '', 'content': 'Gross Trailer Weight (GTW) The GTW is...","To calculate the Gross Trailer Weight (GTW), follow these steps:\n\n1. Put y...",0.1579,0.2727,-0.1148,0.2105,0.2727,-0.0622,1.0000,1.0000,0.0000,0.0,1.0,-1.0
7,What can the ASIST button do?,"[{'text': '', 'title': '', 'content': 'ASSIST Call The ASSIST button is used...","To use the ASSIST button, follow these steps: \n1. Push the ASSIST button. \...",0.4615,0.4348,0.0267,0.1795,0.4348,-0.2553,0.3889,1.0000,-0.6111,0.0,1.0,-1.0
8,What does the Door Off Mirror Kit do?,"[{'text': '', 'title': '', 'content': 'Door Off Mirror Kit — If Equipped If ...",The Door Off Mirror Kit allows exterior rearview mirrors to be installed ont...,0.2917,0.1304,0.1613,0.2917,0.1304,0.1613,0.7143,1.0000,-0.2857,0.0,1.0,-1.0
9,Can I manually activate or deactivate the air conditioner?,"[{'text': '', 'title': '', 'content': 'A/C Button Press and release this but...","To manually activate or deactivate the air conditioner, press and release th...",0.3000,0.0811,0.2189,0.2750,0.1351,0.1399,0.4167,0.6667,-0.2500,0.0,1.0,-1.0
10,what does the The cartridge block heater do?,"[{'text': '', 'title': '', 'content': 'Extreme Cold Weather The cartridge bl...",The cartridge block heater clips into the engine block near the water jacket...,0.3200,0.0492,0.2708,0.3000,0.0492,0.2508,0.9375,1.0000,-0.0625,0.0,1.0,-1.0
11,When will the illuminated entry system be activated?,"[{'text': '', 'title': '', 'content': 'Keyless Enter ‘n Go™ — Passive Entry ...",The passages do not provide sufficient information to answer this question.,0.0714,0.0541,0.0173,0.0000,0.0811,-0.0811,0.0000,1.0000,-1.0000,1.0,1.0,0.0
12,"If the light remains on after the bulb check, it indicates what problem?","[{'text': '', 'title': '', 'content': 'system cannot reprogram a key fob obt...","According to Document 1, if the Vehicle Security Light ""remains on after the...",0.1250,0.1042,0.0208,0.0625,0.0208,0.0417,0.5000,0.2000,0.3000,0.0,1.0,-1.0
13,What is special about power windows?,"[{'text': '', 'title': '', 'content': 'The power windows feature allows for ...",The power windows feature allows for movement of the windows with the push o...,0.4103,0.2759,0.1344,0.3590,0.1379,0.2211,0.8125,0.5000,0.3125,0.0,1.0,-1.0
14,What should I do to jump start the car?,"[{'text': '', 'title': '', 'content': 'Preparations For Jump Start The batte...","To jump start the car, follow these steps:\n\n1. Apply the parking brake.\n2...",0.9286,0.4127,0.5159,0.6190,0.2063,0.4127,0.6667,0.5000,0.1667,0.0,1.0,-1.0
15,How to deactivate the cruise control?,"[{'text': '', 'title': '', 'content': 'To Deactivate A soft tap on the brake...","To deactivate the Cruise Control, perform one of the following steps:\n\n1. ...",0.6538,0.4667,0.1871,0.4231,0.4667,-0.0436,0.6471,0.8571,-0.2100,0.0,1.0,-1.0
16,Is it safe for me to park the vehicle in somewhere very hot?,"[{'text': '', 'title': '', 'content': 'and can eventually poison you. To avo...",WARNING: Do not leave children or animals inside parked vehicles in hot weat...,0.4390,0.1622,0.2768,0.2927,0.1892,0.1035,0.6667,1.0000,-0.3333,0.0,1.0,-1.0
17,Any tips for driving downhill?,"[{'text': '', 'title': '', 'content': 'If the engine stalls or you lose head...","To drive downhill, follow these steps:\n1. Determine if the hill is too stee...",0.5556,0.5000,0.0556,0.5556,0.5000,0.0556,0.9600,1.0000,-0.0400,1.0,1.0,0.0
18,what can the dimmer controls adjust?,"[{'text': '', 'title': '', 'content': 'Dimmer Control The dimmer control is ...",The dimmer control can adjust the following:\n\n1. Brightness of the instrum...,0.3810,0.5000,-0.1190,0.2857,0.5000,-0.2143,0.7500,1.0000,-0.2500,1.0,1.0,0.0
19,how to use the key fob to unlock all the doors?,"[{'text': '', 'title': '', 'content': 'To Lock/Unlock The Doors And Tailgate...","To unlock all the doors using the key fob, push and release the unlock butto...",0.2000,0.0312,0.1688,0.2571,0.0312,0.2258,0.1429,1.0000,-0.8571,0.0,1.0,-1.0

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.3484,0.2060,0.2247,0.1651,0.1554
1,utilization_score,0.2844,0.1892,0.1934,0.1589,0.1597
2,completeness_score,0.6007,0.8762,0.3095,0.2242,0.3483
3,adherence_score,0.2222,1.0000,0.4157,0.0000,0.7778

None

================================================================================
Configuration: delucionqa_or_v7_hybrid_rerank
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `delucionqa_or_v7_hybrid_rerank`

**name**: delucionqa_or_v7_hybrid_rerank  •  **mode**: test  •  **providers**: {'openrouter': {'type': 'openrouter', 'api_key_env': 'OPENROUTER_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'fixed_word', 'config': {'max_words': 160, 'overlap_words': 24}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'BAAI/bge-base-en-v1.5', 'dimension': 768}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 768}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 20}}, {'type': 'sparse', 'config': {'top_k': 20}}]}, 'query_transform': None, 'fusion': {'type': 'rrf', 'config': {'top_k': 10, 'k': 60}}, 'rerank': {'type': 'cross_encoder', 'config': {'model_name': 'BAAI/bge-reranker-v2-m3', 'top_k': 5}}}  •  **generation**: {'strategy': 'default', 'provider': 'openrouter', 'config': {'model': 'meta-llama/llama-3.3-70b-instruct', 'temperature': 0.0, 'max_tokens': 512, 'system_prompt': 'You are an automotive owner\'s-manual support assistant. Answer questions\nabout vehicle features, controls, and procedures using ONLY the provided\nowner\'s-manual passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use outside knowledge.\n2. Give exact, step-by-step procedures. Preserve exact control names, button\n   names, warning/CAUTION text, and feature labels verbatim.\n3. Include any safety warnings (WARNING/CAUTION) that the passages attach to\n   the procedure.\n4. Be concise and procedural - give the steps, not background.\n5. If the passages do not contain the answer, respond with exactly:\n   "The passages do not provide sufficient information to answer this question."\n6. Every claim must be directly supported by the passages provided.\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, give exact steps, control names, and any safety warnings):\n'}}  •  **evaluation**: {'type': 'trace', 'provider': 'openrouter', 'config': {'model': 'meta-llama/llama-3.3-70b-instruct', 'temperature': 0.0, 'max_tokens': 2000}}  •  **cache**: {'enabled': True, 'cache_dir': './cache_openrouter_delucionqa'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,What if I fail to latch the tailgate properly?,"[{'text': '', 'title': '', 'content': 'Closing To close the tailgate, lift u...",CAUTION: Failure to securely latch the tailgate could result in damage to th...,NaN,0.1111,NaN,NaN,0.1111,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
1,What kind of safety features are implemented in this car?,"[{'text': '', 'title': '', 'content': 'Some of the most important safety fea...","The vehicle has the following safety features: \n1. Restraint systems, \n2. ...",0.6286,0.2500,0.3786,0.5143,0.2500,0.2643,0.5455,1.0000,-0.4545,0.0,1.0,-1.0
2,When will the Automatic SOS be triggered?,"[{'text': '', 'title': '', 'content': 'Automatic SOS — If Equipped Automatic...",The passages do not provide sufficient information to answer this question.,0.0323,0.0244,0.0079,0.0000,0.0244,-0.0244,0.0000,1.0000,-1.0000,1.0,1.0,0.0
3,What happens if I accidentally push the SOS Call button?,"[{'text': '', 'title': '', 'content': 'Connected Services SOS FAQs — If Equi...","If you accidentally push the SOS Call button, you have 10 seconds to cancel ...",0.3000,0.0820,0.2180,0.2250,0.0656,0.1594,0.7500,0.8000,-0.0500,0.0,1.0,-1.0
4,What is the DEF?,"[{'text': '', 'title': '', 'content': 'System Overview This vehicle is equip...","The passages do not provide a direct definition of DEF. However, according t...",0.3333,0.0625,0.2708,0.2667,0.0625,0.2042,0.7000,1.0000,-0.3000,0.0,1.0,-1.0
5,What may cause erratic or noisy performance of the radio?,"[{'text': '', 'title': '', 'content': 'Under certain conditions, the mobile ...","According to Document 1, the mobile phone being on in the vehicle can cause ...",0.2162,0.1143,0.1019,0.2162,0.1143,0.1019,1.0000,1.0000,0.0000,0.0,1.0,-1.0
6,how to calculate the gross trailer weight?,"[{'text': '', 'title': '', 'content': 'Gross Trailer Weight (GTW) The GTW is...","To calculate the Gross Trailer Weight (GTW), follow these steps:\n\n1. Put y...",0.2105,0.2727,-0.0622,0.2105,0.2727,-0.0622,1.0000,1.0000,0.0000,1.0,1.0,0.0
7,What can the ASIST button do?,"[{'text': '', 'title': '', 'content': 'ASSIST Call The ASSIST button is used...",The ASSIST button is used to automatically connect you to any one of the fol...,0.5517,0.4348,0.1169,0.3793,0.4348,-0.0555,0.6875,1.0000,-0.3125,0.0,1.0,-1.0
8,What does the Door Off Mirror Kit do?,"[{'text': '', 'title': '', 'content': 'Door Off Mirror Kit — If Equipped If ...",The Door Off Mirror Kit allows exterior rearview mirrors to be installed ont...,0.2500,0.1304,0.1196,0.2500,0.1304,0.1196,0.8333,1.0000,-0.1667,0.0,1.0,-1.0
9,Can I manually activate or deactivate the air conditioner?,"[{'text': '', 'title': '', 'content': 'A/C Button Press and release this but...","To manually activate or deactivate the air conditioner, press and release th...",0.3714,0.0811,0.2903,0.2286,0.1351,0.0935,0.4615,0.6667,-0.2052,0.0,1.0,-1.0
10,what does the The cartridge block heater do?,"[{'text': '', 'title': '', 'content': 'Extreme Cold Weather The cartridge bl...",The cartridge block heater clips into the engine block near the water jacket...,0.3913,0.0492,0.3421,0.3261,0.0492,0.2769,0.8333,1.0000,-0.1667,0.0,1.0,-1.0
11,When will the illuminated entry system be activated?,"[{'text': '', 'title': '', 'content': 'Keyless Enter ‘n Go™ — Passive Entry ...",The passages do not provide sufficient information to answer this question.,0.2581,0.0541,0.2040,0.0000,0.0811,-0.0811,0.0000,1.0000,-1.0000,1.0,1.0,0.0
12,"If the light remains on after the bulb check, it indicates what problem?","[{'text': '', 'title': '', 'content': 'system cannot reprogram a key fob obt...","According to Document 1, if the Vehicle Security Light ""remains on after the...",0.1944,0.1042,0.0902,0.0556,0.0208,0.0348,0.2857,0.2000,0.0857,0.0,1.0,-1.0
13,What is special about power windows?,"[{'text': '', 'title': '', 'content': 'The power windows feature allows for ...",The power windows feature allows for movement of the windows with the push o...,0.4444,0.2759,0.1685,0.3889,0.1379,0.2510,0.8125,0.5000,0.3125,0.0,1.0,-1.0
14,What should I do to jump start the car?,"[{'text': '', 'title': '', 'content': 'Preparations For Jump Start The batte...","To jump start the car, follow these steps:\n\n1. Apply the parking brake.\n2...",0.9286,0.4127,0.5159,0.5476,0.2063,0.3413,0.5897,0.5000,0.0897,0.0,1.0,-1.0
15,How to deactivate the cruise control?,"[{'text': '', 'title': '', 'content': 'To Deactivate A soft tap on the brake...","To deactivate the Cruise Control, follow these steps:\n\n1. A soft tap on th...",0.6538,0.4667,0.1871,0.5000,0.4667,0.0333,0.7647,0.8571,-0.0924,0.0,1.0,-1.0
16,Is it safe for me to park the vehicle in somewhere very hot?,"[{'text': '', 'title': '', 'content': 'Transporting Passengers NEVER TRANSPO...",WARNING: Do not leave children or animals inside parked vehicles in hot weat...,0.3400,0.1622,0.1778,0.2800,0.1892,0.0908,0.7059,1.0000,-0.2941,0.0,1.0,-1.0
17,Any tips for driving downhill?,"[{'text': '', 'title': '', 'content': 'If the engine stalls or you lose head...","To drive downhill, follow these steps:\n\n1. Determine if the hill is too st...",0.4615,0.5000,-0.0385,0.4423,0.5000,-0.0577,0.9583,1.0000,-0.0417,1.0,1.0,0.0
18,what can the dimmer controls adjust?,"[{'text': '', 'title': '', 'content': 'Dimmer Control The dimmer control is ...",The dimmer control can adjust the following:\n\n1. Brightness of the instrum...,0.2857,0.5000,-0.2143,0.2143,0.5000,-0.2857,0.7500,1.0000,-0.2500,0.0,1.0,-1.0
19,how to use the key fob to unlock all the doors?,"[{'text': '', 'title': '', 'content': 'To Lock/Unlock The Doors And Tailgate...","To unlock all the doors using the key fob, push and release the unlock butto...",0.1935,0.0312,0.1623,0.0645,0.0312,0.0333,0.3333,1.0000,-0.6667,0.0,1.0,-1.0

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.3708,0.2060,0.2017,0.1651,0.1930
1,utilization_score,0.2689,0.1892,0.1616,0.1589,0.1353
2,completeness_score,0.6322,0.8762,0.2898,0.2242,0.2889
3,adherence_score,0.2105,1.0000,0.4077,0.0000,0.7895

None

================================================================================
Configuration: delucionqa_or_v8_hyde
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `delucionqa_or_v8_hyde`

**name**: delucionqa_or_v8_hyde  •  **mode**: test  •  **providers**: {'openrouter': {'type': 'openrouter', 'api_key_env': 'OPENROUTER_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'fixed_word', 'config': {'max_words': 160, 'overlap_words': 24}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'BAAI/bge-base-en-v1.5', 'dimension': 768}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 768}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 20}}, {'type': 'sparse', 'config': {'top_k': 20}}]}, 'query_transform': {'type': 'hyde', 'provider': 'openrouter', 'config': {'model': 'meta-llama/llama-3.3-70b-instruct', 'temperature': 0.2, 'max_tokens': 256}}, 'fusion': {'type': 'rrf', 'config': {'top_k': 10, 'k': 60}}, 'rerank': {'type': 'cross_encoder', 'config': {'model_name': 'BAAI/bge-reranker-v2-m3', 'top_k': 5}}}  •  **generation**: {'strategy': 'default', 'provider': 'openrouter', 'config': {'model': 'meta-llama/llama-3.3-70b-instruct', 'temperature': 0.0, 'max_tokens': 512, 'system_prompt': 'You are an automotive owner\'s-manual support assistant. Answer questions\nabout vehicle features, controls, and procedures using ONLY the provided\nowner\'s-manual passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use outside knowledge.\n2. Give exact, step-by-step procedures. Preserve exact control names, button\n   names, warning/CAUTION text, and feature labels verbatim.\n3. Include any safety warnings (WARNING/CAUTION) that the passages attach to\n   the procedure.\n4. Be concise and procedural - give the steps, not background.\n5. If the passages do not contain the answer, respond with exactly:\n   "The passages do not provide sufficient information to answer this question."\n6. Every claim must be directly supported by the passages provided.\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, give exact steps, control names, and any safety warnings):\n'}}  •  **evaluation**: {'type': 'trace', 'provider': 'openrouter', 'config': {'model': 'meta-llama/llama-3.3-70b-instruct', 'temperature': 0.0, 'max_tokens': 2000}}  •  **cache**: {'enabled': True, 'cache_dir': './cache_openrouter_delucionqa'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,What if I fail to latch the tailgate properly?,"[{'text': '', 'title': '', 'content': 'Closing To close the tailgate, lift u...",CAUTION: Failure to securely latch the tailgate could result in damage to th...,0.1333,0.1111,0.0222,0.1333,0.1111,0.0222,1.0000,1.0000,0.0000,1.0,1.0,0.0
1,What kind of safety features are implemented in this car?,"[{'text': '', 'title': '', 'content': 'Some of the most important safety fea...",The passages mention the following safety features: \n1. Restraint systems (...,0.6857,0.2500,0.4357,0.6571,0.2500,0.4071,0.6667,1.0000,-0.3333,0.0,1.0,-1.0
2,When will the Automatic SOS be triggered?,"[{'text': '', 'title': '', 'content': 'Automatic SOS — If Equipped Automatic...",The passages do not provide sufficient information to answer this question.,0.0333,0.0244,0.0089,0.0000,0.0244,-0.0244,0.0000,1.0000,-1.0000,0.0,1.0,-1.0
3,What happens if I accidentally push the SOS Call button?,"[{'text': '', 'title': '', 'content': 'Connected Services SOS FAQs — If Equi...","If you accidentally push the SOS Call button, you have 10 seconds to cancel ...",0.2143,0.0820,0.1323,0.2143,0.0656,0.1487,0.4444,0.8000,-0.3556,0.0,1.0,-1.0
4,What is the DEF?,"[{'text': '', 'title': '', 'content': 'System Overview This vehicle is equip...","The passages do not provide a direct definition of DEF. However, according t...",0.4000,0.0625,0.3375,0.1333,0.0625,0.0708,0.2500,1.0000,-0.7500,0.0,1.0,-1.0
5,What may cause erratic or noisy performance of the radio?,"[{'text': '', 'title': '', 'content': 'Under certain conditions, the mobile ...",The mobile phone being on in your vehicle can cause erratic or noisy perform...,0.1778,0.1143,0.0635,0.0444,0.1143,-0.0699,0.2500,1.0000,-0.7500,0.0,1.0,-1.0
6,how to calculate the gross trailer weight?,"[{'text': '', 'title': '', 'content': 'Gross Trailer Weight (GTW) The GTW is...","To calculate the Gross Trailer Weight (GTW), follow these steps:\n\n1. Put y...",0.1579,0.2727,-0.1148,0.2105,0.2727,-0.0622,1.0000,1.0000,0.0000,0.0,1.0,-1.0
7,What can the ASIST button do?,"[{'text': '', 'title': '', 'content': 'ASSIST Call The ASSIST button is used...",The ASSIST button is used to automatically connect you to any one of the fol...,0.4545,0.4348,0.0197,0.3333,0.4348,-0.1015,0.7333,1.0000,-0.2667,0.0,1.0,-1.0
8,What does the Door Off Mirror Kit do?,"[{'text': '', 'title': '', 'content': 'Door Off Mirror Kit — If Equipped If ...",The Door Off Mirror Kit allows exterior rearview mirrors to be installed ont...,0.3077,0.1304,0.1773,0.3462,0.1304,0.2158,0.8750,1.0000,-0.1250,0.0,1.0,-1.0
9,Can I manually activate or deactivate the air conditioner?,"[{'text': '', 'title': '', 'content': 'A/C Button Press and release this but...","To manually activate or deactivate the air conditioner, press and release th...",0.3611,0.0811,0.2800,0.1944,0.1351,0.0593,0.4615,0.6667,-0.2052,0.0,1.0,-1.0
10,what does the The cartridge block heater do?,"[{'text': '', 'title': '', 'content': 'Extreme Cold Weather The cartridge bl...",The cartridge block heater clips into the engine block near the water jacket...,0.4490,0.0492,0.3998,0.3673,0.0492,0.3181,0.7273,1.0000,-0.2727,0.0,1.0,-1.0
11,When will the illuminated entry system be activated?,"[{'text': '', 'title': '', 'content': 'Keyless Enter ‘n Go™ — Passive Entry ...",The passages do not provide sufficient information to answer this question.,0.0741,0.0541,0.0200,0.0000,0.0811,-0.0811,0.0000,1.0000,-1.0000,1.0,1.0,0.0
12,"If the light remains on after the bulb check, it indicates what problem?","[{'text': '', 'title': '', 'content': 'If the light remains on when the park...",The passages do not provide sufficient information to answer this question.,0.2326,0.1042,0.1284,0.0000,0.0208,-0.0208,0.0000,0.2000,-0.2000,1.0,1.0,0.0
13,What is special about power windows?,"[{'text': '', 'title': '', 'content': 'The power windows feature allows for ...",The power windows feature allows for movement of the windows with the push o...,0.4848,0.2759,0.2089,0.4545,0.1379,0.3166,0.8125,0.5000,0.3125,0.0,1.0,-1.0
14,What should I do to jump start the car?,"[{'text': '', 'title': '', 'content': 'Preparations For Jump Start The batte...","To jump start the car, follow these steps:\n\n1. Apply the parking brake.\n2...",0.9286,0.4127,0.5159,0.5952,0.2063,0.3889,0.6410,0.5000,0.1410,1.0,1.0,0.0
15,How to deactivate the cruise control?,"[{'text': '', 'title': '', 'content': 'To Deactivate A soft tap on the brake...","To deactivate the Cruise Control, follow these steps:\n\n1. A soft tap on th...",0.6538,0.4667,0.1871,0.4231,0.4667,-0.0436,0.5294,0.8571,-0.3277,0.0,1.0,-1.0
16,Is it safe for me to park the vehicle in somewhere very hot?,"[{'text': '', 'title': '', 'content': 'Transporting Passengers NEVER TRANSPO...",WARNING: Do not leave children or animals inside parked vehicles in hot weat...,0.5833,0.1622,0.4211,0.3333,0.1892,0.1441,0.5000,1.0000,-0.5000,0.0,1.0,-1.0
17,Any tips for driving downhill?,"[{'text': '', 'title': '', 'content': 'If the engine stalls or you lose head...","To drive downhill, follow these steps:\n\n1. Determine if the hill is too st...",0.6250,0.5000,0.1250,0.4000,0.5000,-0.1000,0.6400,1.0000,-0.3600,0.0,1.0,-1.0
18,what can the dimmer controls adjust?,"[{'text': '', 'title': '', 'content': 'Dimmer Control The dimmer control is ...",The dimmer control can adjust the following:\n1. Brightness of the instrumen...,0.2857,0.5000,-0.2143,0.2857,0.5000,-0.2143,1.0000,1.0000,0.0000,1.0,1.0,0.0
19,how to use the key fob to unlock all the doors?,"[{'text': '', 'title': '', 'content': 'To Lock/Unlock The Doors And Tailgate...","To unlock all the doors using the key fob, push and release the unlock butto...",0.1714,0.0312,0.1401,0.2571,0.0312,0.2258,0.1667,1.0000,-0.8333,0.0,1.0,-1.0

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.3707,0.2060,0.2305,0.1651,0.1976
1,utilization_score,0.2692,0.1892,0.1834,0.1589,0.1518
2,completeness_score,0.5349,0.8762,0.3263,0.2242,0.3867
3,adherence_score,0.2500,1.0000,0.4330,0.0000,0.7500

None

## 10. Compare Configurations

Generate a comparison report across all configurations to see which performs best.

In [12]:
# Generate comparison report
print("Generating comparison report...")
comparison = runner.compare()

print(f"\n✅ Comparison report generated!")
print(f"  Saved to: {experiment_config.report_dir}/comparison.csv")

Generating comparison report...

✅ Comparison report generated!
  Saved to: rag-experiments/delucionqa-openrouter-experiment/reports/comparison.csv

In [13]:
# Display comparison
print("\nConfiguration Comparison:")
display(comparison.to_dataframe())

Configuration Comparison:

,config_name,relevance_score__mean,relevance_score__mae,utilization_score__mean,utilization_score__mae,completeness_score__mean,completeness_score__mae,adherence_score__mean,adherence_score__mae
0,delucionqa_or_v1_baseline,0.2979,0.1954,0.2374,0.1781,0.6330,0.3524,0.1579,0.8421
1,delucionqa_or_v2_hybrid_wsum,0.1780,0.1498,0.1507,0.1250,0.6429,0.3488,0.1111,0.8889
2,delucionqa_or_v3_embed_bge,0.3530,0.2279,0.2953,0.1781,0.6375,0.3120,0.2500,0.7500
3,delucionqa_or_v4_chunk_sentence,0.4214,0.2532,0.2906,0.1721,0.5869,0.3720,0.2105,0.7895
4,delucionqa_or_v5_hybrid_rrf,0.1543,0.1245,0.1488,0.1052,0.7612,0.2692,0.1111,0.8889
5,delucionqa_or_v6_rerank_only,0.3484,0.1554,0.2844,0.1597,0.6007,0.3483,0.2222,0.7778
6,delucionqa_or_v7_hybrid_rerank,0.3708,0.1930,0.2689,0.1353,0.6322,0.2889,0.2105,0.7895
7,delucionqa_or_v8_hyde,0.3707,0.1976,0.2692,0.1518,0.5349,0.3867,0.2500,0.7500

## 11. Summary

The ExperimentRunner provides a complete workflow for:

1. **Configuration-driven data loading** - Specify data source in YAML
2. **Automatic parsing** - Documents parsed using configured parser
3. **Multi-config evaluation** - Test multiple RAG configurations
4. **Parallel execution** - Speed up evaluation with parallel runs
5. **Comprehensive reporting** - Per-query and aggregate metrics
6. **Cross-config comparison** - Identify best performing config

### Key Benefits:

- **Reproducible** - Everything configured in YAML
- **Flexible** - Easy to change data source or parser
- **Scalable** - Parallel execution for faster evaluation
- **Comprehensive** - Detailed metrics and comparisons