# eManual Experiment Runner — OpenRouter variant (parallel to the Groq run)

Same emanual RAG sweep as `emanual_experiment_notebook.ipynb`, but all LLM calls
go through **OpenRouter** instead of Groq. Run this notebook alongside the Groq
one to parallelize without sharing Groq's rate limit.

Driven by `experiment_configs/emanual_openrouter_experiment.yaml` and the configs
under `rag-experiments/emanual-openrouter-experiment/config/`. It uses its own
`temp/`, `reports/`, and `cache_openrouter/` dirs so the two runs never collide.

**Requires** `OPENROUTER_API_KEY` (comma-separate multiple keys to rotate). The
`openai` package must be installed (it is added to the install cell below).

## 1. Setup & Dependencies

In [1]:
get_ipython().system('pip3 install datasets faiss-cpu sentence-transformers torch groq openai python-dotenv nltk pandas -q')

[notice] A new release of pip is available: 26.0 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

## 2. Imports

In [2]:
import sys
import os
from pathlib import Path
from dotenv import load_dotenv

# --- Point this at wherever THIS repo (rag_cust_support) lives. ---
# On Colab this is typically under your mounted Drive. Adjust if different.
PROJECT_ROOT = Path('/content/drive/MyDrive/Capstone/rag_cust_support')
if not PROJECT_ROOT.exists():
    # Fallback: running locally from the notebooks/ folder.
    PROJECT_ROOT = Path.cwd().parent if 'notebooks' in str(Path.cwd()) else Path.cwd()

os.chdir(PROJECT_ROOT)
project_root = PROJECT_ROOT
# Make THIS repo win on sys.path (avoids importing a stale rag-foundry copy).
sys.path = [p for p in sys.path if 'rag-foundry' not in p]
if str(project_root) in sys.path:
    sys.path.remove(str(project_root))
sys.path.insert(0, str(project_root))

from experiment.experiment_config import ExperimentConfig
from experiment.experiment_runner import ExperimentRunner
import experiment.experiment_runner as _er, core.registry as _reg

load_dotenv(override=True)
print('Current directory:', Path.cwd())
print('experiment_runner loaded from:', _er.__file__)
print('core.registry   loaded from:', _reg.__file__)
assert 'rag-foundry' not in _er.__file__, 'Still importing the old rag-foundry code! Restart runtime.'
print('HuggingFace token loaded:', bool(os.getenv('HF_TOKEN')))
print('Groq API key loaded:', bool(os.getenv('GROQ_API_KEY')))
print('OpenRouter API key loaded:', bool(os.getenv('OPENROUTER_API_KEY')))

/Users/bhupendra.bhoi/pandas_env/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Current directory: /Users/bhupendra.bhoi/aiml/Capstone Project/rag_cust_support
experiment_runner loaded from: /Users/bhupendra.bhoi/aiml/Capstone Project/rag_cust_support/experiment/experiment_runner.py
core.registry   loaded from: /Users/bhupendra.bhoi/aiml/Capstone Project/rag_cust_support/core/registry.py
HuggingFace token loaded: True
Groq API key loaded: True
OpenRouter API key loaded: True

## 3. Load Experiment Configuration

The experiment configuration file specifies:
- **data_loader**: How to load data (HuggingFace with dataset_name, subset, split)
- **data_parser**: How to parse documents (title_passage)
- **config_dir**: Directory containing RAG pipeline configs
- **num_queries**: Number of queries to evaluate
- **parallel**: Whether to run configs in parallel

In [3]:
EXPERIMENT_CONFIG_PATH = project_root / "experiment_configs/emanual_experiment.yaml"

experiment_config = ExperimentConfig.load(EXPERIMENT_CONFIG_PATH)

print("Experiment Configuration:")
print(f"  Config Dir:  {experiment_config.config_dir}")
print(f"  Report Dir:  {experiment_config.report_dir}")
print(f"  Temp Dir:    {experiment_config.temp_dir}")
print(f"  Cache:       {experiment_config.cache}")
print(f"  Num Queries: {experiment_config.end_index}")
print(f"  Parallel:    {experiment_config.parallel}")
print(f"  Max Workers: {experiment_config.max_workers}")
print(f"\nData Loader:")
print(f"  Type: {experiment_config.data_loader['type']}")
print(f"  Config: {experiment_config.data_loader['config']}")
print(f"\nData Parser:")
print(f"  Type: {experiment_config.data_parser}")

Experiment Configuration:
  Config Dir:  rag-experiments/emanual-experiment/config
  Report Dir:  rag-experiments/emanual-experiment/reports
  Temp Dir:    rag-experiments/emanual-experiment/temp
  Cache:       {'enabled': True, 'cache_dir': './cache'}
  Num Queries: 20
  Parallel:    False
  Max Workers: 1

Data Loader:
  Type: huggingface
  Config: {'dataset_name': 'galileo-ai/ragbench', 'subset': 'emanual', 'split': 'test', 'limit': 132}

Data Parser:
  Type: noop

## 4. Initialize Experiment Runner

The ExperimentRunner will:
- Create report directory if it doesn't exist
- Load RAG configs from the specified directory
- Load and parse data automatically based on YAML config

In [4]:
# Initialize experiment runner
runner = ExperimentRunner(experiment_config)
print("ExperimentRunner initialized")

ExperimentRunner initialized

In [5]:
# Load data automatically based on YAML configuration
print("Loading data based on experiment configuration...")
documents, raw_data = runner.load_data()

print(f"\n✅ Data loaded successfully!")
print(f"  Documents: {len(documents)} parsed documents")
print(f"  Raw Data:  {len(raw_data)} samples")

# Inspect first sample
first_sample = raw_data[0]
print(f"\nFirst Sample:")
print(f"  Question: {first_sample['question'][:100]}...")
print(f"  Documents: {len(first_sample['documents'])}")

Loading data based on experiment configuration...
Loading HuggingFace dataset: galileo-ai/ragbench/emanual (test)...
Loaded 132 samples

✅ Data loaded successfully!
  Documents: 101 parsed documents
  Raw Data:  132 samples

First Sample:
  Question: I want to  enter into Ambient mode. How can I do that?...
  Documents: 3

## 6. Load RAG Pipeline Configs

Load all RAG pipeline configurations from the config directory specified in the experiment config.

In [6]:
# Load RAG pipeline configs
configs = runner.load_configs()

print(f'Loaded {len(configs)} RAG pipeline configurations:')
for cfg in configs:
    searches = ' + '.join(s.type.value for s in cfg.retrieval.search.searches)
    fusion = cfg.retrieval.fusion.type.value if cfg.retrieval.fusion else '-'
    rerank = cfg.retrieval.rerank.type.value if cfg.retrieval.rerank else '-'
    qx = cfg.retrieval.query_transform.type.value if cfg.retrieval.query_transform else '-'
    gc = cfg.generation.config
    model = gc.get('model') if isinstance(gc, dict) else getattr(gc, 'model', None)
    print(f'  - {cfg.name}')
    print(f'      chunking={cfg.chunking.type.value}  embed={cfg.embedding.type.value}')
    print(f'      search=[{searches}]  fusion={fusion}  rerank={rerank}  q_transform={qx}')
    print(f'      generation_model={model}')

Loaded 9 RAG pipeline configurations:
  - emanual_v11_role_aware_bgem3
      chunking=sentence  embed=sentence_transformer
      search=[dense + sparse]  fusion=rrf  rerank=cross_encoder  q_transform=-
      generation_model=llama-3.3-70b-versatile
  - emanual_v1_baseline
      chunking=fixed_word  embed=sentence_transformer
      search=[dense]  fusion=-  rerank=-  q_transform=-
      generation_model=llama-3.3-70b-versatile
  - emanual_v2_hybrid_wsum
      chunking=fixed_word  embed=sentence_transformer
      search=[dense + sparse]  fusion=weighted_sum  rerank=-  q_transform=-
      generation_model=llama-3.3-70b-versatile
  - emanual_v3_embed_bge
      chunking=fixed_word  embed=sentence_transformer
      search=[dense]  fusion=-  rerank=-  q_transform=-
      generation_model=llama-3.3-70b-versatile
  - emanual_v4_chunk_sentence
      chunking=sentence  embed=sentence_transformer
      search=[dense]  fusion=-  rerank=-  q_transform=-
      generation_model=llama-3.3-70b-versatile
  - emanual_v5_hybrid_rrf
      chunking=fixed_word  embed=sentence_transformer
      search=[dense + sparse]  fusion=rrf  rerank=-  q_transform=-
      generation_model=llama-3.3-70b-versatile
  - emanual_v6_rerank_only
      chunking=fixed_word  embed=sentence_transformer
      search=[dense]  fusion=-  rerank=cross_encoder  q_transform=-
      generation_model=llama-3.3-70b-versatile
  - emanual_v7_hybrid_rerank
      chunking=fixed_word  embed=sentence_transformer
      search=[dense + sparse]  fusion=rrf  rerank=cross_encoder  q_transform=-
      generation_model=llama-3.3-70b-versatile
  - emanual_v8_hyde
      chunking=fixed_word  embed=sentence_transformer
      search=[dense + sparse]  fusion=rrf  rerank=cross_encoder  q_transform=hyde
      generation_model=llama-3.3-70b-versatile

## 7. Run Experiments

Run all RAG configurations on the loaded data. Each config will:
1. Build a vector index from the documents
2. Run queries against the index
3. Generate responses
4. Evaluate using TRACe metrics

Results are returned as PipelineRunResult objects.

In [7]:
get_ipython().system('pip install rank_bm25 -q')

# Run experiments

[notice] A new release of pip is available: 26.0 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [8]:
# Run experiments

print(f"Running {len(configs)} configurations from {experiment_config.start_index} to {experiment_config.end_index} queries...")
print(f"Parallel mode: {experiment_config.parallel}")

runs = runner.run(documents, raw_data)

print(f"\n✅ Experiments completed!")
print(f"  Ran {len(runs)} configurations")

for run in runs:
    print(f"  - {run['config'].name}: {run['total_written']} queries")

Running 9 configurations from 0 to 20 queries...
Parallel mode: False
Loading embedding model: BAAI/bge-m3

Loading weights: 100%|██████████| 391/391 [00:00<00:00, 60778.00it/s]

Loading reranker model: BAAI/bge-reranker-v2-m3

Loading weights: 100%|██████████| 393/393 [00:00<00:00, 6343.24it/s]

Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 5sUsing key #0: ****Yzkz
Using key #0: ****Yzkz
Progress: 2/20 (10.0%) | QPS: 0.17 | ETA: 1.8m | Elapsed: 12ssUsing key #0: ****Yzkz
Using key #0: ****Yzkz
Progress: 3/20 (15.0%) | QPS: 0.19 | ETA: 1.5m | Elapsed: 16sUsing key #0: ****Yzkz
Progress: 4/20 (20.0%) | QPS: 0.12 | ETA: 2.3m | Elapsed: 34sUsing key #0: ****Yzkz
Progress: 5/20 (25.0%) | QPS: 0.09 | ETA: 2.7m | Elapsed: 53sUsing key #0: ****Yzkz
Progress: 6/20 (30.0%) | QPS: 0.08 | ETA: 2.8m | Elapsed: 1.2mUsing key #0: ****Yzkz
Progress: 6/20 (30.0%) | QPS: 0.08 | ETA: 2.8m | Elapsed: 1.2m================================================================================
429 on ****Yzkz
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq21xc5dec58dfyhejka65td` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11290, Requested 4429. Please try again in 18.595s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sun, 26 Jul 2026 04:54:20 GMT
  content-type: application/json
  content-length: 385
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 19
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 994
  x-ratelimit-remaining-tokens: 710
  x-ratelimit-reset-requests: 8m38.4s
  x-ratelimit-reset-tokens: 56.449s
  x-request-id: req_01kyeccatefhqam36kec1ma7cm
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a210ce4b5aadcd03-HYD
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq21xc5dec58dfyhejka65td` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11290, Requested 4429. Please try again in 18.595s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 19
{'provider': 'groq', 'current_index': 0, 'keys': [{'key_suffix': 'Yzkz', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 24, 39, 727653), 'requests': 8, 'successes': 6, 'failures': 1, '429s': 1}, {'key_suffix': 'Fxew', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'yNwZ', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'isl2', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'DJvI', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': '7gBP', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}]}
Using key #1: ****Fxew
Progress: 7/20 (35.0%) | QPS: 0.09 | ETA: 2.3m | Elapsed: 1.3mUsing key #1: ****Fxew
Progress: 8/20 (40.0%) | QPS: 0.10 | ETA: 2.0m | Elapsed: 1.3mUsing key #1: ****Fxew
Progress: 9/20 (45.0%) | QPS: 0.11 | ETA: 1.7m | Elapsed: 1.4mUsing key #1: ****Fxew
Progress: 10/20 (50.0%) | QPS: 0.11 | ETA: 1.5m | Elapsed: 1.5mUsing key #1: ****Fxew
Progress: 11/20 (55.0%) | QPS: 0.11 | ETA: 1.3m | Elapsed: 1.6mUsing key #1: ****Fxew
Progress: 12/20 (60.0%) | QPS: 0.10 | ETA: 1.3m | Elapsed: 1.9m================================================================================
429 on ****Fxew
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyay0bp1em1bnwtc93xw53kw` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11148, Requested 4477. Please try again in 18.125s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sun, 26 Jul 2026 04:55:05 GMT
  content-type: application/json
  content-length: 385
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 19
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 995
  x-ratelimit-remaining-tokens: 852
  x-ratelimit-reset-requests: 7m12s
  x-ratelimit-reset-tokens: 55.74s
  x-request-id: req_01kyecdpdne3r9n8sr69benctf
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a210cf6268f9c508-HYD
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyay0bp1em1bnwtc93xw53kw` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11148, Requested 4477. Please try again in 18.125s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 19
{'provider': 'groq', 'current_index': 1, 'keys': [{'key_suffix': 'Yzkz', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 24, 39, 727653), 'requests': 8, 'successes': 7, 'failures': 1, '429s': 1}, {'key_suffix': 'Fxew', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 25, 24, 375564), 'requests': 6, 'successes': 5, 'failures': 1, '429s': 1}, {'key_suffix': 'yNwZ', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'isl2', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'DJvI', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': '7gBP', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}]}
Using key #2: ****yNwZ
Progress: 12/20 (60.0%) | QPS: 0.10 | ETA: 1.3m | Elapsed: 2.0mUsing key #2: ****yNwZ
Progress: 14/20 (70.0%) | QPS: 0.12 | ETA: 52s | Elapsed: 2.0mmUsing key #2: ****yNwZ
Progress: 15/20 (75.0%) | QPS: 0.12 | ETA: 41s | Elapsed: 2.1mUsing key #2: ****yNwZ
Progress: 15/20 (75.0%) | QPS: 0.12 | ETA: 42s | Elapsed: 2.1mUsing key #2: ****yNwZ
Progress: 16/20 (80.0%) | QPS: 0.11 | ETA: 35s | Elapsed: 2.3mUsing key #2: ****yNwZ
Progress: 17/20 (85.0%) | QPS: 0.11 | ETA: 28s | Elapsed: 2.6mUsing key #2: ****yNwZ
Progress: 18/20 (90.0%) | QPS: 0.10 | ETA: 20s | Elapsed: 2.9mUsing key #2: ****yNwZ
Progress: 19/20 (95.0%) | QPS: 0.10 | ETA: 10s | Elapsed: 3.2m================================================================================
429 on ****yNwZ
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyayk6txfny8n7ahf9xc9x96` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11190, Requested 4108. Please try again in 16.489999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sun, 26 Jul 2026 04:56:23 GMT
  content-type: application/json
  content-length: 391
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 17
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 993
  x-ratelimit-remaining-tokens: 810
  x-ratelimit-reset-requests: 10m4.8s
  x-ratelimit-reset-tokens: 55.95s
  x-request-id: req_01kyecg2n1e9r8qrh7jr327x85
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a210d14a4b29c508-HYD
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyayk6txfny8n7ahf9xc9x96` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11190, Requested 4108. Please try again in 16.489999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 17
{'provider': 'groq', 'current_index': 2, 'keys': [{'key_suffix': 'Yzkz', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 24, 39, 727653), 'requests': 8, 'successes': 7, 'failures': 1, '429s': 1}, {'key_suffix': 'Fxew', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 25, 24, 375564), 'requests': 6, 'successes': 5, 'failures': 1, '429s': 1}, {'key_suffix': 'yNwZ', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 26, 40, 435498), 'requests': 8, 'successes': 7, 'failures': 1, '429s': 1}, {'key_suffix': 'isl2', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'DJvI', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': '7gBP', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}]}
Using key #3: ****isl2
Progress: 20/20 (100.0%) | QPS: 0.10 | ETA: 0s | Elapsed: 3.3m
Loading embedding model: sentence-transformers/all-MiniLM-L6-v2

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 8090.59it/s]

Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 0sUsing key #3: ****isl2
Using key #3: ****isl2
Using key #3: ****isl2
Using key #3: ****isl2
Using key #3: ****isl2
Using key #3: ****isl2
Using key #3: ****isl2
Progress: 5/20 (25.0%) | QPS: 4.98 | ETA: 3s | Elapsed: 1sUsing key #3: ****isl2
Using key #3: ****isl2
Progress: 7/20 (35.0%) | QPS: 3.48 | ETA: 4s | Elapsed: 2sUsing key #3: ****isl2
Using key #3: ****isl2
Progress: 9/20 (45.0%) | QPS: 1.79 | ETA: 6s | Elapsed: 5sUsing key #3: ****isl2
Progress: 10/20 (50.0%) | QPS: 0.99 | ETA: 10s | Elapsed: 10sUsing key #3: ****isl2
================================================================================
429 on ****isl2
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyayrpkneawrsb0tg3sgy3r7` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11651, Requested 1019. Please try again in 3.35s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sun, 26 Jul 2026 04:56:42 GMT
  content-type: application/json
  content-length: 383
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 4
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 988
  x-ratelimit-remaining-tokens: 349
  x-ratelimit-reset-requests: 17m16.8s
  x-ratelimit-reset-tokens: 58.254s
  x-request-id: req_01kyecgn43fyfsgh9kq851e56y
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a210d1c08a17ba26-HYD
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyayrpkneawrsb0tg3sgy3r7` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11651, Requested 1019. Please try again in 3.35s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 4
{'provider': 'groq', 'current_index': 3, 'keys': [{'key_suffix': 'Yzkz', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 24, 39, 727653), 'requests': 8, 'successes': 7, 'failures': 1, '429s': 1}, {'key_suffix': 'Fxew', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 25, 24, 375564), 'requests': 6, 'successes': 5, 'failures': 1, '429s': 1}, {'key_suffix': 'yNwZ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 26, 40, 435498), 'requests': 8, 'successes': 7, 'failures': 1, '429s': 1}, {'key_suffix': 'isl2', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 26, 46, 346920), 'requests': 14, 'successes': 12, 'failures': 1, '429s': 1}, {'key_suffix': 'DJvI', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': '7gBP', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}]}
Using key #4: ****DJvI
Using key #4: ****DJvI
Progress: 12/20 (60.0%) | QPS: 1.09 | ETA: 7s | Elapsed: 11sUsing key #4: ****DJvI
Using key #4: ****DJvI
Using key #4: ****DJvI
Progress: 15/20 (75.0%) | QPS: 1.24 | ETA: 4s | Elapsed: 12sUsing key #4: ****DJvI
Using key #4: ****DJvI
Using key #4: ****DJvI
Progress: 20/20 (100.0%) | QPS: 1.42 | ETA: 0s | Elapsed: 14s
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 0sUsing key #4: ****DJvI
Using key #4: ****DJvI
Using key #4: ****DJvI
Progress: 2/20 (10.0%) | QPS: 0.99 | ETA: 18s | Elapsed: 2sUsing key #4: ****DJvI
Progress: 2/20 (10.0%) | QPS: 0.22 | ETA: 1.4m | Elapsed: 9sUsing key #4: ****DJvI
Progress: 3/20 (15.0%) | QPS: 0.30 | ETA: 57s | Elapsed: 10s================================================================================
429 on ****DJvI
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyayyr8gf2abv4dvzasffv7j` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11637, Requested 1531. Please try again in 5.84s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sun, 26 Jul 2026 04:56:56 GMT
  content-type: application/json
  content-length: 383
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 6
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 989
  x-ratelimit-remaining-tokens: 363
  x-ratelimit-reset-requests: 15m50.4s
  x-ratelimit-reset-tokens: 58.185s
  x-request-id: req_01kyech2yafzf89t99e024228h
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a210d218e8dcdf6e-HYD
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyayyr8gf2abv4dvzasffv7j` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11637, Requested 1531. Please try again in 5.84s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 6
{'provider': 'groq', 'current_index': 4, 'keys': [{'key_suffix': 'Yzkz', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 24, 39, 727653), 'requests': 8, 'successes': 7, 'failures': 1, '429s': 1}, {'key_suffix': 'Fxew', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 25, 24, 375564), 'requests': 6, 'successes': 5, 'failures': 1, '429s': 1}, {'key_suffix': 'yNwZ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 26, 40, 435498), 'requests': 8, 'successes': 7, 'failures': 1, '429s': 1}, {'key_suffix': 'isl2', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 26, 46, 346920), 'requests': 14, 'successes': 13, 'failures': 1, '429s': 1}, {'key_suffix': 'DJvI', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 27, 2, 501547), 'requests': 13, 'successes': 11, 'failures': 1, '429s': 1}, {'key_suffix': '7gBP', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}]}
Using key #5: ****7gBP
Using key #5: ****7gBP
Progress: 4/20 (20.0%) | QPS: 0.36 | ETA: 44s | Elapsed: 11sUsing key #5: ****7gBP
Using key #5: ****7gBP
Progress: 6/20 (30.0%) | QPS: 0.50 | ETA: 28s | Elapsed: 12sUsing key #5: ****7gBP
Using key #5: ****7gBP
Progress: 8/20 (40.0%) | QPS: 0.61 | ETA: 20s | Elapsed: 13sUsing key #5: ****7gBP
Using key #5: ****7gBP
Using key #5: ****7gBP
Progress: 11/20 (55.0%) | QPS: 0.68 | ETA: 13s | Elapsed: 16sUsing key #5: ****7gBP
Progress: 12/20 (60.0%) | QPS: 0.57 | ETA: 14s | Elapsed: 21sUsing key #5: ****7gBP
Progress: 13/20 (65.0%) | QPS: 0.48 | ETA: 15s | Elapsed: 27sUsing key #5: ****7gBP
Progress: 14/20 (70.0%) | QPS: 0.48 | ETA: 12s | Elapsed: 29s================================================================================
429 on ****7gBP
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyaz4w9sf2n85wmxftrm7c8d` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11151, Requested 1543. Please try again in 3.47s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sun, 26 Jul 2026 04:57:16 GMT
  content-type: application/json
  content-length: 383
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 4
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 990
  x-ratelimit-remaining-tokens: 849
  x-ratelimit-reset-requests: 14m24s
  x-ratelimit-reset-tokens: 55.755s
  x-request-id: req_01kyechp6redkscb62j1p4ndzk
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a210d29449d42982-HYD
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyaz4w9sf2n85wmxftrm7c8d` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11151, Requested 1543. Please try again in 3.47s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 4
{'provider': 'groq', 'current_index': 5, 'keys': [{'key_suffix': 'Yzkz', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 24, 39, 727653), 'requests': 8, 'successes': 7, 'failures': 1, '429s': 1}, {'key_suffix': 'Fxew', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 25, 24, 375564), 'requests': 6, 'successes': 5, 'failures': 1, '429s': 1}, {'key_suffix': 'yNwZ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 26, 40, 435498), 'requests': 8, 'successes': 7, 'failures': 1, '429s': 1}, {'key_suffix': 'isl2', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 26, 46, 346920), 'requests': 14, 'successes': 13, 'failures': 1, '429s': 1}, {'key_suffix': 'DJvI', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 27, 2, 501547), 'requests': 13, 'successes': 12, 'failures': 1, '429s': 1}, {'key_suffix': '7gBP', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 27, 20, 228232), 'requests': 12, 'successes': 10, 'failures': 1, '429s': 1}]}
Using key #0: ****Yzkz
Progress: 14/20 (70.0%) | QPS: 0.46 | ETA: 13s | Elapsed: 30sUsing key #0: ****Yzkz
Using key #0: ****Yzkz
Progress: 16/20 (80.0%) | QPS: 0.51 | ETA: 8s | Elapsed: 31sUsing key #0: ****Yzkz
Progress: 17/20 (85.0%) | QPS: 0.53 | ETA: 6s | Elapsed: 32sUsing key #0: ****Yzkz
Progress: 20/20 (100.0%) | QPS: 0.59 | ETA: 0s | Elapsed: 34s
Loading embedding model: BAAI/bge-base-en-v1.5

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 6322.70it/s]

Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 0sUsing key #0: ****Yzkz
Using key #0: ****Yzkz
Using key #0: ****Yzkz
Using key #0: ****Yzkz
Using key #0: ****Yzkz
Using key #0: ****Yzkz
Progress: 4/20 (20.0%) | QPS: 3.99 | ETA: 4s | Elapsed: 1sUsing key #0: ****Yzkz
Using key #0: ****Yzkz
Using key #0: ****Yzkz
Progress: 8/20 (40.0%) | QPS: 3.98 | ETA: 3s | Elapsed: 2sUsing key #0: ****Yzkz
Progress: 8/20 (40.0%) | QPS: 1.99 | ETA: 6s | Elapsed: 4sUsing key #0: ****Yzkz
Progress: 9/20 (45.0%) | QPS: 1.12 | ETA: 10s | Elapsed: 8s================================================================================
429 on ****Yzkz
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq21xc5dec58dfyhejka65td` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11644, Requested 1051. Please try again in 3.475s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sun, 26 Jul 2026 04:57:36 GMT
  content-type: application/json
  content-length: 384
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 4
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 979
  x-ratelimit-remaining-tokens: 356
  x-ratelimit-reset-requests: 30m14.4s
  x-ratelimit-reset-tokens: 58.22s
  x-request-id: req_01kyecj9qyefpvf6w8gd65wvfh
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a210d3113ea47e55-HYD
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq21xc5dec58dfyhejka65td` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11644, Requested 1051. Please try again in 3.475s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 4
{'provider': 'groq', 'current_index': 0, 'keys': [{'key_suffix': 'Yzkz', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 27, 40, 233828), 'requests': 24, 'successes': 21, 'failures': 2, '429s': 2}, {'key_suffix': 'Fxew', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 25, 24, 375564), 'requests': 6, 'successes': 5, 'failures': 1, '429s': 1}, {'key_suffix': 'yNwZ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 26, 40, 435498), 'requests': 8, 'successes': 7, 'failures': 1, '429s': 1}, {'key_suffix': 'isl2', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 26, 46, 346920), 'requests': 14, 'successes': 13, 'failures': 1, '429s': 1}, {'key_suffix': 'DJvI', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 27, 2, 501547), 'requests': 13, 'successes': 12, 'failures': 1, '429s': 1}, {'key_suffix': '7gBP', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 27, 20, 228232), 'requests': 12, 'successes': 11, 'failures': 1, '429s': 1}]}
Using key #1: ****Fxew
Progress: 10/20 (50.0%) | QPS: 1.11 | ETA: 9s | Elapsed: 9sUsing key #1: ****Fxew
Using key #1: ****Fxew
Using key #1: ****Fxew
Using key #1: ****Fxew
Using key #1: ****Fxew
Progress: 14/20 (70.0%) | QPS: 1.39 | ETA: 4s | Elapsed: 10sUsing key #1: ****Fxew
Using key #1: ****Fxew
Using key #1: ****Fxew
Using key #1: ****Fxew
Progress: 20/20 (100.0%) | QPS: 1.66 | ETA: 0s | Elapsed: 12s
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 0sUsing key #1: ****Fxew
Using key #1: ****Fxew
Using key #1: ****Fxew
Using key #1: ****Fxew
Using key #1: ****Fxew
Using key #1: ****Fxew
Progress: 4/20 (20.0%) | QPS: 1.33 | ETA: 12s | Elapsed: 3sUsing key #1: ****Fxew
Progress: 5/20 (25.0%) | QPS: 0.83 | ETA: 18s | Elapsed: 6sUsing key #1: ****Fxew
Progress: 6/20 (30.0%) | QPS: 0.85 | ETA: 16s | Elapsed: 7s================================================================================
429 on ****Fxew
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyay0bp1em1bnwtc93xw53kw` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11423, Requested 1092. Please try again in 2.574999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sun, 26 Jul 2026 04:57:47 GMT
  content-type: application/json
  content-length: 390
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 3
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 980
  x-ratelimit-remaining-tokens: 577
  x-ratelimit-reset-requests: 28m48s
  x-ratelimit-reset-tokens: 57.114s
  x-request-id: req_01kyecjms8e48rjeppknyrsc6r
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a210d357fd0aba26-HYD
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyay0bp1em1bnwtc93xw53kw` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11423, Requested 1092. Please try again in 2.574999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 3
{'provider': 'groq', 'current_index': 1, 'keys': [{'key_suffix': 'Yzkz', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 27, 40, 233828), 'requests': 24, 'successes': 22, 'failures': 2, '429s': 2}, {'key_suffix': 'Fxew', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 27, 50, 537731), 'requests': 24, 'successes': 21, 'failures': 2, '429s': 2}, {'key_suffix': 'yNwZ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 26, 40, 435498), 'requests': 8, 'successes': 7, 'failures': 1, '429s': 1}, {'key_suffix': 'isl2', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 26, 46, 346920), 'requests': 14, 'successes': 13, 'failures': 1, '429s': 1}, {'key_suffix': 'DJvI', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 27, 2, 501547), 'requests': 13, 'successes': 12, 'failures': 1, '429s': 1}, {'key_suffix': '7gBP', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 27, 20, 228232), 'requests': 12, 'successes': 11, 'failures': 1, '429s': 1}]}
Using key #2: ****yNwZ
Progress: 6/20 (30.0%) | QPS: 0.75 | ETA: 19s | Elapsed: 8sUsing key #2: ****yNwZ
Using key #2: ****yNwZ
Progress: 8/20 (40.0%) | QPS: 0.88 | ETA: 14s | Elapsed: 9sUsing key #2: ****yNwZ
Using key #2: ****yNwZ
Using key #2: ****yNwZ
Using key #2: ****yNwZ
Using key #2: ****yNwZ
Progress: 13/20 (65.0%) | QPS: 1.29 | ETA: 5s | Elapsed: 10sUsing key #2: ****yNwZ
Using key #2: ****yNwZ
Using key #2: ****yNwZ
Using key #2: ****yNwZ
Using key #2: ****yNwZ
Progress: 20/20 (100.0%) | QPS: 1.66 | ETA: 0s | Elapsed: 12s
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 0sUsing key #2: ****yNwZ
Using key #2: ****yNwZ
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 5sUsing key #2: ****yNwZ
Progress: 1/20 (5.0%) | QPS: 0.10 | ETA: 3.2m | Elapsed: 10sUsing key #2: ****yNwZ
Progress: 2/20 (10.0%) | QPS: 0.18 | ETA: 1.7m | Elapsed: 11s================================================================================
429 on ****yNwZ
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyayk6txfny8n7ahf9xc9x96` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11480, Requested 1543. Please try again in 5.115s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sun, 26 Jul 2026 04:58:03 GMT
  content-type: application/json
  content-length: 384
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 6
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 979
  x-ratelimit-remaining-tokens: 520
  x-ratelimit-reset-requests: 30m14.4s
  x-ratelimit-reset-tokens: 57.4s
  x-request-id: req_01kyeck423ej394gw0q7f62c02
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a210d3b9bbd1ba26-HYD
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyayk6txfny8n7ahf9xc9x96` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11480, Requested 1543. Please try again in 5.115s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 6
{'provider': 'groq', 'current_index': 2, 'keys': [{'key_suffix': 'Yzkz', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 27, 40, 233828), 'requests': 24, 'successes': 22, 'failures': 2, '429s': 2}, {'key_suffix': 'Fxew', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 27, 50, 537731), 'requests': 24, 'successes': 22, 'failures': 2, '429s': 2}, {'key_suffix': 'yNwZ', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 28, 9, 183215), 'requests': 25, 'successes': 22, 'failures': 2, '429s': 2}, {'key_suffix': 'isl2', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 26, 46, 346920), 'requests': 14, 'successes': 13, 'failures': 1, '429s': 1}, {'key_suffix': 'DJvI', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 27, 2, 501547), 'requests': 13, 'successes': 12, 'failures': 1, '429s': 1}, {'key_suffix': '7gBP', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 27, 20, 228232), 'requests': 12, 'successes': 11, 'failures': 1, '429s': 1}]}
Using key #3: ****isl2
Using key #3: ****isl2
Progress: 3/20 (15.0%) | QPS: 0.25 | ETA: 1.1m | Elapsed: 12sUsing key #3: ****isl2
Using key #3: ****isl2
Progress: 5/20 (25.0%) | QPS: 0.38 | ETA: 39s | Elapsed: 13sUsing key #3: ****isl2
Using key #3: ****isl2
Using key #3: ****isl2
Progress: 8/20 (40.0%) | QPS: 0.57 | ETA: 21s | Elapsed: 14sUsing key #3: ****isl2
Using key #3: ****isl2
Progress: 10/20 (50.0%) | QPS: 0.62 | ETA: 16s | Elapsed: 16sUsing key #3: ****isl2
Progress: 12/20 (60.0%) | QPS: 0.60 | ETA: 13s | Elapsed: 20sUsing key #3: ****isl2
Progress: 12/20 (60.0%) | QPS: 0.44 | ETA: 18s | Elapsed: 27s================================================================================
429 on ****isl2
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyayrpkneawrsb0tg3sgy3r7` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11643, Requested 1526. Please try again in 5.845s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sun, 26 Jul 2026 04:58:19 GMT
  content-type: application/json
  content-length: 384
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 6
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 977
  x-ratelimit-remaining-tokens: 357
  x-ratelimit-reset-requests: 33m7.2s
  x-ratelimit-reset-tokens: 58.215s
  x-request-id: req_01kyeckmd1ejetcfexjjr6vkw7
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a210d4223b68162a-HYD
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyayrpkneawrsb0tg3sgy3r7` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11643, Requested 1526. Please try again in 5.845s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 6
{'provider': 'groq', 'current_index': 3, 'keys': [{'key_suffix': 'Yzkz', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 27, 40, 233828), 'requests': 24, 'successes': 22, 'failures': 2, '429s': 2}, {'key_suffix': 'Fxew', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 27, 50, 537731), 'requests': 24, 'successes': 22, 'failures': 2, '429s': 2}, {'key_suffix': 'yNwZ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 28, 9, 183215), 'requests': 25, 'successes': 23, 'failures': 2, '429s': 2}, {'key_suffix': 'isl2', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 28, 25, 915710), 'requests': 25, 'successes': 23, 'failures': 2, '429s': 2}, {'key_suffix': 'DJvI', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 27, 2, 501547), 'requests': 13, 'successes': 12, 'failures': 1, '429s': 1}, {'key_suffix': '7gBP', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 27, 20, 228232), 'requests': 12, 'successes': 11, 'failures': 1, '429s': 1}]}
Using key #4: ****DJvI
Using key #4: ****DJvI
Progress: 13/20 (65.0%) | QPS: 0.46 | ETA: 15s | Elapsed: 28sUsing key #4: ****DJvI
Using key #4: ****DJvI
Using key #4: ****DJvI
Using key #4: ****DJvI
Using key #4: ****DJvI
Progress: 20/20 (100.0%) | QPS: 0.66 | ETA: 0s | Elapsed: 30s
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 1sUsing key #4: ****DJvI
Using key #4: ****DJvI
Progress: 2/20 (10.0%) | QPS: 0.99 | ETA: 18s | Elapsed: 2sUsing key #4: ****DJvI
Using key #4: ****DJvI
Progress: 3/20 (15.0%) | QPS: 1.00 | ETA: 17s | Elapsed: 3sUsing key #4: ****DJvI
Progress: 4/20 (20.0%) | QPS: 0.80 | ETA: 20s | Elapsed: 5sUsing key #4: ****DJvI
Progress: 4/20 (20.0%) | QPS: 0.44 | ETA: 36s | Elapsed: 9s================================================================================
429 on ****DJvI
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyayyr8gf2abv4dvzasffv7j` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11755, Requested 1141. Please try again in 4.48s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sun, 26 Jul 2026 04:58:32 GMT
  content-type: application/json
  content-length: 383
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 5
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 976
  x-ratelimit-remaining-tokens: 245
  x-ratelimit-reset-requests: 34m33.6s
  x-ratelimit-reset-tokens: 58.775s
  x-request-id: req_01kyecm06kemb8s5db0cdwxn70
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a210d46ddd970fac-HYD
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyayyr8gf2abv4dvzasffv7j` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11755, Requested 1141. Please try again in 4.48s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 5
{'provider': 'groq', 'current_index': 4, 'keys': [{'key_suffix': 'Yzkz', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 27, 40, 233828), 'requests': 24, 'successes': 22, 'failures': 2, '429s': 2}, {'key_suffix': 'Fxew', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 27, 50, 537731), 'requests': 24, 'successes': 22, 'failures': 2, '429s': 2}, {'key_suffix': 'yNwZ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 28, 9, 183215), 'requests': 25, 'successes': 23, 'failures': 2, '429s': 2}, {'key_suffix': 'isl2', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 28, 25, 915710), 'requests': 25, 'successes': 23, 'failures': 2, '429s': 2}, {'key_suffix': 'DJvI', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 28, 36, 997078), 'requests': 26, 'successes': 24, 'failures': 2, '429s': 2}, {'key_suffix': '7gBP', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 27, 20, 228232), 'requests': 12, 'successes': 11, 'failures': 1, '429s': 1}]}
Using key #5: ****7gBP
Progress: 5/20 (25.0%) | QPS: 0.50 | ETA: 30s | Elapsed: 10sUsing key #5: ****7gBP
Progress: 6/20 (30.0%) | QPS: 0.54 | ETA: 26s | Elapsed: 11sUsing key #5: ****7gBP
Using key #5: ****7gBP
Progress: 8/20 (40.0%) | QPS: 0.66 | ETA: 18s | Elapsed: 12sUsing key #5: ****7gBP
Progress: 9/20 (45.0%) | QPS: 0.69 | ETA: 16s | Elapsed: 13sUsing key #5: ****7gBP
Using key #5: ****7gBP
Progress: 11/20 (55.0%) | QPS: 0.78 | ETA: 12s | Elapsed: 14sUsing key #5: ****7gBP
Using key #5: ****7gBP
Progress: 13/20 (65.0%) | QPS: 0.86 | ETA: 8s | Elapsed: 15sUsing key #5: ****7gBP
Progress: 15/20 (75.0%) | QPS: 0.93 | ETA: 5s | Elapsed: 16sUsing key #5: ****7gBP
Using key #5: ****7gBP
Progress: 16/20 (80.0%) | QPS: 0.94 | ETA: 4s | Elapsed: 17sUsing key #5: ****7gBP
Progress: 18/20 (90.0%) | QPS: 1.00 | ETA: 2s | Elapsed: 18sUsing key #5: ****7gBP
Using key #5: ****7gBP
Progress: 20/20 (100.0%) | QPS: 1.00 | ETA: 0s | Elapsed: 20s
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 0sUsing key #5: ****7gBPUsing key #5: ****7gBP

Progress: 1/20 (5.0%) | QPS: 0.50 | ETA: 38s | Elapsed: 2s: 1sUsing key #5: ****7gBP
Progress: 1/20 (5.0%) | QPS: 0.17 | ETA: 1.9m | Elapsed: 6s================================================================================
429 on ****7gBP
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyaz4w9sf2n85wmxftrm7c8d` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11821, Requested 1120. Please try again in 4.705s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sun, 26 Jul 2026 04:58:49 GMT
  content-type: application/json
  content-length: 384
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 5
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 972
  x-ratelimit-remaining-tokens: 179
  x-ratelimit-reset-requests: 40m19.2s
  x-ratelimit-reset-tokens: 59.105s
  x-request-id: req_01kyecmgxqe9avv7s8avv6zj99
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a210d4d8cf5f7e55-HYD
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyaz4w9sf2n85wmxftrm7c8d` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11821, Requested 1120. Please try again in 4.705s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 5

## 7b. Evaluate Existing JSONL Files

Run offline evaluation on already-generated JSONL files.
Uses experiment-level evaluation config — all configs are scored with the same judge model.

- `parallel_runs=True` — evaluate multiple configs simultaneously
- `parallel_config_run=True` — evaluate records within each config in parallel

In [9]:
# Discover all configs and build run dicts from existing JSONL files
configs = runner.load_configs()
runs = []
for cfg in configs:
    jsonl_path = experiment_config.temp_dir / f"{cfg.name}.jsonl"
    if jsonl_path.exists():
        runs.append({"config_name": cfg.name, "config": cfg, "jsonl_path": jsonl_path})
    else:
        print(f"  Skipping {cfg.name} — no JSONL found")

print(f"Found {len(runs)} configs with JSONL files")

# Evaluate all configs: parallel across configs + parallel within each config
eval_runs = runner.evaluate_runs(
    runs,
    parallel_runs=True,
    parallel_config_run=True,
)

# Use eval_runs for report generation downstream
runs = eval_runs
print(f"\n✅ Evaluation complete: {len(eval_runs)} configs")

Found 9 configs with JSONL files
Using key #2: ****yNwZ
Using key #2: ****yNwZ
Using key #2: ****yNwZ
Using key #2: ****yNwZ
================================================================================
429 on ****yNwZ
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyayk6txfny8n7ahf9xc9x96` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11793, Requested 5902. Please try again in 28.475s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sun, 26 Jul 2026 05:00:14 GMT
  content-type: application/json
  content-length: 385
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 29
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 962
  x-ratelimit-remaining-tokens: 207
  x-ratelimit-reset-requests: 54m43.2s
  x-ratelimit-reset-tokens: 58.965s
  x-request-id: req_01kyecq41bew6axbjnkve1f018
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a210d6ecc9ccfbde-HYD
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyayk6txfny8n7ahf9xc9x96` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11793, Requested 5902. Please try again in 28.475s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 29
{'provider': 'groq', 'current_index': 2, 'keys': [{'key_suffix': 'Yzkz', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 29, 4, 112184), 'requests': 41, 'successes': 38, 'failures': 3, '429s': 3}, {'key_suffix': 'Fxew', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 29, 34, 212502), 'requests': 53, 'successes': 50, 'failures': 3, '429s': 3}, {'key_suffix': 'yNwZ', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 30, 43, 230780), 'requests': 43, 'successes': 39, 'failures': 3, '429s': 3}, {'key_suffix': 'isl2', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 28, 25, 915710), 'requests': 25, 'successes': 23, 'failures': 2, '429s': 2}, {'key_suffix': 'DJvI', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 28, 36, 997078), 'requests': 26, 'successes': 24, 'failures': 2, '429s': 2}, {'key_suffix': '7gBP', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 28, 54, 126765), 'requests': 30, 'successes': 28, 'failures': 2, '429s': 2}]}
Using key #3: ****isl2
Using key #3: ****isl2
Using key #3: ****isl2
Using key #3: ****isl2
Using key #3: ****isl2
Using key #3: ****isl2
================================================================================
429 on ****isl2
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyayrpkneawrsb0tg3sgy3r7` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 10979, Requested 5471. Please try again in 22.25s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sun, 26 Jul 2026 05:01:05 GMT
  content-type: application/json
  content-length: 384
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 23
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 974
  x-ratelimit-remaining-tokens: 1021
  x-ratelimit-reset-requests: 37m26.4s
  x-ratelimit-reset-tokens: 54.895s
  x-request-id: req_01kyecrnvsf0za6yzdq5jm5fxz
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a210d82b9fd5a46b-HYD
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyayrpkneawrsb0tg3sgy3r7` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 10979, Requested 5471. Please try again in 22.25s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 23
{'provider': 'groq', 'current_index': 3, 'keys': [{'key_suffix': 'Yzkz', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 29, 4, 112184), 'requests': 41, 'successes': 38, 'failures': 3, '429s': 3}, {'key_suffix': 'Fxew', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 29, 34, 212502), 'requests': 53, 'successes': 50, 'failures': 3, '429s': 3}, {'key_suffix': 'yNwZ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 30, 43, 230780), 'requests': 43, 'successes': 40, 'failures': 3, '429s': 3}, {'key_suffix': 'isl2', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 31, 28, 310497), 'requests': 31, 'successes': 27, 'failures': 3, '429s': 3}, {'key_suffix': 'DJvI', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 28, 36, 997078), 'requests': 26, 'successes': 24, 'failures': 2, '429s': 2}, {'key_suffix': '7gBP', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 28, 54, 126765), 'requests': 30, 'successes': 28, 'failures': 2, '429s': 2}]}
Using key #4: ****DJvI
Using key #4: ****DJvI
Using key #4: ****DJvI
Using key #4: ****DJvI
Using key #4: ****DJvI
Using key #4: ****DJvI
Using key #4: ****DJvI
================================================================================
429 on ****DJvI
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyayyr8gf2abv4dvzasffv7j` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 10893, Requested 6877. Please try again in 28.85s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sun, 26 Jul 2026 05:02:24 GMT
  content-type: application/json
  content-length: 384
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 29
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 972
  x-ratelimit-remaining-tokens: 1107
  x-ratelimit-reset-requests: 40m19.2s
  x-ratelimit-reset-tokens: 54.465s
  x-request-id: req_01kyecv3h2ezks650q77392qzw
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a210da1cad4ec508-HYD
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyayyr8gf2abv4dvzasffv7j` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 10893, Requested 6877. Please try again in 28.85s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 29
{'provider': 'groq', 'current_index': 4, 'keys': [{'key_suffix': 'Yzkz', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 29, 4, 112184), 'requests': 41, 'successes': 38, 'failures': 3, '429s': 3}, {'key_suffix': 'Fxew', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 29, 34, 212502), 'requests': 53, 'successes': 50, 'failures': 3, '429s': 3}, {'key_suffix': 'yNwZ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 30, 43, 230780), 'requests': 43, 'successes': 40, 'failures': 3, '429s': 3}, {'key_suffix': 'isl2', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 31, 28, 310497), 'requests': 31, 'successes': 28, 'failures': 3, '429s': 3}, {'key_suffix': 'DJvI', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 32, 53, 784265), 'requests': 33, 'successes': 29, 'failures': 3, '429s': 3}, {'key_suffix': '7gBP', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 28, 54, 126765), 'requests': 30, 'successes': 28, 'failures': 2, '429s': 2}]}
Using key #5: ****7gBP
Using key #5: ****7gBP
Using key #5: ****7gBP
Using key #5: ****7gBP
Using key #5: ****7gBP
Using key #5: ****7gBP
================================================================================
429 on ****7gBP
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyaz4w9sf2n85wmxftrm7c8d` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11450, Requested 5755. Please try again in 26.025s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sun, 26 Jul 2026 05:03:38 GMT
  content-type: application/json
  content-length: 385
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 27
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 969
  x-ratelimit-remaining-tokens: 550
  x-ratelimit-reset-requests: 44m38.4s
  x-ratelimit-reset-tokens: 57.25s
  x-request-id: req_01kyecxbpzff1rcn1qh98byk1c
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a210dbea7deac230-HYD
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyaz4w9sf2n85wmxftrm7c8d` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 11450, Requested 5755. Please try again in 26.025s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 27
{'provider': 'groq', 'current_index': 5, 'keys': [{'key_suffix': 'Yzkz', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 29, 4, 112184), 'requests': 41, 'successes': 38, 'failures': 3, '429s': 3}, {'key_suffix': 'Fxew', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 29, 34, 212502), 'requests': 53, 'successes': 50, 'failures': 3, '429s': 3}, {'key_suffix': 'yNwZ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 30, 43, 230780), 'requests': 43, 'successes': 40, 'failures': 3, '429s': 3}, {'key_suffix': 'isl2', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 31, 28, 310497), 'requests': 31, 'successes': 28, 'failures': 3, '429s': 3}, {'key_suffix': 'DJvI', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 32, 53, 784265), 'requests': 33, 'successes': 30, 'failures': 3, '429s': 3}, {'key_suffix': '7gBP', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 34, 5, 700338), 'requests': 36, 'successes': 32, 'failures': 3, '429s': 3}]}
Using key #0: ****Yzkz
[emanual_v11_role_aware_bgem3] Evaluation complete → rag-experiments/emanual-experiment/temp/emanual_v11_role_aware_bgem3.jsonl
Using key #0: ****Yzkz
Using key #0: ****Yzkz
Using key #0: ****Yzkz
Using key #0: ****Yzkz
Using key #0: ****Yzkz
Using key #0: ****Yzkz
Using key #0: ****Yzkz
Using key #0: ****Yzkz
================================================================================
429 on ****Yzkz
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq21xc5dec58dfyhejka65td` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 10645, Requested 1936. Please try again in 2.905s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sun, 26 Jul 2026 05:04:00 GMT
  content-type: application/json
  content-length: 384
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 3
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 959
  x-ratelimit-remaining-tokens: 1355
  x-ratelimit-reset-requests: 59m2.4s
  x-ratelimit-reset-tokens: 53.225s
  x-request-id: req_01kyecy14ef8ethgrmfrd35tc8
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a210dc73bad6c230-HYD
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kq21xc5dec58dfyhejka65td` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 10645, Requested 1936. Please try again in 2.905s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 3
{'provider': 'groq', 'current_index': 0, 'keys': [{'key_suffix': 'Yzkz', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 34, 3, 634062), 'requests': 50, 'successes': 45, 'failures': 4, '429s': 4}, {'key_suffix': 'Fxew', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 29, 34, 212502), 'requests': 53, 'successes': 50, 'failures': 3, '429s': 3}, {'key_suffix': 'yNwZ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 30, 43, 230780), 'requests': 43, 'successes': 40, 'failures': 3, '429s': 3}, {'key_suffix': 'isl2', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 31, 28, 310497), 'requests': 31, 'successes': 28, 'failures': 3, '429s': 3}, {'key_suffix': 'DJvI', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 32, 53, 784265), 'requests': 33, 'successes': 30, 'failures': 3, '429s': 3}, {'key_suffix': '7gBP', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 34, 5, 700338), 'requests': 36, 'successes': 33, 'failures': 3, '429s': 3}]}
Using key #1: ****Fxew
Using key #1: ****Fxew
Using key #1: ****Fxew
Using key #1: ****Fxew
Using key #1: ****Fxew
Using key #1: ****Fxew
Using key #1: ****Fxew
Using key #1: ****Fxew
Using key #1: ****Fxew
Using key #1: ****Fxew
Using key #1: ****Fxew
================================================================================
429 on ****Fxew
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyay0bp1em1bnwtc93xw53kw` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 10738, Requested 1610. Please try again in 1.74s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sun, 26 Jul 2026 05:04:22 GMT
  content-type: application/json
  content-length: 383
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 2
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 945
  x-ratelimit-remaining-tokens: 1262
  x-ratelimit-reset-requests: 1h19m12s
  x-ratelimit-reset-tokens: 53.69s
  x-request-id: req_01kyecyp3jfajbm2g3f21w6sqd
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a210dcf9ed607c70-HYD
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyay0bp1em1bnwtc93xw53kw` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 10738, Requested 1610. Please try again in 1.74s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 2
{'provider': 'groq', 'current_index': 1, 'keys': [{'key_suffix': 'Yzkz', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 34, 3, 634062), 'requests': 50, 'successes': 46, 'failures': 4, '429s': 4}, {'key_suffix': 'Fxew', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 34, 24, 112062), 'requests': 64, 'successes': 59, 'failures': 4, '429s': 4}, {'key_suffix': 'yNwZ', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 30, 43, 230780), 'requests': 43, 'successes': 40, 'failures': 3, '429s': 3}, {'key_suffix': 'isl2', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 31, 28, 310497), 'requests': 31, 'successes': 28, 'failures': 3, '429s': 3}, {'key_suffix': 'DJvI', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 32, 53, 784265), 'requests': 33, 'successes': 30, 'failures': 3, '429s': 3}, {'key_suffix': '7gBP', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 34, 5, 700338), 'requests': 36, 'successes': 33, 'failures': 3, '429s': 3}]}
Using key #2: ****yNwZ
Using key #2: ****yNwZ
Using key #2: ****yNwZ
[emanual_v1_baseline] Evaluation complete → rag-experiments/emanual-experiment/temp/emanual_v1_baseline.jsonl
Using key #2: ****yNwZ
Using key #2: ****yNwZ
Using key #2: ****yNwZ
Using key #2: ****yNwZ
Using key #2: ****yNwZ
Using key #2: ****yNwZ
================================================================================
429 on ****yNwZ
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyayk6txfny8n7ahf9xc9x96` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 9944, Requested 2343. Please try again in 1.435s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sun, 26 Jul 2026 05:04:43 GMT
  content-type: application/json
  content-length: 383
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 2
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 956
  x-ratelimit-remaining-tokens: 2056
  x-ratelimit-reset-requests: 1h3m21.6s
  x-ratelimit-reset-tokens: 49.72s
  x-request-id: req_01kyeczahpfqv8sexp3dtk8c4w
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a210dd7cddff7e55-HYD
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyayk6txfny8n7ahf9xc9x96` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 9944, Requested 2343. Please try again in 1.435s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 2

Record 6 evaluation failed: All Groq API keys are currently rate limited.
Record 12 evaluation failed: All Groq API keys are currently rate limited.
Record 13 evaluation failed: All Groq API keys are currently rate limited.
Record 14 evaluation failed: All Groq API keys are currently rate limited.
Record 15 evaluation failed: All Groq API keys are currently rate limited.
Record 16 evaluation failed: All Groq API keys are currently rate limited.
Record 17 evaluation failed: All Groq API keys are currently rate limited.
Record 18 evaluation failed: All Groq API keys are currently rate limited.
Record 19 evaluation failed: All Groq API keys are currently rate limited.
Record 20 evaluation failed: All Groq API keys are currently rate limited.

================================================================================
429 on ****7gBP
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyaz4w9sf2n85wmxftrm7c8d` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 10494, Requested 1758. Please try again in 1.26s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sun, 26 Jul 2026 05:08:26 GMT
  content-type: application/json
  content-length: 383
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 2
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 952
  x-ratelimit-remaining-tokens: 1506
  x-ratelimit-reset-requests: 1h9m7.2s
  x-ratelimit-reset-tokens: 52.47s
  x-request-id: req_01kyed64hre5mb9cx7sez3y4pr
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a210e2ef7c5349d5-HYD
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyaz4w9sf2n85wmxftrm7c8d` service tier `on_demand` on tokens per minute (TPM): Limit 12000, Used 10494, Requested 1758. Please try again in 1.26s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 2
{'provider': 'groq', 'current_index': 5, 'keys': [{'key_suffix': 'Yzkz', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 11, 9, 14, 48180), 'requests': 63, 'successes': 57, 'failures': 6, '429s': 6}, {'key_suffix': 'Fxew', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 56, 4, 912506), 'requests': 86, 'successes': 79, 'failures': 7, '429s': 7}, {'key_suffix': 'yNwZ', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 48, 51, 110264), 'requests': 63, 'successes': 57, 'failures': 6, '429s': 6}, {'key_suffix': 'isl2', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 50, 42, 230393), 'requests': 43, 'successes': 38, 'failures': 5, '429s': 5}, {'key_suffix': 'DJvI', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 11, 12, 3, 628705), 'requests': 51, 'successes': 46, 'failures': 5, '429s': 5}, {'key_suffix': '7gBP', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 38, 28, 256093), 'requests': 59, 'successes': 52, 'failures': 6, '429s': 6}]}
[emanual_v6_rerank_only] Evaluation complete → rag-experiments/emanual-experiment/temp/emanual_v6_rerank_only.jsonl
Using key #5: ****7gBP
Using key #5: ****7gBP
Using key #5: ****7gBP

Record 4 evaluation failed: All Groq API keys are currently rate limited.
Record 5 evaluation failed: All Groq API keys are currently rate limited.
Record 6 evaluation failed: All Groq API keys are currently rate limited.
Record 7 evaluation failed: All Groq API keys are currently rate limited.
Record 8 evaluation failed: All Groq API keys are currently rate limited.
Record 9 evaluation failed: All Groq API keys are currently rate limited.
Record 10 evaluation failed: All Groq API keys are currently rate limited.
Record 11 evaluation failed: All Groq API keys are currently rate limited.
Record 12 evaluation failed: All Groq API keys are currently rate limited.
Record 13 evaluation failed: All Groq API keys are currently rate limited.
Record 14 evaluation failed: All Groq API keys are currently rate limited.
Record 15 evaluation failed: All Groq API keys are currently rate limited.
Record 16 evaluation failed: All Groq API keys are currently rate limited.
Record 17 evaluation failed: All Groq API keys are currently rate limited.
Record 18 evaluation failed: All Groq API keys are currently rate limited.
Record 19 evaluation failed: All Groq API keys are currently rate limited.
Record 20 evaluation failed: All Groq API keys are currently rate limited.

Using key #5: ****7gBP
================================================================================
429 on ****7gBP
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyaz4w9sf2n85wmxftrm7c8d` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99079, Requested 2135. Please try again in 17m28.896s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sun, 26 Jul 2026 05:08:42 GMT
  content-type: application/json
  content-length: 386
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 1049
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 949
  x-ratelimit-remaining-tokens: 506
  x-ratelimit-reset-requests: 1h13m26.4s
  x-ratelimit-reset-tokens: 57.47s
  x-request-id: req_01kyed6mrgef0tm082h92x5w1x
  x-should-retry: false
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a210e357cd190fac-HYD
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyaz4w9sf2n85wmxftrm7c8d` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99079, Requested 2135. Please try again in 17m28.896s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 1049
{'provider': 'groq', 'current_index': 5, 'keys': [{'key_suffix': 'Yzkz', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 11, 9, 14, 48180), 'requests': 63, 'successes': 57, 'failures': 6, '429s': 6}, {'key_suffix': 'Fxew', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 56, 4, 912506), 'requests': 86, 'successes': 79, 'failures': 7, '429s': 7}, {'key_suffix': 'yNwZ', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 48, 51, 110264), 'requests': 63, 'successes': 57, 'failures': 6, '429s': 6}, {'key_suffix': 'isl2', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 50, 42, 230393), 'requests': 43, 'successes': 38, 'failures': 5, '429s': 5}, {'key_suffix': 'DJvI', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 11, 12, 3, 628705), 'requests': 51, 'successes': 46, 'failures': 5, '429s': 5}, {'key_suffix': '7gBP', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 56, 11, 856359), 'requests': 63, 'successes': 55, 'failures': 7, '429s': 7}]}

Record 3 evaluation failed: All Groq API keys are currently rate limited.
Record 1 evaluation failed: All Groq API keys are currently rate limited.
Record 2 evaluation failed: All Groq API keys are currently rate limited.
Record 3 evaluation failed: All Groq API keys are currently rate limited.
Record 4 evaluation failed: All Groq API keys are currently rate limited.
Record 5 evaluation failed: All Groq API keys are currently rate limited.
Record 6 evaluation failed: All Groq API keys are currently rate limited.
Record 7 evaluation failed: All Groq API keys are currently rate limited.
Record 8 evaluation failed: All Groq API keys are currently rate limited.
Record 9 evaluation failed: All Groq API keys are currently rate limited.
Record 10 evaluation failed: All Groq API keys are currently rate limited.
Record 11 evaluation failed: All Groq API keys are currently rate limited.
Record 13 evaluation failed: All Groq API keys are currently rate limited.
Record 12 evaluation failed: All Groq API keys are currently rate limited.
Record 15 evaluation failed: All Groq API keys are currently rate limited.
Record 14 evaluation failed: All Groq API keys are currently rate limited.
Record 16 evaluation failed: All Groq API keys are currently rate limited.
Record 17 evaluation failed: All Groq API keys are currently rate limited.
Record 18 evaluation failed: All Groq API keys are currently rate limited.
Record 19 evaluation failed: All Groq API keys are currently rate limited.
Record 20 evaluation failed: All Groq API keys are currently rate limited.

================================================================================
429 on ****7gBP
Error code: 429 - {'error': {'message': 'Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyaz4w9sf2n85wmxftrm7c8d` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99078, Requested 1843. Please try again in 13m15.743999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing', 'type': 'tokens', 'code': 'rate_limit_exceeded'}}
Status: 429

Headers:
  date: Sun, 26 Jul 2026 05:08:44 GMT
  content-type: application/json
  content-length: 392
  connection: keep-alive
  cache-control: private, max-age=0, no-store, no-cache, must-revalidate
  retry-after: 796
  server: cloudflare
  vary: Origin
  x-groq-region: bom
  x-ratelimit-limit-requests: 1000
  x-ratelimit-limit-tokens: 12000
  x-ratelimit-remaining-requests: 949
  x-ratelimit-remaining-tokens: 750
  x-ratelimit-reset-requests: 1h13m26.4s
  x-ratelimit-reset-tokens: 56.25s
  x-request-id: req_01kyed6nype1c80144ctgctytn
  x-should-retry: false
  via: 1.1 google
  cf-cache-status: DYNAMIC
  strict-transport-security: max-age=15552000
  cf-ray: a210e35f7b450fac-HYD
  alt-svc: h3=":443"; ma=86400

Body:
{"error":{"message":"Rate limit reached for model `llama-3.3-70b-versatile` in organization `org_01kyaz4w9sf2n85wmxftrm7c8d` service tier `on_demand` on tokens per day (TPD): Limit 100000, Used 99078, Requested 1843. Please try again in 13m15.743999999s. Need more tokens? Upgrade to Dev Tier today at https://console.groq.com/settings/billing","type":"tokens","code":"rate_limit_exceeded"}}

Retry after: 796
{'provider': 'groq', 'current_index': 5, 'keys': [{'key_suffix': 'Yzkz', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 11, 9, 14, 48180), 'requests': 63, 'successes': 57, 'failures': 6, '429s': 6}, {'key_suffix': 'Fxew', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 56, 4, 912506), 'requests': 86, 'successes': 79, 'failures': 7, '429s': 7}, {'key_suffix': 'yNwZ', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 48, 51, 110264), 'requests': 63, 'successes': 57, 'failures': 6, '429s': 6}, {'key_suffix': 'isl2', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 50, 42, 230393), 'requests': 43, 'successes': 38, 'failures': 5, '429s': 5}, {'key_suffix': 'DJvI', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 11, 12, 3, 628705), 'requests': 51, 'successes': 46, 'failures': 5, '429s': 5}, {'key_suffix': '7gBP', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 26, 10, 52, 0, 77821), 'requests': 63, 'successes': 55, 'failures': 8, '429s': 8}]}
[emanual_v7_hybrid_rerank] Evaluation complete → rag-experiments/emanual-experiment/temp/emanual_v7_hybrid_rerank.jsonl
[emanual_v8_hyde] Evaluation complete → rag-experiments/emanual-experiment/temp/emanual_v8_hyde.jsonl

✅ Evaluation complete: 9 configs

## 8. Generate Reports

Generate detailed reports for each configuration including:
- Per-query table with all TRACe scores
- Aggregate statistics (mean, std, MAE)
- Comparison with ground truth

In [10]:
# Generate reports
print("Generating reports...")
reports = runner.generate_reports(runs)

print(f"\n✅ Reports generated!")
print(f"  Saved to: {experiment_config.report_dir}")

Generating reports...

✅ Reports generated!
  Saved to: rag-experiments/emanual-experiment/reports

## 9. Display Reports

Display the generated reports with per-query and aggregate metrics.

In [11]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 80)

for report in reports:
    print(f"\n{'='*80}")
    print(f"Configuration: {report.config_name}")
    print(f"{'='*80}")
    
    # Display per-query results
    print("\nPer-Query Results:")
    display(report.display())

================================================================================
Configuration: emanual_v11_role_aware_bgem3
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `emanual_v11_role_aware_bgem3`

**name**: emanual_v11_role_aware_bgem3  •  **mode**: test  •  **providers**: {'groq': {'type': 'groq', 'api_key_env': 'GROQ_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'sentence', 'config': {'max_words': 380, 'overlap_sentences': 2}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'BAAI/bge-m3', 'dimension': 1024}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 1024}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 40}}, {'type': 'sparse', 'config': {'top_k': 40}}]}, 'query_transform': None, 'fusion': {'type': 'rrf', 'config': {'top_k': 40, 'k': 60}}, 'rerank': {'type': 'cross_encoder', 'config': {'model_name': 'BAAI/bge-reranker-v2-m3', 'top_k': 15}}}  •  **generation**: {'strategy': 'default', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 512, 'system_prompt': 'You are a consumer-electronics product-support assistant. Answer questions\nabout device features and settings using ONLY the provided user-manual passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use outside knowledge.\n2. Give exact, step-by-step instructions. Preserve menu paths, button names,\n   setting names, and on-screen labels verbatim\n   (e.g. "Settings > Support > Self Diagnosis > Signal Information").\n3. Be concise and procedural - give the steps, not background.\n4. If the passages do not contain the answer, respond with exactly:\n   "The passages do not provide sufficient information to answer this question."\n5. Every step must be directly supported by the passages provided.\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, give exact steps and menu paths):\n'}}  •  **evaluation**: {'type': 'trace', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 2000}}  •  **cache**: {'enabled': True, 'cache_dir': './cache'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,I want to enter into Ambient mode. How can I do that?,"[{'text': '', 'title': '', 'content': 'Using the Ambient Mode. Learn about t...","To enter Ambient Mode, press the button.",0.0190,0.0204,-0.0014,0.0095,0.0408,-0.0313,0.5000,1.0000,-0.5000,1.0,1.0,0.0
1,Where do I find signal information ?,"[{'text': '', 'title': '', 'content': 'Other Issues. Use these procedures to...","To find signal information, go to Settings > Support > Self Diagnosis > Sign...",0.0190,0.1111,-0.0921,0.0190,0.1111,-0.0921,1.0000,1.0000,0.0000,0.0,1.0,-1.0
2,How can I view the channels that are serached by auto program function and H...,"[{'text': '', 'title': '', 'content': 'Using the Channel List. Change the ch...",To view the channels that are searched by the auto program function:\n1. Pre...,0.1317,0.4211,-0.2894,0.0479,0.1579,-0.1100,0.3182,0.3750,-0.0568,0.0,1.0,-1.0
3,Can I configure Tint?,"[{'text': '', 'title': '', 'content': 'Configuring advanced picture settings...","To configure Tint, go to: \nSettings > Picture > Expert Settings > Tint (G/R...",0.0377,0.0323,0.0054,0.0126,0.0323,-0.0197,0.3333,1.0000,-0.6667,1.0,1.0,0.0
4,How do I fix the missing/wrong color issue ?,"[{'text': '', 'title': '', 'content': 'Testing the picture. Settings Support...","To fix the missing/wrong color issue, follow these steps:\n\n1. Run Start Pi...",0.0707,0.0893,-0.0186,0.0272,0.1786,-0.1514,0.3846,0.4000,-0.0154,0.0,1.0,-1.0
5,How do I fix blurring issues on TV screen?,"[{'text': '', 'title': '', 'content': 'Testing the picture. Settings Support...","To fix blurring issues on the TV screen, use the Auto Motion Plus Settings f...",0.0498,0.0357,0.0141,0.0050,0.0357,-0.0307,0.1000,1.0000,-0.9000,0.0,1.0,-1.0
6,What is the use of universal guide?,"[{'text': '', 'title': '', 'content': 'Using the Universal Guide App. Search...",The Universal Guide is an app that allows you to search for and enjoy variou...,0.0491,0.2778,-0.2287,0.0245,0.1667,-0.1422,0.5000,0.6000,-0.1000,0.0,1.0,-1.0
7,What is the feature of Bixby guide?,"[{'text': '', 'title': '', 'content': 'Running Bixby. Press and hold the but...","To view the Bixby guide, press the Bixby button once. When you press the but...",0.0252,0.1333,-0.1081,0.0189,0.1333,-0.1144,0.7500,1.0000,-0.2500,1.0,1.0,0.0
8,How to launch the last used app automatically?,"[{'text': '', 'title': '', 'content': 'Launching the last used app automatic...","To launch the last used app automatically, go to Settings > General > Smart ...",0.0184,0.0682,-0.0498,0.0092,0.0455,-0.0363,0.5000,0.6667,-0.1667,0.0,1.0,-1.0
9,Where do I find the list of my favorite channels?,"[{'text': '', 'title': '', 'content': 'Creating a Personal Favorites List. D...","To find the list of your favorite channels, follow these steps: \n\nPress th...",0.1111,0.4167,-0.3056,0.0850,0.3333,-0.2483,0.5294,0.8000,-0.2706,0.0,1.0,-1.0
10,I want to setup a beautiful screens. How can I do that?,"[{'text': '', 'title': '', 'content': 'Changing the content and settings for...","To set up beautiful screens, follow these steps: \n\n1. Press the button in ...",0.1350,0.0328,0.1022,0.0307,0.0492,-0.0185,0.2273,1.0000,-0.7727,1.0,1.0,0.0
11,How do I record using time Timeshift function?,"[{'text': '', 'title': '', 'content': 'Using the Instant and Schedule Record...","To record using the Timeshift function, follow these steps:\n\n1. Press the ...",0.0717,0.2000,-0.1283,0.0269,0.1000,-0.0731,0.3125,0.5000,-0.1875,0.0,1.0,-1.0
12,My IP auto setting failed. How to configure it?,"[{'text': '', 'title': '', 'content': 'Troubleshooting Internet connectivity...","To configure the IP settings, follow these steps: \n\n1. Go to Settings \n2....",0.0688,0.1154,-0.0466,0.0212,0.1538,-0.1326,0.2308,0.6667,-0.4359,0.0,1.0,-1.0
13,How can I connect my mobile device to the TV?,"[{'text': '', 'title': '', 'content': 'Connecting Your Mobile Device. Connec...","To connect your mobile device to the TV, follow these steps: \n1. Turn on th...",0.2681,0.3929,-0.1248,0.0797,0.3571,-0.2774,0.2973,0.9091,-0.6118,0.0,1.0,-1.0
14,How to configure Contrast and Sharpness?,"[{'text': '', 'title': '', 'content': 'Configuring advanced picture settings...","To configure Contrast and Sharpness, follow these steps: \nSettings > Pictur...",0.0556,0.0769,-0.0213,0.0247,0.0769,-0.0522,0.4444,1.0000,-0.5556,1.0,1.0,0.0
15,What are the steps to reset network?,"[{'text': '', 'title': '', 'content': 'Resetting Your Network. Settings Gene...",Settings > General > Network > Reset Network > Try Now > Restore the network...,0.0299,0.0370,-0.0071,0.0060,0.0370,-0.0310,0.2000,1.0000,-0.8000,1.0,0.0,1.0
16,How do I view a list of mobile devices registered to the TV?,"[{'text': '', 'title': '', 'content': 'Connecting Your Mobile Device. Connec...","To view a list of mobile devices registered to the TV, follow these steps: \...",0.0343,0.1111,-0.0768,0.0114,0.0741,-0.0627,0.3333,0.6667,-0.3334,0.0,1.0,-1.0
17,I get this error 'some files cannot be played'. How do I fix this?,"[{'text': '', 'title': '', 'content': 'My File Won't Play. When files don't ...",The passages do not provide sufficient information to answer this question.,0.0270,0.2105,-0.1835,0.0000,0.1579,-0.1579,0.0000,0.2500,-0.2500,0.0,0.0,0.0
18,How do I set scheduled viewing time?,"[{'text': '', 'title': '', 'content': 'Setting Up a Schedule Viewing. Config...","To set scheduled viewing time, follow these steps: \n\n1. Set the TV's clock...",0.1475,0.3500,-0.2025,0.0656,0.1500,-0.0844,0.4444,0.4286,0.0158,0.0,1.0,-1.0
19,Can I scan TV for malicious code ?,"[{'text': '', 'title': '', 'content': 'Scanning the TV and connected storage...","To scan the TV for malicious code, follow these steps: \nSettings > General ...",0.0376,0.7692,-0.7316,0.0376,0.5385,-0.5009,1.0000,0.7000,0.3000,1.0,1.0,0.0

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.0704,0.1951,0.0603,0.1870,0.1369
1,utilization_score,0.0281,0.1465,0.0235,0.1258,0.1184
2,completeness_score,0.4203,0.7481,0.2517,0.2503,0.3594
3,adherence_score,0.3500,0.9000,0.4770,0.3000,0.6500

None

================================================================================
Configuration: emanual_v1_baseline
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `emanual_v1_baseline`

**name**: emanual_v1_baseline  •  **mode**: test  •  **providers**: {'groq': {'type': 'groq', 'api_key_env': 'GROQ_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'fixed_word', 'config': {'max_words': 128, 'overlap_words': 20}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'sentence-transformers/all-MiniLM-L6-v2', 'dimension': 384}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 384}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 5}}]}, 'query_transform': None, 'fusion': None, 'rerank': None}  •  **generation**: {'strategy': 'default', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 512, 'system_prompt': 'You are a consumer-electronics product-support assistant. Answer questions\nabout device features and settings using ONLY the provided user-manual passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use outside knowledge.\n2. Give exact, step-by-step instructions. Preserve menu paths, button names,\n   setting names, and on-screen labels verbatim\n   (e.g. "Settings > Support > Self Diagnosis > Signal Information").\n3. Be concise and procedural - give the steps, not background.\n4. If the passages do not contain the answer, respond with exactly:\n   "The passages do not provide sufficient information to answer this question."\n5. Every step must be directly supported by the passages provided.\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, give exact steps and menu paths):\n'}}  •  **evaluation**: {'type': 'trace', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 2000}}  •  **cache**: {'enabled': True, 'cache_dir': './cache'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,I want to enter into Ambient mode. How can I do that?,"[{'text': '', 'title': '', 'content': 'beautiful screens, various visual inf...","To enter Ambient Mode, press the button. Alternatively, if the TV is turned ...",0.1290,0.0204,0.1086,0.0968,0.0408,0.0560,0.7500,1.0000,-0.2500,1.0,1.0,0.0
1,Where do I find signal information ?,"[{'text': '', 'title': '', 'content': 'Viewing Broadcast Information at a Gl...",Settings > Support > Self Diagnosis > Signal Information > Try Now,0.1176,0.1111,0.0065,0.0588,0.1111,-0.0523,0.5000,1.0000,-0.5000,1.0,1.0,0.0
2,How can I view the channels that are serached by auto program function and H...,"[{'text': '', 'title': '', 'content': 'Viewing and selecting channels on Fav...",To view the channels that are searched by the auto program function:\n1. Go ...,0.6333,0.4211,0.2122,0.3333,0.1579,0.1754,0.4737,0.3750,0.0987,0.0,1.0,-1.0
3,Can I configure Tint?,"[{'text': '', 'title': '', 'content': 'Setting the screen to black and white...",The passages do not provide sufficient information to answer this question.,0.2400,0.0323,0.2077,0.0000,0.0323,-0.0323,0.0000,1.0000,-1.0000,1.0,1.0,0.0
4,How do I fix the missing/wrong color issue ?,"[{'text': '', 'title': '', 'content': 'Inverting the screen color. Settings ...",The passages do not provide sufficient information to answer this question.,0.1818,0.0893,0.0925,0.0000,0.1786,-0.1786,0.0000,0.4000,-0.4000,1.0,1.0,0.0
5,How do I fix blurring issues on TV screen?,"[{'text': '', 'title': '', 'content': 'Setting the screen to black and white...","To fix blurring issues on the TV screen, try the following steps:\n\n1. Go t...",0.3448,0.0357,0.3091,0.3103,0.0357,0.2746,0.6000,1.0000,-0.4000,0.0,1.0,-1.0
6,What is the use of universal guide?,"[{'text': '', 'title': '', 'content': 'Accessibility Guidance. Provides a me...",The Universal Guide allows you to search for and enjoy various content such ...,0.2500,0.2778,-0.0278,0.2188,0.1667,0.0521,0.6250,0.6000,0.0250,0.0,1.0,-1.0
7,What is the feature of Bixby guide?,"[{'text': '', 'title': '', 'content': 'button, say a command, and then relea...","To view the Bixby guide, \n1. Press the button on your Samsung Smart Remote ...",0.4074,0.1333,0.2741,0.1111,0.1333,-0.0222,0.2727,1.0000,-0.7273,0.0,1.0,-1.0
8,How to launch the last used app automatically?,"[{'text': '', 'title': '', 'content': 'Launching the last used app automatic...","To launch the last used app automatically, follow these steps: \nSettings > ...",0.0811,0.0682,0.0129,0.0541,0.0455,0.0086,0.6667,0.6667,0.0000,1.0,1.0,0.0
9,Where do I find the list of my favorite channels?,"[{'text': '', 'title': '', 'content': 'Viewing and selecting channels on Fav...","To find the list of your favorite channels, follow these steps: \nPress the ...",0.6667,0.4167,0.2500,0.2857,0.3333,-0.0476,0.4286,0.8000,-0.3714,0.0,1.0,-1.0
10,I want to setup a beautiful screens. How can I do that?,"[{'text': '', 'title': '', 'content': 'the Ambient Mode browser will be prov...","To set up a beautiful screen, follow these steps: \nIn the Ambient Mode brow...",0.9000,0.0328,0.8672,0.0667,0.0492,0.0175,0.0741,1.0000,-0.9259,1.0,1.0,0.0
11,How do I record using time Timeshift function?,"[{'text': '', 'title': '', 'content': 'to Using the Recording and Timeshift'...","To record using the Timeshift function, follow these steps: \n1. Press the b...",0.7241,0.2000,0.5241,0.3448,0.1000,0.2448,0.4762,0.5000,-0.0238,0.0,1.0,-1.0
12,My IP auto setting failed. How to configure it?,"[{'text': '', 'title': '', 'content': 'turned on. If it is, turn it off and ...","To configure the IP settings, follow these steps: \nSettings > General > Net...",0.1429,0.1154,0.0275,0.2143,0.1538,0.0605,0.5000,0.6667,-0.1667,0.0,1.0,-1.0
13,How can I connect my mobile device to the TV?,"[{'text': '', 'title': '', 'content': 'Connecting Your Mobile Device. Connec...","To connect your mobile device to the TV, follow these steps: \n1. Turn on th...",0.4516,0.3929,0.0587,0.2903,0.3571,-0.0668,0.6429,0.9091,-0.2662,0.0,1.0,-1.0
14,How to configure Contrast and Sharpness?,"[{'text': '', 'title': '', 'content': 'Configuring advanced picture settings...","To configure Contrast and Sharpness, follow these steps: \nSettings > Pictur...",0.2105,0.0769,0.1336,0.0526,0.0769,-0.0243,0.2500,1.0000,-0.7500,1.0,1.0,0.0
15,What are the steps to reset network?,"[{'text': '', 'title': '', 'content': 'Resetting Your Network. Settings Gene...",Settings > General > Network > Reset Network > Try Now \n\n(This will) Resto...,0.2286,0.0370,0.1916,0.0286,0.0370,-0.0084,0.1250,1.0000,-0.8750,1.0,0.0,1.0
16,How do I view a list of mobile devices registered to the TV?,"[{'text': '', 'title': '', 'content': 'Managing Mobile Devices. Settings Gen...",Settings > General > External Device Manager > Device Connect Manager > Devi...,0.6000,0.1111,0.4889,0.0571,0.0741,-0.0170,0.0952,0.6667,-0.5715,1.0,1.0,0.0
17,I get this error 'some files cannot be played'. How do I fix this?,"[{'text': '', 'title': '', 'content': 'My File Won't Play. When files don't ...",The passages do not provide sufficient information to answer this question.,0.1538,0.2105,-0.0567,0.0000,0.1579,-0.1579,0.0000,0.2500,-0.2500,1.0,0.0,1.0
18,How do I set scheduled viewing time?,"[{'text': '', 'title': '', 'content': 'Setting Up a Schedule Viewing. Config...","To set a scheduled viewing time, follow these steps: \n1. Check the current ...",0.7368,0.3500,0.3868,0.6842,0.1500,0.5342,0.7143,0.4286,0.2857,0.0,1.0,-1.0
19,Can I scan TV for malicious code ?,"[{'text': '', 'title': '', 'content': 'Scanning the TV and connected storage...","To scan the TV for malicious code, follow these steps: \nSettings > General ...",0.3704,0.7692,-0.3988,0.1481,0.5385,-0.3904,0.4000,0.7000,-0.3000,1.0,1.0,0.0

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.3785,0.1951,0.2423,0.1870,0.2318
1,utilization_score,0.1678,0.1465,0.1662,0.1258,0.1211
2,completeness_score,0.3797,0.7481,0.2509,0.2503,0.4094
3,adherence_score,0.5500,0.9000,0.4975,0.3000,0.5500

None

================================================================================
Configuration: emanual_v2_hybrid_wsum
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `emanual_v2_hybrid_wsum`

**name**: emanual_v2_hybrid_wsum  •  **mode**: test  •  **providers**: {'groq': {'type': 'groq', 'api_key_env': 'GROQ_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'fixed_word', 'config': {'max_words': 128, 'overlap_words': 20}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'sentence-transformers/all-MiniLM-L6-v2', 'dimension': 384}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 384}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 20}}, {'type': 'sparse', 'config': {'top_k': 20}}]}, 'query_transform': None, 'fusion': {'type': 'weighted_sum', 'config': {'top_k': 10, 'weights': [0.5, 0.5]}}, 'rerank': None}  •  **generation**: {'strategy': 'default', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 512, 'system_prompt': 'You are a consumer-electronics product-support assistant. Answer questions\nabout device features and settings using ONLY the provided user-manual passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use outside knowledge.\n2. Give exact, step-by-step instructions. Preserve menu paths, button names,\n   setting names, and on-screen labels verbatim\n   (e.g. "Settings > Support > Self Diagnosis > Signal Information").\n3. Be concise and procedural - give the steps, not background.\n4. If the passages do not contain the answer, respond with exactly:\n   "The passages do not provide sufficient information to answer this question."\n5. Every step must be directly supported by the passages provided.\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, give exact steps and menu paths):\n'}}  •  **evaluation**: {'type': 'trace', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 2000}}  •  **cache**: {'enabled': True, 'cache_dir': './cache'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,I want to enter into Ambient mode. How can I do that?,"[{'text': '', 'title': '', 'content': 'beautiful screens, various visual inf...","To enter Ambient Mode, press the button. \n\nAlternatively, if the TV is tur...",0.1231,0.0204,0.1027,0.0769,0.0408,0.0361,0.6250,1.0000,-0.3750,1.0,1.0,0.0
1,Where do I find signal information ?,"[{'text': '', 'title': '', 'content': 'Checking digital channel signal info ...","To find signal information, go to: Settings > Support > Self Diagnosis > Sig...",0.0889,0.1111,-0.0222,0.0222,0.1111,-0.0889,0.2500,1.0000,-0.7500,1.0,1.0,0.0
2,How can I view the channels that are serached by auto program function and H...,"[{'text': '', 'title': '', 'content': 'Creating a Personal Favorites List. D...",To view the channels that are searched by the auto program function:\n1. Go ...,0.2807,0.4211,-0.1404,0.1228,0.1579,-0.0351,0.3125,0.3750,-0.0625,0.0,1.0,-1.0
3,Can I configure Tint?,"[{'text': '', 'title': '', 'content': 'Configuring advanced picture settings...","To configure Tint, follow these steps: \nSettings > Picture > Expert Setting...",0.0364,0.0323,0.0041,0.0182,0.0323,-0.0141,0.5000,1.0000,-0.5000,1.0,1.0,0.0
4,How do I fix the missing/wrong color issue ?,"[{'text': '', 'title': '', 'content': 'Inverting the screen color. Settings ...","To fix the missing/wrong color issue, follow these steps: \nSettings > Suppo...",0.3265,0.0893,0.2372,0.0816,0.1786,-0.0970,0.2500,0.4000,-0.1500,0.0,1.0,-1.0
5,How do I fix blurring issues on TV screen?,"[{'text': '', 'title': '', 'content': 'I Can't Hear the Sound Clearly. When ...","To fix blurring issues on the TV screen, follow these steps: \nSettings > Pi...",0.4600,0.0357,0.4243,0.1600,0.0357,0.1243,0.3478,1.0000,-0.6522,0.0,1.0,-1.0
6,What is the use of universal guide?,"[{'text': '', 'title': '', 'content': 'Using the Universal Guide App. Search...",The Universal Guide is an app that allows you to search for and enjoy variou...,0.1667,0.2778,-0.1111,0.1000,0.1667,-0.0667,0.6000,0.6000,0.0000,0.0,1.0,-1.0
7,What is the feature of Bixby guide?,"[{'text': '', 'title': '', 'content': 'button, say a command, and then relea...","To view the Bixby guide, \n1. Press the button once. \n2. The ""Using Bixby"" ...",0.1053,0.1333,-0.0280,0.0395,0.1333,-0.0938,0.3750,1.0000,-0.6250,0.0,1.0,-1.0
8,How to launch the last used app automatically?,"[{'text': '', 'title': '', 'content': 'Launching the last used app automatic...","To launch the last used app automatically, follow these steps: \nSettings > ...",0.0385,0.0682,-0.0297,0.0256,0.0455,-0.0199,0.6667,0.6667,0.0000,0.0,1.0,-1.0
9,Where do I find the list of my favorite channels?,"[{'text': '', 'title': '', 'content': 'Creating a Personal Favorites List. D...","To find the list of your favorite channels, follow these steps: \nPress the ...",0.2885,0.4167,-0.1282,0.1538,0.3333,-0.1795,0.3333,0.8000,-0.4667,0.0,1.0,-1.0
10,I want to setup a beautiful screens. How can I do that?,"[{'text': '', 'title': '', 'content': 'the Ambient Mode browser will be prov...","To setup a beautiful screen, follow these steps: \n\nIn the Ambient Mode bro...",0.1613,0.0328,0.1285,0.0484,0.0492,-0.0008,0.3000,1.0000,-0.7000,0.0,1.0,-1.0
11,How do I record using time Timeshift function?,"[{'text': '', 'title': '', 'content': 'Buttons and functions available while...","To record using the Timeshift function, follow these steps: \n\n1. Press the...",0.2083,0.2000,0.0083,0.0833,0.1000,-0.0167,0.2667,0.5000,-0.2333,0.0,1.0,-1.0
12,My IP auto setting failed. How to configure it?,"[{'text': '', 'title': '', 'content': 'turned on. If it is, turn it off and ...","To configure the IP settings, follow these steps: \n\n1. Go to ""Settings > G...",0.0896,0.1154,-0.0258,0.0896,0.1538,-0.0642,0.3333,0.6667,-0.3334,0.0,1.0,-1.0
13,How can I connect my mobile device to the TV?,"[{'text': '', 'title': '', 'content': 'Connecting Your Mobile Device. Connec...","To connect your mobile device to the TV, follow these steps: \n1. Turn on th...",0.2381,0.3929,-0.1548,0.1270,0.3571,-0.2301,0.5333,0.9091,-0.3758,0.0,1.0,-1.0
14,How to configure Contrast and Sharpness?,"[{'text': '', 'title': '', 'content': 'Configuring advanced picture settings...","To configure Contrast and Sharpness, follow these steps: \nSettings > Pictur...",0.0889,0.0769,0.0120,0.0222,0.0769,-0.0547,0.2500,1.0000,-0.7500,1.0,1.0,0.0
15,What are the steps to reset network?,"[{'text': '', 'title': '', 'content': 'I Want to Reset the TV. Initialize th...",Settings > General > Network > Reset Network > Try Now.,0.0556,0.0370,0.0186,0.0139,0.0370,-0.0231,0.2500,1.0000,-0.7500,1.0,0.0,1.0
16,How do I view a list of mobile devices registered to the TV?,"[{'text': '', 'title': '', 'content': 'Managing Mobile Devices. Settings Gen...",Settings > General > External Device Manager > Device Connect Manager > Devi...,0.1918,0.1111,0.0807,0.0137,0.0741,-0.0604,0.0714,0.6667,-0.5953,1.0,1.0,0.0
17,I get this error 'some files cannot be played'. How do I fix this?,"[{'text': '', 'title': '', 'content': 'My File Won't Play. When files don't ...",The passages do not provide sufficient information to answer this question.,0.1111,0.2105,-0.0994,0.0000,0.1579,-0.1579,0.0000,0.2500,-0.2500,1.0,0.0,1.0
18,How do I set scheduled viewing time?,"[{'text': '', 'title': '', 'content': 'Setting Up a Schedule Viewing. Config...","To set scheduled viewing time, follow these steps: \n1. Set the TV's clock (...",0.4630,0.3500,0.1130,0.1852,0.1500,0.0352,0.4000,0.4286,-0.0286,0.0,1.0,-1.0
19,Can I scan TV for malicious code ?,"[{'text': '', 'title': '', 'content': 'Scanning the TV and connected storage...","To scan the TV for malicious code, follow these steps: \nSettings > General ...",0.1250,0.7692,-0.6442,0.0625,0.5385,-0.4760,0.5000,0.7000,-0.2000,1.0,1.0,0.0

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.1824,0.1951,0.1233,0.1870,0.1257
1,utilization_score,0.0723,0.1465,0.0538,0.1258,0.0937
2,completeness_score,0.3582,0.7481,0.1689,0.2503,0.3899
3,adherence_score,0.4000,0.9000,0.4899,0.3000,0.7000

None

================================================================================
Configuration: emanual_v3_embed_bge
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `emanual_v3_embed_bge`

**name**: emanual_v3_embed_bge  •  **mode**: test  •  **providers**: {'groq': {'type': 'groq', 'api_key_env': 'GROQ_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'fixed_word', 'config': {'max_words': 128, 'overlap_words': 20}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'BAAI/bge-base-en-v1.5', 'dimension': 768}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 768}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 5}}]}, 'query_transform': None, 'fusion': None, 'rerank': None}  •  **generation**: {'strategy': 'default', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 512, 'system_prompt': 'You are a consumer-electronics product-support assistant. Answer questions\nabout device features and settings using ONLY the provided user-manual passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use outside knowledge.\n2. Give exact, step-by-step instructions. Preserve menu paths, button names,\n   setting names, and on-screen labels verbatim\n   (e.g. "Settings > Support > Self Diagnosis > Signal Information").\n3. Be concise and procedural - give the steps, not background.\n4. If the passages do not contain the answer, respond with exactly:\n   "The passages do not provide sufficient information to answer this question."\n5. Every step must be directly supported by the passages provided.\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, give exact steps and menu paths):\n'}}  •  **evaluation**: {'type': 'trace', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 2000}}  •  **cache**: {'enabled': True, 'cache_dir': './cache'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,I want to enter into Ambient mode. How can I do that?,"[{'text': '', 'title': '', 'content': 'beautiful screens, various visual inf...","To enter Ambient Mode, press the button.",0.1143,0.0204,0.0939,0.0571,0.0408,0.0163,0.5000,1.0000,-0.5000,1.0,1.0,0.0
1,Where do I find signal information ?,"[{'text': '', 'title': '', 'content': 'Checking digital channel signal info ...","To find signal information, go to: Settings > Support > Self Diagnosis > Sig...",0.0645,0.1111,-0.0466,0.0323,0.1111,-0.0788,0.5000,1.0000,-0.5000,1.0,1.0,0.0
2,How can I view the channels that are serached by auto program function and H...,"[{'text': '', 'title': '', 'content': 'Viewing and selecting channels on Fav...",To view the channels that are searched by the auto program function: \nPress...,0.7097,0.4211,0.2886,0.2258,0.1579,0.0679,0.3182,0.3750,-0.0568,0.0,1.0,-1.0
3,Can I configure Tint?,"[{'text': '', 'title': '', 'content': 'Configuring advanced picture settings...",Settings > Picture > Expert Settings > Try Now > Tint (G/R) > Try Now.,0.1053,0.0323,0.0730,0.0526,0.0323,0.0203,0.5000,1.0000,-0.5000,1.0,1.0,0.0
4,How do I fix the missing/wrong color issue ?,"[{'text': '', 'title': '', 'content': 'Solution Power Saving Mode Settings G...","To fix the missing/wrong color issue, follow these steps:\n1. Run ""Start Pic...",0.5625,0.0893,0.4732,0.2500,0.1786,0.0714,0.3333,0.4000,-0.0667,0.0,1.0,-1.0
5,How do I fix blurring issues on TV screen?,"[{'text': '', 'title': '', 'content': 'on your TV are correct but just a lit...","To fix blurring issues on the TV screen, follow these steps: \nSettings > Pi...",0.3182,0.0357,0.2825,0.2273,0.0357,0.1916,0.5714,1.0000,-0.4286,1.0,1.0,0.0
6,What is the use of universal guide?,"[{'text': '', 'title': '', 'content': 'Using the Universal Guide App. Search...",The Universal Guide is an app that allows you to search for and enjoy variou...,0.3077,0.2778,0.0299,0.1923,0.1667,0.0256,0.5000,0.6000,-0.1000,0.0,1.0,-1.0
7,What is the feature of Bixby guide?,"[{'text': '', 'title': '', 'content': 'Quick Guides. You can learn quickly h...","To view the Bixby guide, \n1. Press the button on your Samsung Smart Remote ...",0.2500,0.1333,0.1167,0.0938,0.1333,-0.0395,0.3750,1.0000,-0.6250,1.0,1.0,0.0
8,How to launch the last used app automatically?,"[{'text': '', 'title': '', 'content': 'Launching the last used app automatic...","To launch the last used app automatically, follow these steps: \nSettings > ...",0.0732,0.0682,0.0050,0.0488,0.0455,0.0033,0.6667,0.6667,0.0000,1.0,1.0,0.0
9,Where do I find the list of my favorite channels?,"[{'text': '', 'title': '', 'content': 'Viewing and selecting channels on Fav...","To find the list of your favorite channels, follow these steps: \nPress the ...",0.4074,0.4167,-0.0093,0.2593,0.3333,-0.0740,0.4545,0.8000,-0.3455,1.0,1.0,0.0
10,I want to setup a beautiful screens. How can I do that?,"[{'text': '', 'title': '', 'content': 'Configuring advanced picture settings...","To set up a beautiful screen, follow these steps: \nIn the Ambient Mode brow...",0.3333,0.0328,0.3005,0.1852,0.0492,0.1360,0.5556,1.0000,-0.4444,0.0,1.0,-1.0
11,How do I record using time Timeshift function?,"[{'text': '', 'title': '', 'content': 'to Using the Recording and Timeshift'...","To record using the Timeshift function, follow these steps: \n1. Press the b...",0.3448,0.2000,0.1448,0.1724,0.1000,0.0724,0.5000,0.5000,0.0000,0.0,1.0,-1.0
12,My IP auto setting failed. How to configure it?,"[{'text': '', 'title': '', 'content': 'turned on. If it is, turn it off and ...","To configure the IP settings, follow these steps: \nSettings > General > Net...",0.1071,0.1154,-0.0083,0.0714,0.1538,-0.0824,0.3333,0.6667,-0.3334,1.0,1.0,0.0
13,How can I connect my mobile device to the TV?,"[{'text': '', 'title': '', 'content': 'Connecting Your Mobile Device. Connec...","To connect your mobile device to the TV, follow these steps: \n1. Turn on th...",0.4474,0.3929,0.0545,0.2368,0.3571,-0.1203,0.5294,0.9091,-0.3797,0.0,1.0,-1.0
14,How to configure Contrast and Sharpness?,"[{'text': '', 'title': '', 'content': 'Configuring advanced picture settings...","To configure Contrast and Sharpness, follow these steps: \nSettings > Pictur...",0.1500,0.0769,0.0731,0.0500,0.0769,-0.0269,0.3333,1.0000,-0.6667,1.0,1.0,0.0
15,What are the steps to reset network?,"[{'text': '', 'title': '', 'content': 'Resetting Your Network. Settings Gene...",Settings > General > Network > Reset Network > Try Now \n\nThis will restore...,0.3636,0.0370,0.3266,0.0303,0.0370,-0.0067,0.0833,1.0000,-0.9167,1.0,0.0,1.0
16,How do I view a list of mobile devices registered to the TV?,"[{'text': '', 'title': '', 'content': 'Managing Mobile Devices. Settings Gen...",Settings > General > External Device Manager > Device Connect Manager > Devi...,0.0667,0.1111,-0.0444,0.0333,0.0741,-0.0408,0.5000,0.6667,-0.1667,1.0,1.0,0.0
17,I get this error 'some files cannot be played'. How do I fix this?,"[{'text': '', 'title': '', 'content': 'My File Won't Play. When files don't ...",The passages do not provide sufficient information to answer this question.,0.1562,0.2105,-0.0543,0.0000,0.1579,-0.1579,0.0000,0.2500,-0.2500,0.0,0.0,0.0
18,How do I set scheduled viewing time?,"[{'text': '', 'title': '', 'content': 'Setting Up a Schedule Viewing. Config...","To set a scheduled viewing time, follow these steps: \n1. Check the current ...",0.7273,0.3500,0.3773,0.5909,0.1500,0.4409,0.8125,0.4286,0.3839,0.0,1.0,-1.0
19,Can I scan TV for malicious code ?,"[{'text': '', 'title': '', 'content': 'Protecting the TV from Hacking and Ma...","To scan the TV for malicious code, follow these steps: \nSettings > General ...",0.4167,0.7692,-0.3525,0.1250,0.5385,-0.4135,0.3000,0.7000,-0.4000,1.0,1.0,0.0

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.3013,0.1951,0.1988,0.1870,0.1578
1,utilization_score,0.1467,0.1465,0.1326,0.1258,0.1043
2,completeness_score,0.4333,0.7481,0.1794,0.2503,0.3532
3,adherence_score,0.6000,0.9000,0.4899,0.3000,0.4000

None

================================================================================
Configuration: emanual_v4_chunk_sentence
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `emanual_v4_chunk_sentence`

**name**: emanual_v4_chunk_sentence  •  **mode**: test  •  **providers**: {'groq': {'type': 'groq', 'api_key_env': 'GROQ_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'sentence', 'config': {'max_words': 150, 'overlap_sentences': 1}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'sentence-transformers/all-MiniLM-L6-v2', 'dimension': 384}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 384}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 5}}]}, 'query_transform': None, 'fusion': None, 'rerank': None}  •  **generation**: {'strategy': 'default', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 512, 'system_prompt': 'You are a consumer-electronics product-support assistant. Answer questions\nabout device features and settings using ONLY the provided user-manual passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use outside knowledge.\n2. Give exact, step-by-step instructions. Preserve menu paths, button names,\n   setting names, and on-screen labels verbatim\n   (e.g. "Settings > Support > Self Diagnosis > Signal Information").\n3. Be concise and procedural - give the steps, not background.\n4. If the passages do not contain the answer, respond with exactly:\n   "The passages do not provide sufficient information to answer this question."\n5. Every step must be directly supported by the passages provided.\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, give exact steps and menu paths):\n'}}  •  **evaluation**: {'type': 'trace', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 2000}}  •  **cache**: {'enabled': True, 'cache_dir': './cache'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,I want to enter into Ambient mode. How can I do that?,"[{'text': '', 'title': '', 'content': 'Changing the content and settings for...","To enter Ambient Mode, press the button. \n\nAlternatively, if the TV is tur...",0.1212,0.0204,0.1008,0.0909,0.0408,0.0501,0.7500,1.0000,-0.2500,1.0,1.0,0.0
1,Where do I find signal information ?,"[{'text': '', 'title': '', 'content': 'Viewing Broadcast Information at a Gl...",Settings > Support > Self Diagnosis > Signal Information > Try Now,0.1000,0.1111,-0.0111,0.0500,0.1111,-0.0611,0.5000,1.0000,-0.5000,1.0,1.0,0.0
2,How can I view the channels that are serached by auto program function and H...,"[{'text': '', 'title': '', 'content': 'Viewing and selecting channels on Fav...",To view the channels that are searched by the auto program function:\n1. Go ...,0.3333,0.4211,-0.0878,0.2083,0.1579,0.0504,0.6250,0.3750,0.2500,0.0,1.0,-1.0
3,Can I configure Tint?,"[{'text': '', 'title': '', 'content': 'Setting the screen to black and white...","To configure Tint, follow these steps: \nSettings > Picture > Expert Setting...",0.1364,0.0323,0.1041,0.0455,0.0323,0.0132,0.3333,1.0000,-0.6667,1.0,1.0,0.0
4,How do I fix the missing/wrong color issue ?,"[{'text': '', 'title': '', 'content': 'This function may not be supported de...","To fix the missing/wrong color issue, try the following steps:\n\n1. Check t...",0.4583,0.0893,0.3690,0.2083,0.1786,0.0297,0.2727,0.4000,-0.1273,0.0,1.0,-1.0
5,How do I fix blurring issues on TV screen?,"[{'text': '', 'title': '', 'content': 'Setting the screen to black and white...","To fix blurring issues on the TV screen, follow these steps: \nSettings > Pi...",0.4074,0.0357,0.3717,0.1852,0.0357,0.1495,0.3636,1.0000,-0.6364,0.0,1.0,-1.0
6,What is the use of universal guide?,"[{'text': '', 'title': '', 'content': 'Accessibility Guidance. Provides a me...",The Universal Guide is an app that allows you to search for and enjoy variou...,0.1818,0.2778,-0.0960,0.1364,0.1667,-0.0303,0.7500,0.6000,0.1500,0.0,1.0,-1.0
7,What is the feature of Bixby guide?,"[{'text': '', 'title': '', 'content': 'Quick Guides. You can learn quickly h...","To view the Bixby guide, \n1. Press the button on your Samsung Smart Remote ...",0.2963,0.1333,0.1630,0.1111,0.1333,-0.0222,0.3750,1.0000,-0.6250,0.0,1.0,-1.0
8,How to launch the last used app automatically?,"[{'text': '', 'title': '', 'content': 'Launching the last used app automatic...","To launch the last used app automatically, follow these steps: \nSettings > ...",0.1053,0.0682,0.0371,0.0526,0.0455,0.0071,0.5000,0.6667,-0.1667,0.0,1.0,-1.0
9,Where do I find the list of my favorite channels?,"[{'text': '', 'title': '', 'content': 'Viewing and selecting channels on Fav...","To find the list of your favorite channels, follow these steps: \nPress the ...",0.6818,0.4167,0.2651,0.1818,0.3333,-0.1515,0.2667,0.8000,-0.5333,1.0,1.0,0.0
10,I want to setup a beautiful screens. How can I do that?,"[{'text': '', 'title': '', 'content': 'Using the Ambient Mode. Learn about t...","To setup a beautiful screen, follow these steps: \n1. Enter Ambient Mode by ...",0.4483,0.0328,0.4155,0.1034,0.0492,0.0542,0.2308,1.0000,-0.7692,0.0,1.0,-1.0
11,How do I record using time Timeshift function?,"[{'text': '', 'title': '', 'content': 'Before Using the Recording and Timesh...","To record using the Timeshift function, follow these steps: \n1. Press the b...",0.2750,0.2000,0.0750,0.1250,0.1000,0.0250,0.4545,0.5000,-0.0455,0.0,1.0,-1.0
12,My IP auto setting failed. How to configure it?,"[{'text': '', 'title': '', 'content': 'Enter the correct password if require...","To configure the IP settings, follow these steps: \nSettings > General > Net...",0.2174,0.1154,0.1020,0.0870,0.1538,-0.0668,0.4000,0.6667,-0.2667,1.0,1.0,0.0
13,How can I connect my mobile device to the TV?,"[{'text': '', 'title': '', 'content': 'Connecting Your Mobile Device. Connec...","To connect your mobile device to the TV, follow these steps: \n1. Turn on th...",0.4722,0.3929,0.0793,0.2500,0.3571,-0.1071,0.5294,0.9091,-0.3797,0.0,1.0,-1.0
14,How to configure Contrast and Sharpness?,"[{'text': '', 'title': '', 'content': 'Configuring advanced picture settings...","To configure Contrast and Sharpness, follow these steps: \nSettings > Pictur...",0.1500,0.0769,0.0731,0.0500,0.0769,-0.0269,0.3333,1.0000,-0.6667,1.0,1.0,0.0
15,What are the steps to reset network?,"[{'text': '', 'title': '', 'content': 'Resetting Your Network. Settings Gene...",Settings > General > Network > Reset Network > Try Now \n\nThis will restore...,0.3000,0.0370,0.2630,0.0333,0.0370,-0.0037,0.1111,1.0000,-0.8889,1.0,0.0,1.0
16,How do I view a list of mobile devices registered to the TV?,"[{'text': '', 'title': '', 'content': 'Managing Mobile Devices. Settings Gen...",Settings > General > External Device Manager > Device Connect Manager > Devi...,0.6111,0.1111,0.5000,0.0278,0.0741,-0.0463,0.0455,0.6667,-0.6212,1.0,1.0,0.0
17,I get this error 'some files cannot be played'. How do I fix this?,"[{'text': '', 'title': '', 'content': 'My File Won't Play. When files don't ...",The passages do not provide sufficient information to answer this question.,0.1290,0.2105,-0.0815,0.0645,0.1579,-0.0934,0.5000,0.2500,0.2500,1.0,0.0,1.0
18,How do I set scheduled viewing time?,"[{'text': '', 'title': '', 'content': 'Setting Up a Schedule Viewing. Config...","To set scheduled viewing time, follow these steps: \n1. Check the current ti...",0.8696,0.3500,0.5196,0.7391,0.1500,0.5891,0.7500,0.4286,0.3214,0.0,1.0,-1.0
19,Can I scan TV for malicious code ?,"[{'text': '', 'title': '', 'content': 'Scanning the TV and connected storage...","To scan the TV for malicious code, follow these steps: \nSettings > General ...",0.3571,0.7692,-0.4121,0.1071,0.5385,-0.4314,0.3000,0.7000,-0.4000,0.0,1.0,-1.0

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.3326,0.1951,0.2059,0.1870,0.2063
1,utilization_score,0.1429,0.1465,0.1509,0.1258,0.1005
2,completeness_score,0.4195,0.7481,0.1940,0.2503,0.4257
3,adherence_score,0.4500,0.9000,0.4975,0.3000,0.6500

None

================================================================================
Configuration: emanual_v5_hybrid_rrf
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `emanual_v5_hybrid_rrf`

**name**: emanual_v5_hybrid_rrf  •  **mode**: test  •  **providers**: {'groq': {'type': 'groq', 'api_key_env': 'GROQ_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'fixed_word', 'config': {'max_words': 128, 'overlap_words': 20}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'sentence-transformers/all-MiniLM-L6-v2', 'dimension': 384}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 384}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 20}}, {'type': 'sparse', 'config': {'top_k': 20}}]}, 'query_transform': None, 'fusion': {'type': 'rrf', 'config': {'top_k': 10, 'k': 60}}, 'rerank': None}  •  **generation**: {'strategy': 'default', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 512, 'system_prompt': 'You are a consumer-electronics product-support assistant. Answer questions\nabout device features and settings using ONLY the provided user-manual passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use outside knowledge.\n2. Give exact, step-by-step instructions. Preserve menu paths, button names,\n   setting names, and on-screen labels verbatim\n   (e.g. "Settings > Support > Self Diagnosis > Signal Information").\n3. Be concise and procedural - give the steps, not background.\n4. If the passages do not contain the answer, respond with exactly:\n   "The passages do not provide sufficient information to answer this question."\n5. Every step must be directly supported by the passages provided.\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, give exact steps and menu paths):\n'}}  •  **evaluation**: {'type': 'trace', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 2000}}  •  **cache**: {'enabled': True, 'cache_dir': './cache'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,I want to enter into Ambient mode. How can I do that?,"[{'text': '', 'title': '', 'content': 'Changing the content and settings for...","To enter Ambient Mode, press the button.",0.1231,0.0204,0.1027,0.0462,0.0408,0.0054,0.3750,1.0000,-0.6250,1.0,1.0,0.0
1,Where do I find signal information ?,"[{'text': '', 'title': '', 'content': 'Checking digital channel signal info ...","To find signal information, go to: Settings > Support > Self Diagnosis > Sig...",0.1316,0.1111,0.0205,0.0263,0.1111,-0.0848,0.2000,1.0000,-0.8000,1.0,1.0,0.0
2,How can I view the channels that are serached by auto program function and H...,"[{'text': '', 'title': '', 'content': 'Viewing and selecting channels on Fav...",To view the channels that are searched by the auto program function: \nPress...,0.1897,0.4211,-0.2314,0.0690,0.1579,-0.0889,0.3636,0.3750,-0.0114,0.0,1.0,-1.0
3,Can I configure Tint?,"[{'text': '', 'title': '', 'content': 'Configuring advanced picture settings...",Settings > Picture > Expert Settings > Try Now > Tint (G/R) > Try Now,0.0536,0.0323,0.0213,0.0179,0.0323,-0.0144,0.3333,1.0000,-0.6667,1.0,1.0,0.0
4,How do I fix the missing/wrong color issue ?,"[{'text': '', 'title': '', 'content': 'Inverting the screen color. Settings ...","To fix the missing/wrong color issue, follow these steps: \nSettings > Suppo...",0.2553,0.0893,0.1660,0.0851,0.1786,-0.0935,0.3333,0.4000,-0.0667,0.0,1.0,-1.0
5,How do I fix blurring issues on TV screen?,"[{'text': '', 'title': '', 'content': 'on your TV are correct but just a lit...","To fix blurring issues on the TV screen, use the Auto Motion Plus Settings f...",0.2157,0.0357,0.1800,0.0196,0.0357,-0.0161,0.0909,1.0000,-0.9091,0.0,1.0,-1.0
6,What is the use of universal guide?,"[{'text': '', 'title': '', 'content': 'Using the Universal Guide App. Search...",The Universal Guide is an app that allows you to search for and enjoy variou...,0.1774,0.2778,-0.1004,0.0968,0.1667,-0.0699,0.4545,0.6000,-0.1455,1.0,1.0,0.0
7,What is the feature of Bixby guide?,"[{'text': '', 'title': '', 'content': 'button, say a command, and then relea...","To view the Bixby guide, \n1. Press the button once. \n2. The ""Using Bixby"" ...",0.0921,0.1333,-0.0412,0.0395,0.1333,-0.0938,0.4286,1.0000,-0.5714,0.0,1.0,-1.0
8,How to launch the last used app automatically?,"[{'text': '', 'title': '', 'content': 'Launching the last used app automatic...","To launch the last used app automatically, follow these steps: \nSettings > ...",0.0385,0.0682,-0.0297,0.0256,0.0455,-0.0199,0.6667,0.6667,0.0000,1.0,1.0,0.0
9,Where do I find the list of my favorite channels?,"[{'text': '', 'title': '', 'content': 'Creating a Personal Favorites List. D...","To find the list of your favorite channels, follow these steps: \nPress the ...",0.2885,0.4167,-0.1282,0.0962,0.3333,-0.2371,0.3333,0.8000,-0.4667,1.0,1.0,0.0
10,I want to setup a beautiful screens. How can I do that?,"[{'text': '', 'title': '', 'content': 'the Ambient Mode browser will be prov...","To set up a beautiful screen, follow these steps: \n\n1. Enter Ambient Mode ...",0.1833,0.0328,0.1505,0.0500,0.0492,0.0008,0.0909,1.0000,-0.9091,0.0,1.0,-1.0
11,How do I record using time Timeshift function?,"[{'text': '', 'title': '', 'content': 'Buttons and functions available while...","To record using the Timeshift function, follow these steps: \n\n1. Press the...",0.5067,0.2000,0.3067,0.1467,0.1000,0.0467,0.2895,0.5000,-0.2105,0.0,1.0,-1.0
12,My IP auto setting failed. How to configure it?,"[{'text': '', 'title': '', 'content': 'turned on. If it is, turn it off and ...","To configure the IP settings, go to Settings > General > Network > Network S...",0.0597,0.1154,-0.0557,0.0746,0.1538,-0.0792,0.5000,0.6667,-0.1667,0.0,1.0,-1.0
13,How can I connect my mobile device to the TV?,"[{'text': '', 'title': '', 'content': 'Connecting Your Mobile Device. Connec...","To connect your mobile device to the TV, follow these steps: \n1. Turn on th...",0.2698,0.3929,-0.1231,0.1270,0.3571,-0.2301,0.4118,0.9091,-0.4973,0.0,1.0,-1.0
14,How to configure Contrast and Sharpness?,"[{'text': '', 'title': '', 'content': 'Configuring advanced picture settings...","To configure Contrast and Sharpness, follow these steps: \nSettings > Pictur...",0.1163,0.0769,0.0394,0.0233,0.0769,-0.0536,0.2000,1.0000,-0.8000,1.0,1.0,0.0
15,What are the steps to reset network?,"[{'text': '', 'title': '', 'content': 'I Want to Reset the TV. Initialize th...","To reset the network, follow these steps: \nSettings > General > Network > R...",0.4143,0.0370,0.3773,0.0143,0.0370,-0.0227,0.0345,1.0000,-0.9655,1.0,0.0,1.0
16,How do I view a list of mobile devices registered to the TV?,"[{'text': '', 'title': '', 'content': 'Managing Mobile Devices. Settings Gen...","To view a list of mobile devices registered to the TV, go to: \nSettings > G...",0.1096,0.1111,-0.0015,0.0137,0.0741,-0.0604,0.1250,0.6667,-0.5417,0.0,1.0,-1.0
17,I get this error 'some files cannot be played'. How do I fix this?,"[{'text': '', 'title': '', 'content': 'My File Won't Play. When files don't ...",The passages do not provide sufficient information to answer this question.,0.1569,0.2105,-0.0536,0.0000,0.1579,-0.1579,0.0000,0.2500,-0.2500,0.0,0.0,0.0
18,How do I set scheduled viewing time?,"[{'text': '', 'title': '', 'content': 'Setting Up a Schedule Viewing. Config...","To set scheduled viewing time, follow these steps: \n1. Check the current ti...",0.5962,0.3500,0.2462,0.2885,0.1500,0.1385,0.4839,0.4286,0.0553,0.0,1.0,-1.0
19,Can I scan TV for malicious code ?,"[{'text': '', 'title': '', 'content': 'Scanning the TV and connected storage...","To scan the TV for malicious code, follow these steps: \nSettings > General ...",0.1250,0.7692,-0.6442,0.0938,0.5385,-0.4447,0.7500,0.7000,0.0500,1.0,1.0,0.0

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.2052,0.1951,0.1458,0.1870,0.1510
1,utilization_score,0.0677,0.1465,0.0646,0.1258,0.0979
2,completeness_score,0.3232,0.7481,0.1955,0.2503,0.4354
3,adherence_score,0.4500,0.9000,0.4975,0.3000,0.5500

None

================================================================================
Configuration: emanual_v6_rerank_only
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `emanual_v6_rerank_only`

**name**: emanual_v6_rerank_only  •  **mode**: test  •  **providers**: {'groq': {'type': 'groq', 'api_key_env': 'GROQ_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'fixed_word', 'config': {'max_words': 128, 'overlap_words': 20}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'sentence-transformers/all-MiniLM-L6-v2', 'dimension': 384}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 384}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 20}}]}, 'query_transform': None, 'fusion': None, 'rerank': {'type': 'cross_encoder', 'config': {'model_name': 'BAAI/bge-reranker-v2-m3', 'top_k': 5}}}  •  **generation**: {'strategy': 'default', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 512, 'system_prompt': 'You are a consumer-electronics product-support assistant. Answer questions\nabout device features and settings using ONLY the provided user-manual passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use outside knowledge.\n2. Give exact, step-by-step instructions. Preserve menu paths, button names,\n   setting names, and on-screen labels verbatim\n   (e.g. "Settings > Support > Self Diagnosis > Signal Information").\n3. Be concise and procedural - give the steps, not background.\n4. If the passages do not contain the answer, respond with exactly:\n   "The passages do not provide sufficient information to answer this question."\n5. Every step must be directly supported by the passages provided.\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, give exact steps and menu paths):\n'}}  •  **evaluation**: {'type': 'trace', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 2000}}  •  **cache**: {'enabled': True, 'cache_dir': './cache'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,I want to enter into Ambient mode. How can I do that?,"[{'text': '', 'title': '', 'content': 'beautiful screens, various visual inf...","To enter Ambient Mode, press the button. \n\nNote: The passages do not speci...",0.2162,0.0204,0.1958,0.1351,0.0408,0.0943,0.6250,1.0000,-0.3750,0.0,1.0,-1.0
1,Where do I find signal information ?,"[{'text': '', 'title': '', 'content': 'Checking digital channel signal info ...","To find signal information, go to: Settings > Support > Self Diagnosis > Sig...",0.0690,0.1111,-0.0421,0.0345,0.1111,-0.0766,0.5000,1.0000,-0.5000,1.0,1.0,0.0
2,How can I view the channels that are serached by auto program function and H...,"[{'text': '', 'title': '', 'content': 'up and down directional buttons to mo...",To view the channels that are searched by the auto program function:\n1. Pre...,0.5333,0.4211,0.1122,0.2667,0.1579,0.1088,0.5000,0.3750,0.1250,0.0,1.0,-1.0
3,Can I configure Tint?,"[{'text': '', 'title': '', 'content': 'Configuring advanced picture settings...",Settings > Picture > Expert Settings > Try Now > Tint (G/R) > Try Now,0.0286,0.0323,-0.0037,0.0286,0.0323,-0.0037,1.0000,1.0000,0.0000,1.0,1.0,0.0
4,How do I fix the missing/wrong color issue ?,"[{'text': '', 'title': '', 'content': 'on your TV are correct but just a lit...","To fix the missing/wrong color issue, follow these steps:\n\n1. Run the ""Sta...",0.2500,0.0893,0.1607,0.2188,0.1786,0.0402,0.3750,0.4000,-0.0250,0.0,1.0,-1.0
5,How do I fix blurring issues on TV screen?,"[{'text': '', 'title': '', 'content': 'on your TV are correct but just a lit...","To fix blurring issues on the TV screen, follow these steps: \n1. Go to Sett...",NaN,0.0357,NaN,NaN,0.0357,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
6,What is the use of universal guide?,"[{'text': '', 'title': '', 'content': 'Using the Universal Guide App. Search...",The Universal Guide is an app that allows you to search for and enjoy variou...,0.2162,0.2778,-0.0616,0.1622,0.1667,-0.0045,0.6250,0.6000,0.0250,0.0,1.0,-1.0
7,What is the feature of Bixby guide?,"[{'text': '', 'title': '', 'content': 'Running Bixby. Press and hold the but...","To view the Bixby guide, \n1. Press the Bixby button once. \n2. When you pre...",0.1515,0.1333,0.0182,0.0909,0.1333,-0.0424,0.6000,1.0000,-0.4000,0.0,1.0,-1.0
8,How to launch the last used app automatically?,"[{'text': '', 'title': '', 'content': 'Launching the last used app automatic...","To launch the last used app automatically, follow these steps: \nSettings > ...",0.0714,0.0682,0.0032,0.0476,0.0455,0.0021,0.6667,0.6667,0.0000,1.0,1.0,0.0
9,Where do I find the list of my favorite channels?,"[{'text': '', 'title': '', 'content': 'Creating a Personal Favorites List. D...","To find the list of your favorite channels, follow these steps: \n\nPress th...",0.5806,0.4167,0.1639,0.3548,0.3333,0.0215,0.4444,0.8000,-0.3556,0.0,1.0,-1.0
10,I want to setup a beautiful screens. How can I do that?,"[{'text': '', 'title': '', 'content': 'the Ambient Mode browser will be prov...","To set up a beautiful screen, follow these steps: \nIn the Ambient Mode brow...",0.2414,0.0328,0.2086,0.1034,0.0492,0.0542,0.4286,1.0000,-0.5714,0.0,1.0,-1.0
11,How do I record using time Timeshift function?,"[{'text': '', 'title': '', 'content': 'to Using the Recording and Timeshift'...","To record using the Timeshift function, follow these steps: \n1. Press the b...",NaN,0.2000,NaN,NaN,0.1000,NaN,NaN,0.5000,NaN,NaN,1.0,NaN
12,My IP auto setting failed. How to configure it?,"[{'text': '', 'title': '', 'content': 'turned on. If it is, turn it off and ...","To configure the IP settings, follow these steps: \nSettings > General > Net...",NaN,0.1154,NaN,NaN,0.1538,NaN,NaN,0.6667,NaN,NaN,1.0,NaN
13,How can I connect my mobile device to the TV?,"[{'text': '', 'title': '', 'content': 'Connecting Your Mobile Device. Connec...","To connect your mobile device to the TV, follow these steps: \n1. Turn on th...",NaN,0.3929,NaN,NaN,0.3571,NaN,NaN,0.9091,NaN,NaN,1.0,NaN
14,How to configure Contrast and Sharpness?,"[{'text': '', 'title': '', 'content': 'Configuring advanced picture settings...","To configure Contrast and Sharpness, follow these steps: \nSettings > Pictur...",NaN,0.0769,NaN,NaN,0.0769,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
15,What are the steps to reset network?,"[{'text': '', 'title': '', 'content': 'Resetting Your Network. Settings Gene...",Settings > General > Network > Reset Network > Try Now \n\nThis will restore...,NaN,0.0370,NaN,NaN,0.0370,NaN,NaN,1.0000,NaN,NaN,0.0,NaN
16,How do I view a list of mobile devices registered to the TV?,"[{'text': '', 'title': '', 'content': 'Connecting Your Mobile Device. Connec...",Settings > General > External Device Manager > Device Connect Manager > Devi...,NaN,0.1111,NaN,NaN,0.0741,NaN,NaN,0.6667,NaN,NaN,1.0,NaN
17,I get this error 'some files cannot be played'. How do I fix this?,"[{'text': '', 'title': '', 'content': 'My File Won't Play. When files don't ...",The passages do not provide sufficient information to answer this question.,NaN,0.2105,NaN,NaN,0.1579,NaN,NaN,0.2500,NaN,NaN,0.0,NaN
18,How do I set scheduled viewing time?,"[{'text': '', 'title': '', 'content': 'Setting Up a Schedule Viewing. Config...","To set scheduled viewing time, follow these steps: \n1. Check the current ti...",NaN,0.3500,NaN,NaN,0.1500,NaN,NaN,0.4286,NaN,NaN,1.0,NaN
19,Can I scan TV for malicious code ?,"[{'text': '', 'title': '', 'content': 'Scanning the TV and connected storage...","To scan the TV for malicious code, follow these steps: \nSettings > General ...",NaN,0.7692,NaN,NaN,0.5385,NaN,NaN,0.7000,NaN,NaN,1.0,NaN

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.2358,0.1951,0.1770,0.1870,0.0970
1,utilization_score,0.1443,0.1465,0.1023,0.1258,0.0448
2,completeness_score,0.5765,0.7481,0.1686,0.2503,0.2377
3,adherence_score,0.3000,0.9000,0.4583,0.3000,0.7000

None

================================================================================
Configuration: emanual_v7_hybrid_rerank
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `emanual_v7_hybrid_rerank`

**name**: emanual_v7_hybrid_rerank  •  **mode**: test  •  **providers**: {'groq': {'type': 'groq', 'api_key_env': 'GROQ_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'fixed_word', 'config': {'max_words': 128, 'overlap_words': 20}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'BAAI/bge-base-en-v1.5', 'dimension': 768}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 768}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 20}}, {'type': 'sparse', 'config': {'top_k': 20}}]}, 'query_transform': None, 'fusion': {'type': 'rrf', 'config': {'top_k': 10, 'k': 60}}, 'rerank': {'type': 'cross_encoder', 'config': {'model_name': 'BAAI/bge-reranker-v2-m3', 'top_k': 5}}}  •  **generation**: {'strategy': 'default', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 512, 'system_prompt': 'You are a consumer-electronics product-support assistant. Answer questions\nabout device features and settings using ONLY the provided user-manual passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use outside knowledge.\n2. Give exact, step-by-step instructions. Preserve menu paths, button names,\n   setting names, and on-screen labels verbatim\n   (e.g. "Settings > Support > Self Diagnosis > Signal Information").\n3. Be concise and procedural - give the steps, not background.\n4. If the passages do not contain the answer, respond with exactly:\n   "The passages do not provide sufficient information to answer this question."\n5. Every step must be directly supported by the passages provided.\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, give exact steps and menu paths):\n'}}  •  **evaluation**: {'type': 'trace', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 2000}}  •  **cache**: {'enabled': True, 'cache_dir': './cache'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,I want to enter into Ambient mode. How can I do that?,"[{'text': '', 'title': '', 'content': 'beautiful screens, various visual inf...","To enter Ambient Mode, press the button.",0.1892,0.0204,0.1688,0.1351,0.0408,0.0943,0.7143,1.0000,-0.2857,1.0,1.0,0.0
1,Where do I find signal information ?,"[{'text': '', 'title': '', 'content': 'Checking digital channel signal info ...",Settings > Support > Self Diagnosis > Signal Information > Try Now,0.2727,0.1111,0.1616,0.0455,0.1111,-0.0656,0.1667,1.0000,-0.8333,1.0,1.0,0.0
2,How can I view the channels that are serached by auto program function and H...,"[{'text': '', 'title': '', 'content': 'up and down directional buttons to mo...",To view the channels that are searched by the auto program function: \n1. Pr...,NaN,0.4211,NaN,NaN,0.1579,NaN,NaN,0.3750,NaN,NaN,1.0,NaN
3,Can I configure Tint?,"[{'text': '', 'title': '', 'content': 'Configuring advanced picture settings...",Settings > Picture > Expert Settings > Try Now > Tint (G/R) > Try Now,NaN,0.0323,NaN,NaN,0.0323,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
4,How do I fix the missing/wrong color issue ?,"[{'text': '', 'title': '', 'content': 'on your TV are correct but just a lit...","To fix the missing/wrong color issue, follow these steps:\n\n1. Run the ""Sta...",NaN,0.0893,NaN,NaN,0.1786,NaN,NaN,0.4000,NaN,NaN,1.0,NaN
5,How do I fix blurring issues on TV screen?,"[{'text': '', 'title': '', 'content': 'on your TV are correct but just a lit...","To fix blurring issues on the TV screen, try the following steps:\n\n1. Go t...",NaN,0.0357,NaN,NaN,0.0357,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
6,What is the use of universal guide?,"[{'text': '', 'title': '', 'content': 'Using the Universal Guide App. Search...",The Universal Guide is an app that allows you to search for and enjoy variou...,NaN,0.2778,NaN,NaN,0.1667,NaN,NaN,0.6000,NaN,NaN,1.0,NaN
7,What is the feature of Bixby guide?,"[{'text': '', 'title': '', 'content': 'Running Bixby. Press and hold the but...","To view the Bixby guide, \n1. Press the button on your Samsung Smart Remote ...",NaN,0.1333,NaN,NaN,0.1333,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
8,How to launch the last used app automatically?,"[{'text': '', 'title': '', 'content': 'Launching the last used app automatic...","To launch the last used app automatically, follow these steps: \nSettings > ...",NaN,0.0682,NaN,NaN,0.0455,NaN,NaN,0.6667,NaN,NaN,1.0,NaN
9,Where do I find the list of my favorite channels?,"[{'text': '', 'title': '', 'content': 'Creating a Personal Favorites List. D...","To find the list of your favorite channels, follow these steps: \nPress the ...",NaN,0.4167,NaN,NaN,0.3333,NaN,NaN,0.8000,NaN,NaN,1.0,NaN
10,I want to setup a beautiful screens. How can I do that?,"[{'text': '', 'title': '', 'content': 'the Ambient Mode browser will be prov...","To set up beautiful screens, follow these steps: \nIn the Ambient Mode brows...",NaN,0.0328,NaN,NaN,0.0492,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
11,How do I record using time Timeshift function?,"[{'text': '', 'title': '', 'content': 'to Using the Recording and Timeshift'...","To record using the Timeshift function, follow these steps: \n1. Press the b...",NaN,0.2000,NaN,NaN,0.1000,NaN,NaN,0.5000,NaN,NaN,1.0,NaN
12,My IP auto setting failed. How to configure it?,"[{'text': '', 'title': '', 'content': 'turned on. If it is, turn it off and ...","To configure the IP settings, follow these steps: \nSettings > General > Net...",NaN,0.1154,NaN,NaN,0.1538,NaN,NaN,0.6667,NaN,NaN,1.0,NaN
13,How can I connect my mobile device to the TV?,"[{'text': '', 'title': '', 'content': 'Connecting Your Mobile Device. Connec...","To connect your mobile device to the TV, follow these steps: \n1. Turn on th...",NaN,0.3929,NaN,NaN,0.3571,NaN,NaN,0.9091,NaN,NaN,1.0,NaN
14,How to configure Contrast and Sharpness?,"[{'text': '', 'title': '', 'content': 'Configuring advanced picture settings...","To configure Contrast and Sharpness, follow these steps: \nSettings > Pictur...",NaN,0.0769,NaN,NaN,0.0769,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
15,What are the steps to reset network?,"[{'text': '', 'title': '', 'content': 'Resetting Your Network. Settings Gene...",Settings > General > Network > Reset Network > Try Now \n\n(This will restor...,NaN,0.0370,NaN,NaN,0.0370,NaN,NaN,1.0000,NaN,NaN,0.0,NaN
16,How do I view a list of mobile devices registered to the TV?,"[{'text': '', 'title': '', 'content': 'Connecting Your Mobile Device. Connec...",Settings > General > External Device Manager > Device Connect Manager > Devi...,NaN,0.1111,NaN,NaN,0.0741,NaN,NaN,0.6667,NaN,NaN,1.0,NaN
17,I get this error 'some files cannot be played'. How do I fix this?,"[{'text': '', 'title': '', 'content': 'My File Won't Play. When files don't ...",The passages do not provide sufficient information to answer this question.,NaN,0.2105,NaN,NaN,0.1579,NaN,NaN,0.2500,NaN,NaN,0.0,NaN
18,How do I set scheduled viewing time?,"[{'text': '', 'title': '', 'content': 'Setting Up a Schedule Viewing. Config...","To set scheduled viewing time, follow these steps: \n1. Check the current ti...",NaN,0.3500,NaN,NaN,0.1500,NaN,NaN,0.4286,NaN,NaN,1.0,NaN
19,Can I scan TV for malicious code ?,"[{'text': '', 'title': '', 'content': 'Scanning the TV and connected storage...","To scan the TV for malicious code, follow these steps: \nSettings > General ...",NaN,0.7692,NaN,NaN,0.5385,NaN,NaN,0.7000,NaN,NaN,1.0,NaN

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.2310,0.1951,0.0417,0.1870,0.1652
1,utilization_score,0.0903,0.1465,0.0448,0.1258,0.0799
2,completeness_score,0.4405,0.7481,0.2738,0.2503,0.5595
3,adherence_score,1.0000,0.9000,0.0000,0.3000,0.0000

None

================================================================================
Configuration: emanual_v8_hyde
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `emanual_v8_hyde`

**name**: emanual_v8_hyde  •  **mode**: test  •  **providers**: {'groq': {'type': 'groq', 'api_key_env': 'GROQ_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'fixed_word', 'config': {'max_words': 128, 'overlap_words': 20}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'BAAI/bge-base-en-v1.5', 'dimension': 768}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 768}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 20}}, {'type': 'sparse', 'config': {'top_k': 20}}]}, 'query_transform': {'type': 'hyde', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.2, 'max_tokens': 256}}, 'fusion': {'type': 'rrf', 'config': {'top_k': 10, 'k': 60}}, 'rerank': {'type': 'cross_encoder', 'config': {'model_name': 'BAAI/bge-reranker-v2-m3', 'top_k': 5}}}  •  **generation**: {'strategy': 'default', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 512, 'system_prompt': 'You are a consumer-electronics product-support assistant. Answer questions\nabout device features and settings using ONLY the provided user-manual passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use outside knowledge.\n2. Give exact, step-by-step instructions. Preserve menu paths, button names,\n   setting names, and on-screen labels verbatim\n   (e.g. "Settings > Support > Self Diagnosis > Signal Information").\n3. Be concise and procedural - give the steps, not background.\n4. If the passages do not contain the answer, respond with exactly:\n   "The passages do not provide sufficient information to answer this question."\n5. Every step must be directly supported by the passages provided.\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, give exact steps and menu paths):\n'}}  •  **evaluation**: {'type': 'trace', 'provider': 'groq', 'config': {'model': 'llama-3.3-70b-versatile', 'temperature': 0.0, 'max_tokens': 2000}}  •  **cache**: {'enabled': True, 'cache_dir': './cache'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,I want to enter into Ambient mode. How can I do that?,"[{'text': '', 'title': '', 'content': 'beautiful screens, various visual inf...","To enter Ambient Mode, press the button. \n\nNote: The passages do not speci...",None,0.0204,None,None,0.0408,None,None,1.0000,None,None,1.0,None
1,Where do I find signal information ?,"[{'text': '', 'title': '', 'content': 'Checking digital channel signal info ...",Settings > Support > Self Diagnosis > Signal Information > Try Now,None,0.1111,None,None,0.1111,None,None,1.0000,None,None,1.0,None
2,How can I view the channels that are serached by auto program function and H...,"[{'text': '', 'title': '', 'content': 'up and down directional buttons to mo...",To view the channels that are searched by the auto program function: \nPress...,None,0.4211,None,None,0.1579,None,None,0.3750,None,None,1.0,None
3,Can I configure Tint?,"[{'text': '', 'title': '', 'content': 'Configuring advanced picture settings...",Settings > Picture > Expert Settings > Try Now > Tint (G/R) > Try Now,None,0.0323,None,None,0.0323,None,None,1.0000,None,None,1.0,None
4,How do I fix the missing/wrong color issue ?,"[{'text': '', 'title': '', 'content': 'Solution Power Saving Mode Settings G...","To fix the missing/wrong color issue, follow these steps:\n\n1. Run the ""Sta...",None,0.0893,None,None,0.1786,None,None,0.4000,None,None,1.0,None
5,How do I fix blurring issues on TV screen?,"[{'text': '', 'title': '', 'content': 'on your TV are correct but just a lit...","To fix blurring issues on the TV screen, follow these steps: \nSettings > Pi...",None,0.0357,None,None,0.0357,None,None,1.0000,None,None,1.0,None
6,What is the use of universal guide?,"[{'text': '', 'title': '', 'content': 'Using the Universal Guide App. Search...",The Universal Guide is an app that allows you to search for and enjoy variou...,None,0.2778,None,None,0.1667,None,None,0.6000,None,None,1.0,None
7,What is the feature of Bixby guide?,"[{'text': '', 'title': '', 'content': 'Running Bixby. Press and hold the but...","To view the Bixby guide, \n1. Press the button on your Samsung Smart Remote ...",None,0.1333,None,None,0.1333,None,None,1.0000,None,None,1.0,None
8,How to launch the last used app automatically?,"[{'text': '', 'title': '', 'content': 'Launching the last used app automatic...","To launch the last used app automatically, follow these steps: \nSettings > ...",None,0.0682,None,None,0.0455,None,None,0.6667,None,None,1.0,None
9,Where do I find the list of my favorite channels?,"[{'text': '', 'title': '', 'content': 'Creating a Personal Favorites List. D...","To find the list of your favorite channels, follow these steps: \n\nPress th...",None,0.4167,None,None,0.3333,None,None,0.8000,None,None,1.0,None
10,I want to setup a beautiful screens. How can I do that?,"[{'text': '', 'title': '', 'content': 'the Ambient Mode browser will be prov...","To set up beautiful screens, follow these steps: \nIn the Ambient Mode brows...",None,0.0328,None,None,0.0492,None,None,1.0000,None,None,1.0,None
11,How do I record using time Timeshift function?,"[{'text': '', 'title': '', 'content': 'to Using the Recording and Timeshift'...","To record using the Timeshift function, follow these steps: \n1. Press the b...",None,0.2000,None,None,0.1000,None,None,0.5000,None,None,1.0,None
12,My IP auto setting failed. How to configure it?,"[{'text': '', 'title': '', 'content': 'turned on. If it is, turn it off and ...","To configure the IP settings, follow these steps: \nSettings > General > Net...",None,0.1154,None,None,0.1538,None,None,0.6667,None,None,1.0,None
13,How can I connect my mobile device to the TV?,"[{'text': '', 'title': '', 'content': 'Connecting Your Mobile Device. Connec...","To connect your mobile device to the TV, follow these steps: \n1. Turn on th...",None,0.3929,None,None,0.3571,None,None,0.9091,None,None,1.0,None
14,How to configure Contrast and Sharpness?,"[{'text': '', 'title': '', 'content': 'Configuring advanced picture settings...","To configure Contrast and Sharpness, follow these steps: \nSettings > Pictur...",None,0.0769,None,None,0.0769,None,None,1.0000,None,None,1.0,None
15,What are the steps to reset network?,"[{'text': '', 'title': '', 'content': 'Resetting Your Network. Settings Gene...",Settings > General > Network > Reset Network > Try Now \n\n(This will restor...,None,0.0370,None,None,0.0370,None,None,1.0000,None,None,0.0,None
16,How do I view a list of mobile devices registered to the TV?,"[{'text': '', 'title': '', 'content': 'Connecting Your Mobile Device. Connec...",Settings > General > External Device Manager > Device Connect Manager > Devi...,None,0.1111,None,None,0.0741,None,None,0.6667,None,None,1.0,None
17,I get this error 'some files cannot be played'. How do I fix this?,"[{'text': '', 'title': '', 'content': 'My File Won't Play. When files don't ...",The passages do not provide sufficient information to answer this question.,None,0.2105,None,None,0.1579,None,None,0.2500,None,None,0.0,None
18,How do I set scheduled viewing time?,"[{'text': '', 'title': '', 'content': 'Setting Up a Schedule Viewing. Config...","To set a scheduled viewing time, follow these steps: \n1. Check the current ...",None,0.3500,None,None,0.1500,None,None,0.4286,None,None,1.0,None
19,Can I scan TV for malicious code ?,"[{'text': '', 'title': '', 'content': 'Scanning the TV and connected storage...","To scan the TV for malicious code, follow these steps: \nSettings > General ...",None,0.7692,None,None,0.5385,None,None,0.7000,None,None,1.0,None

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,NaN,0.1951,NaN,0.1870,NaN
1,utilization_score,NaN,0.1465,NaN,0.1258,NaN
2,completeness_score,NaN,0.7481,NaN,0.2503,NaN
3,adherence_score,NaN,0.9000,NaN,0.3000,NaN

None

## 10. Compare Configurations

Generate a comparison report across all configurations to see which performs best.

In [12]:
# Generate comparison report
print("Generating comparison report...")
comparison = runner.compare()

print(f"\n✅ Comparison report generated!")
print(f"  Saved to: {experiment_config.report_dir}/comparison.csv")

Generating comparison report...

✅ Comparison report generated!
  Saved to: rag-experiments/emanual-experiment/reports/comparison.csv

In [13]:
# Display comparison
print("\nConfiguration Comparison:")
display(comparison.to_dataframe())

Configuration Comparison:

,config_name,relevance_score__mean,relevance_score__mae,utilization_score__mean,utilization_score__mae,completeness_score__mean,completeness_score__mae,adherence_score__mean,adherence_score__mae
0,emanual_v8_hyde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,emanual_v3_embed_bge,0.3013,0.1578,0.1467,0.1043,0.4333,0.3532,0.60,0.40
2,emanual_v6_rerank_only,0.2358,0.0970,0.1443,0.0448,0.5765,0.2377,0.30,0.70
3,emanual_v1_baseline,0.3785,0.2318,0.1678,0.1211,0.3797,0.4094,0.55,0.55
4,emanual_v11_role_aware_bgem3,0.0704,0.1369,0.0281,0.1184,0.4203,0.3594,0.35,0.65
5,emanual_v7_hybrid_rerank,0.2310,0.1652,0.0903,0.0799,0.4405,0.5595,1.00,0.00
6,emanual_v2_hybrid_wsum,0.1824,0.1257,0.0723,0.0937,0.3582,0.3899,0.40,0.70
7,emanual_v4_chunk_sentence,0.3326,0.2063,0.1429,0.1005,0.4195,0.4257,0.45,0.65
8,emanual_v5_hybrid_rrf,0.2052,0.1510,0.0677,0.0979,0.3232,0.4354,0.45,0.55

## 11. Summary

The ExperimentRunner provides a complete workflow for:

1. **Configuration-driven data loading** - Specify data source in YAML
2. **Automatic parsing** - Documents parsed using configured parser
3. **Multi-config evaluation** - Test multiple RAG configurations
4. **Parallel execution** - Speed up evaluation with parallel runs
5. **Comprehensive reporting** - Per-query and aggregate metrics
6. **Cross-config comparison** - Identify best performing config

### Key Benefits:

- **Reproducible** - Everything configured in YAML
- **Flexible** - Easy to change data source or parser
- **Scalable** - Parallel execution for faster evaluation
- **Comprehensive** - Detailed metrics and comparisons