# delucionqa Experiment Runner — OpenRouter variant

RAG ablation sweep for the **delucionqa** subset of `galileo-ai/ragbench`
(automotive owner's-manual QA), with all LLM calls through **OpenRouter**.
Run alongside the other OpenRouter notebooks — it uses its own
`config/`, `reports/`, `temp/`, and `cache_openrouter_delucionqa/` dirs.

Driven by `experiment_configs/delucionqa_openrouter_experiment.yaml`.
**Requires** `OPENROUTER_API_KEY` (comma-separate multiple keys to rotate).

## 1. Setup & Dependencies

In [1]:
get_ipython().system('pip3 install datasets faiss-cpu sentence-transformers torch groq openai python-dotenv nltk pandas -q')

[notice] A new release of pip is available: 26.0 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

## 2. Imports

In [2]:
import sys
import os
from pathlib import Path
from dotenv import load_dotenv

# --- Point this at wherever THIS repo (rag_cust_support) lives. ---
# On Colab this is typically under your mounted Drive. Adjust if different.
PROJECT_ROOT = Path('/content/drive/MyDrive/Capstone/rag_cust_support')
if not PROJECT_ROOT.exists():
    # Fallback: running locally from the notebooks/ folder.
    PROJECT_ROOT = Path.cwd().parent if 'notebooks' in str(Path.cwd()) else Path.cwd()

os.chdir(PROJECT_ROOT)
project_root = PROJECT_ROOT
# Make THIS repo win on sys.path (avoids importing a stale rag-foundry copy).
sys.path = [p for p in sys.path if 'rag-foundry' not in p]
if str(project_root) in sys.path:
    sys.path.remove(str(project_root))
sys.path.insert(0, str(project_root))

from experiment.experiment_config import ExperimentConfig
from experiment.experiment_runner import ExperimentRunner
import experiment.experiment_runner as _er, core.registry as _reg

load_dotenv(override=True)
print('Current directory:', Path.cwd())
print('experiment_runner loaded from:', _er.__file__)
print('core.registry   loaded from:', _reg.__file__)
assert 'rag-foundry' not in _er.__file__, 'Still importing the old rag-foundry code! Restart runtime.'
print('HuggingFace token loaded:', bool(os.getenv('HF_TOKEN')))
print('Groq API key loaded:', bool(os.getenv('GROQ_API_KEY')))
print('OpenRouter API key loaded:', bool(os.getenv('OPENROUTER_API_KEY')))

/Users/bhupendra.bhoi/pandas_env/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Current directory: /Users/bhupendra.bhoi/aiml/Capstone Project/rag_cust_support
experiment_runner loaded from: /Users/bhupendra.bhoi/aiml/Capstone Project/rag_cust_support/experiment/experiment_runner.py
core.registry   loaded from: /Users/bhupendra.bhoi/aiml/Capstone Project/rag_cust_support/core/registry.py
HuggingFace token loaded: True
Groq API key loaded: True
OpenRouter API key loaded: True

## 3. Load Experiment Configuration

The experiment configuration file specifies:
- **data_loader**: How to load data (HuggingFace with dataset_name, subset, split)
- **data_parser**: How to parse documents (title_passage)
- **config_dir**: Directory containing RAG pipeline configs
- **num_queries**: Number of queries to evaluate
- **parallel**: Whether to run configs in parallel

In [14]:
EXPERIMENT_CONFIG_PATH = project_root / "experiment_configs/delucionqa_openrouter_validation.yaml"

experiment_config = ExperimentConfig.load(EXPERIMENT_CONFIG_PATH)

print("Experiment Configuration:")
print(f"  Config Dir:  {experiment_config.config_dir}")
print(f"  Report Dir:  {experiment_config.report_dir}")
print(f"  Temp Dir:    {experiment_config.temp_dir}")
print(f"  Cache:       {experiment_config.cache}")
print(f"  Num Queries: {experiment_config.end_index}")
print(f"  Parallel:    {experiment_config.parallel}")
print(f"  Max Workers: {experiment_config.max_workers}")
print(f"\nData Loader:")
print(f"  Type: {experiment_config.data_loader['type']}")
print(f"  Config: {experiment_config.data_loader['config']}")
print(f"\nData Parser:")
print(f"  Type: {experiment_config.data_parser}")

Experiment Configuration:
  Config Dir:  rag-experiments/delucionqa-openrouter-experiment/validation_config
  Report Dir:  rag-experiments/delucionqa-openrouter-experiment/reports
  Temp Dir:    rag-experiments/delucionqa-openrouter-experiment/temp
  Cache:       {'enabled': True, 'cache_dir': './cache_openrouter_delucionqa'}
  Num Queries: 100
  Parallel:    False
  Max Workers: 1

Data Loader:
  Type: huggingface
  Config: {'dataset_name': 'galileo-ai/ragbench', 'subset': 'delucionqa', 'split': 'test', 'limit': 184}

Data Parser:
  Type: noop

## 4. Initialize Experiment Runner

The ExperimentRunner will:
- Create report directory if it doesn't exist
- Load RAG configs from the specified directory
- Load and parse data automatically based on YAML config

In [15]:
# Initialize experiment runner
runner = ExperimentRunner(experiment_config)
print("ExperimentRunner initialized")

ExperimentRunner initialized

In [16]:
# Load data automatically based on YAML configuration
print("Loading data based on experiment configuration...")
documents, raw_data = runner.load_data()

print(f"\n✅ Data loaded successfully!")
print(f"  Documents: {len(documents)} parsed documents")
print(f"  Raw Data:  {len(raw_data)} samples")

# Inspect first sample
first_sample = raw_data[0]
print(f"\nFirst Sample:")
print(f"  Question: {first_sample['question'][:100]}...")
print(f"  Documents: {len(first_sample['documents'])}")

Loading data based on experiment configuration...
Loading HuggingFace dataset: galileo-ai/ragbench/delucionqa (test)...
Loaded 184 samples

✅ Data loaded successfully!
  Documents: 235 parsed documents
  Raw Data:  184 samples

First Sample:
  Question: What if I fail to latch the tailgate properly?...
  Documents: 3

## 6. Load RAG Pipeline Configs

Load all RAG pipeline configurations from the config directory specified in the experiment config.

In [17]:
# Load RAG pipeline configs
configs = runner.load_configs()

print(f'Loaded {len(configs)} RAG pipeline configurations:')
for cfg in configs:
    searches = ' + '.join(s.type.value for s in cfg.retrieval.search.searches)
    fusion = cfg.retrieval.fusion.type.value if cfg.retrieval.fusion else '-'
    rerank = cfg.retrieval.rerank.type.value if cfg.retrieval.rerank else '-'
    qx = cfg.retrieval.query_transform.type.value if cfg.retrieval.query_transform else '-'
    gc = cfg.generation.config
    model = gc.get('model') if isinstance(gc, dict) else getattr(gc, 'model', None)
    print(f'  - {cfg.name}')
    print(f'      chunking={cfg.chunking.type.value}  embed={cfg.embedding.type.value}')
    print(f'      search=[{searches}]  fusion={fusion}  rerank={rerank}  q_transform={qx}')
    print(f'      generation_model={model}')

Loaded 2 RAG pipeline configurations:
  - delucionqa_or_v1_baseline
      chunking=fixed_word  embed=sentence_transformer
      search=[dense]  fusion=-  rerank=-  q_transform=-
      generation_model=meta-llama/llama-3.3-70b-instruct
  - delucionqa_or_v3_embed_bge
      chunking=fixed_word  embed=sentence_transformer
      search=[dense]  fusion=-  rerank=-  q_transform=-
      generation_model=meta-llama/llama-3.3-70b-instruct

## 7. Run Experiments

Run all RAG configurations on the loaded data. Each config will:
1. Build a vector index from the documents
2. Run queries against the index
3. Generate responses
4. Evaluate using TRACe metrics

Results are returned as PipelineRunResult objects.

In [18]:
get_ipython().system('pip install rank_bm25 -q')

# Run experiments

[notice] A new release of pip is available: 26.0 -> 26.1.2
[notice] To update, run: pip install --upgrade pip

In [19]:
# Run experiments

print(f"Running {len(configs)} configurations from {experiment_config.start_index} to {experiment_config.end_index} queries...")
print(f"Parallel mode: {experiment_config.parallel}")

runs = runner.run(documents, raw_data)

print(f"\n✅ Experiments completed!")
print(f"  Ran {len(runs)} configurations")

for run in runs:
    print(f"  - {run['config'].name}: {run['total_written']} queries")

Running 2 configurations from 0 to 100 queries...
Parallel mode: False
Progress: 20/100 (20.0%) | QPS: 204102.38 | ETA: 0s | Elapsed: 0sUsing key #2: ****fbdbUsing key #2: ****fbdb

================================================================================
HTTP 402 (retryable) on ****fbdb
Error code: 402 - {'error': {'message': 'Insufficient credits. This account never purchased credits. Make sure your key is on the correct account or org, and if so, purchase more at https://openrouter.ai/settings/credits', 'code': 402}}
{'provider': 'openrouter', 'current_index': 2, 'keys': [{'key_suffix': 'e916', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 25, 12, 44, 23, 259284), 'requests': 2, 'successes': 0, 'failures': 2, '429s': 2}, {'key_suffix': 'b076', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 25, 12, 44, 40, 636051), 'requests': 5, 'successes': 4, 'failures': 1, '429s': 1}, {'key_suffix': 'fbdb', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 25, 17, 44, 14, 811712), 'requests': 47, 'successes': 45, 'failures': 1, '429s': 1}, {'key_suffix': '2462', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'f2e4', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}]}
Using key #3: ****2462
================================================================================
HTTP 402 (retryable) on ****fbdb
Error code: 402 - {'error': {'message': 'Insufficient credits. This account never purchased credits. Make sure your key is on the correct account or org, and if so, purchase more at https://openrouter.ai/settings/credits', 'code': 402}}
{'provider': 'openrouter', 'current_index': 3, 'keys': [{'key_suffix': 'e916', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 25, 12, 44, 23, 259284), 'requests': 2, 'successes': 0, 'failures': 2, '429s': 2}, {'key_suffix': 'b076', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 25, 12, 44, 40, 636051), 'requests': 5, 'successes': 4, 'failures': 1, '429s': 1}, {'key_suffix': 'fbdb', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 25, 17, 44, 14, 815217), 'requests': 47, 'successes': 45, 'failures': 2, '429s': 2}, {'key_suffix': '2462', 'available': True, 'cooldown_until': None, 'requests': 1, 'successes': 0, 'failures': 0, '429s': 0}, {'key_suffix': 'f2e4', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}]}
Using key #3: ****2462
Progress: 21/100 (21.0%) | QPS: 6.96 | ETA: 11s | Elapsed: 3sUsing key #3: ****2462
Progress: 21/100 (21.0%) | QPS: 3.48 | ETA: 23s | Elapsed: 6sUsing key #3: ****2462
Progress: 22/100 (22.0%) | QPS: 2.19 | ETA: 36s | Elapsed: 10sUsing key #3: ****2462
Progress: 23/100 (23.0%) | QPS: 1.64 | ETA: 47s | Elapsed: 14sUsing key #3: ****2462
Progress: 24/100 (24.0%) | QPS: 1.49 | ETA: 51s | Elapsed: 16sUsing key #3: ****2462
Progress: 25/100 (25.0%) | QPS: 1.31 | ETA: 57s | Elapsed: 19sUsing key #3: ****2462
Progress: 26/100 (26.0%) | QPS: 1.29 | ETA: 57s | Elapsed: 20sUsing key #3: ****2462
Progress: 27/100 (27.0%) | QPS: 1.22 | ETA: 60s | Elapsed: 22sUsing key #3: ****2462
Progress: 28/100 (28.0%) | QPS: 1.21 | ETA: 59s | Elapsed: 23sUsing key #3: ****2462
Progress: 29/100 (29.0%) | QPS: 1.07 | ETA: 1.1m | Elapsed: 27sUsing key #3: ****2462
Progress: 30/100 (30.0%) | QPS: 1.00 | ETA: 1.2m | Elapsed: 30sUsing key #3: ****2462
Progress: 31/100 (31.0%) | QPS: 0.81 | ETA: 1.4m | Elapsed: 38sUsing key #3: ****2462
Progress: 32/100 (32.0%) | QPS: 0.74 | ETA: 1.5m | Elapsed: 43sUsing key #3: ****2462
Progress: 34/100 (34.0%) | QPS: 0.75 | ETA: 1.5m | Elapsed: 45sUsing key #3: ****2462
Progress: 34/100 (34.0%) | QPS: 0.74 | ETA: 1.5m | Elapsed: 46sUsing key #3: ****2462
Progress: 35/100 (35.0%) | QPS: 0.71 | ETA: 1.5m | Elapsed: 49sUsing key #3: ****2462
Using key #3: ****2462
Progress: 37/100 (37.0%) | QPS: 0.74 | ETA: 1.4m | Elapsed: 50sUsing key #3: ****2462
Progress: 38/100 (38.0%) | QPS: 0.71 | ETA: 1.4m | Elapsed: 53sUsing key #3: ****2462
Progress: 40/100 (40.0%) | QPS: 0.72 | ETA: 1.4m | Elapsed: 55sUsing key #3: ****2462
Progress: 40/100 (40.0%) | QPS: 0.71 | ETA: 1.4m | Elapsed: 56sUsing key #3: ****2462
Progress: 41/100 (41.0%) | QPS: 0.69 | ETA: 1.4m | Elapsed: 59sUsing key #3: ****2462
Progress: 42/100 (42.0%) | QPS: 0.69 | ETA: 1.4m | Elapsed: 1.0mUsing key #3: ****2462
Progress: 43/100 (43.0%) | QPS: 0.66 | ETA: 1.4m | Elapsed: 1.1mUsing key #3: ****2462
Progress: 44/100 (44.0%) | QPS: 0.57 | ETA: 1.6m | Elapsed: 1.3mUsing key #3: ****2462
Progress: 45/100 (45.0%) | QPS: 0.51 | ETA: 1.8m | Elapsed: 1.5mUsing key #3: ****2462
Progress: 47/100 (47.0%) | QPS: 0.53 | ETA: 1.7m | Elapsed: 1.5mUsing key #3: ****2462
Progress: 47/100 (47.0%) | QPS: 0.51 | ETA: 1.7m | Elapsed: 1.5mUsing key #3: ****2462
Progress: 48/100 (48.0%) | QPS: 0.50 | ETA: 1.7m | Elapsed: 1.6mUsing key #3: ****2462
Progress: 49/100 (49.0%) | QPS: 0.49 | ETA: 1.7m | Elapsed: 1.7mUsing key #3: ****2462
Progress: 50/100 (50.0%) | QPS: 0.48 | ETA: 1.7m | Elapsed: 1.7mUsing key #3: ****2462
Progress: 51/100 (51.0%) | QPS: 0.47 | ETA: 1.8m | Elapsed: 1.8mUsing key #3: ****2462
Progress: 52/100 (52.0%) | QPS: 0.47 | ETA: 1.7m | Elapsed: 1.8m================================================================================
HTTP 402 (retryable) on ****2462
Error code: 402 - {'error': {'message': 'Insufficient credits. This account never purchased credits. Make sure your key is on the correct account or org, and if so, purchase more at https://openrouter.ai/settings/credits', 'code': 402}}
{'provider': 'openrouter', 'current_index': 3, 'keys': [{'key_suffix': 'e916', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 25, 12, 44, 23, 259284), 'requests': 2, 'successes': 0, 'failures': 2, '429s': 2}, {'key_suffix': 'b076', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 25, 12, 44, 40, 636051), 'requests': 5, 'successes': 4, 'failures': 1, '429s': 1}, {'key_suffix': 'fbdb', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 25, 17, 44, 14, 815217), 'requests': 47, 'successes': 45, 'failures': 2, '429s': 2}, {'key_suffix': '2462', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 25, 17, 46, 4, 451480), 'requests': 34, 'successes': 32, 'failures': 1, '429s': 1}, {'key_suffix': 'f2e4', 'available': True, 'cooldown_until': None, 'requests': 0, 'successes': 0, 'failures': 0, '429s': 0}]}
Using key #4: ****f2e4
================================================================================
HTTP 402 (retryable) on ****f2e4
Error code: 402 - {'error': {'message': 'Insufficient credits. This account never purchased credits. Make sure your key is on the correct account or org, and if so, purchase more at https://openrouter.ai/settings/credits', 'code': 402}}
{'provider': 'openrouter', 'current_index': 4, 'keys': [{'key_suffix': 'e916', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 25, 12, 44, 23, 259284), 'requests': 2, 'successes': 0, 'failures': 2, '429s': 2}, {'key_suffix': 'b076', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 25, 12, 44, 40, 636051), 'requests': 5, 'successes': 4, 'failures': 1, '429s': 1}, {'key_suffix': 'fbdb', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 25, 17, 44, 14, 815217), 'requests': 47, 'successes': 45, 'failures': 2, '429s': 2}, {'key_suffix': '2462', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 25, 17, 46, 4, 451480), 'requests': 34, 'successes': 32, 'failures': 1, '429s': 1}, {'key_suffix': 'f2e4', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 25, 17, 46, 4, 957988), 'requests': 1, 'successes': 0, 'failures': 1, '429s': 1}]}
Using key #0: ****e916
================================================================================
HTTP 402 (retryable) on ****e916
Error code: 402 - {'error': {'message': 'Insufficient credits. This account never purchased credits. Make sure your key is on the correct account or org, and if so, purchase more at https://openrouter.ai/settings/credits', 'code': 402}}
{'provider': 'openrouter', 'current_index': 0, 'keys': [{'key_suffix': 'e916', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 25, 17, 46, 5, 390389), 'requests': 3, 'successes': 0, 'failures': 3, '429s': 3}, {'key_suffix': 'b076', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 25, 12, 44, 40, 636051), 'requests': 5, 'successes': 4, 'failures': 1, '429s': 1}, {'key_suffix': 'fbdb', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 25, 17, 44, 14, 815217), 'requests': 47, 'successes': 45, 'failures': 2, '429s': 2}, {'key_suffix': '2462', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 25, 17, 46, 4, 451480), 'requests': 34, 'successes': 32, 'failures': 1, '429s': 1}, {'key_suffix': 'f2e4', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 25, 17, 46, 4, 957988), 'requests': 1, 'successes': 0, 'failures': 1, '429s': 1}]}
Using key #1: ****b076
Progress: 52/100 (52.0%) | QPS: 0.47 | ETA: 1.7m | Elapsed: 1.9m================================================================================
HTTP 402 (retryable) on ****b076
Error code: 402 - {'error': {'message': 'This request requires more credits, or fewer max_tokens. You requested up to 512 tokens, but can only afford 265. To increase, visit https://openrouter.ai/settings/credits and upgrade to a paid account', 'code': 402, 'metadata': {'provider_name': None, 'previous_errors': [{'code': 402, 'message': 'This request requires more credits, or fewer max_tokens. You requested up to 512 tokens, but can only afford 212. To increase, visit https://openrouter.ai/settings/credits and upgrade to a paid account'}, {'code': 402, 'message': 'This request requires more credits, or fewer max_tokens. You requested up to 512 tokens, but can only afford 265. To increase, visit https://openrouter.ai/settings/credits and upgrade to a paid account'}, {'code': 402, 'message': 'This request requires more credits, or fewer max_tokens. You requested up to 512 tokens, but can only afford 331. To increase, visit https://openrouter.ai/settings/credits and upgrade to a paid account'}, {'code': 402, 'message': 'This request requires more credits, or fewer max_tokens. You requested up to 512 tokens, but can only afford 141. To increase, visit https://openrouter.ai/settings/credits and upgrade to a paid account'}, {'code': 402, 'message': 'This request requires more credits, or fewer max_tokens. You requested up to 512 tokens, but can only afford 47. To increase, visit https://openrouter.ai/settings/credits and upgrade to a paid account'}, {'code': 402, 'message': 'This request requires more credits, or fewer max_tokens. You requested up to 512 tokens, but can only afford 265. To increase, visit https://openrouter.ai/settings/credits and upgrade to a paid account'}, {'code': 402, 'message': 'This request requires more credits, or fewer max_tokens. You requested up to 512 tokens, but can only afford 118. To increase, visit https://openrouter.ai/settings/credits and upgrade to a paid account'}, {'code': 402, 'message': 'This request requires more credits, or fewer max_tokens. You requested up to 512 tokens, but can only afford 102. To increase, visit https://openrouter.ai/settings/credits and upgrade to a paid account'}, {'code': 402, 'message': 'This request requires more credits, or fewer max_tokens. You requested up to 512 tokens, but can only afford 147. To increase, visit https://openrouter.ai/settings/credits and upgrade to a paid account'}, {'code': 402, 'message': 'This request requires more credits, or fewer max_tokens. You requested up to 512 tokens, but can only afford 147. To increase, visit https://openrouter.ai/settings/credits and upgrade to a paid account'}, {'code': 402, 'message': 'This request requires more credits, or fewer max_tokens. You requested up to 512 tokens, but can only afford 149. To increase, visit https://openrouter.ai/settings/credits and upgrade to a paid account'}, {'code': 402, 'message': 'This request requires more credits, or fewer max_tokens. You requested up to 512 tokens, but can only afford 134. To increase, visit https://openrouter.ai/settings/credits and upgrade to a paid account'}]}}, 'user_id': 'user_3GxweLLleOxmjnPh6r3MY7VpKSG'}
{'provider': 'openrouter', 'current_index': 1, 'keys': [{'key_suffix': 'e916', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 25, 17, 46, 5, 390389), 'requests': 3, 'successes': 0, 'failures': 3, '429s': 3}, {'key_suffix': 'b076', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 25, 17, 46, 5, 899037), 'requests': 6, 'successes': 4, 'failures': 2, '429s': 2}, {'key_suffix': 'fbdb', 'available': True, 'cooldown_until': datetime.datetime(2026, 7, 25, 17, 44, 14, 815217), 'requests': 47, 'successes': 45, 'failures': 2, '429s': 2}, {'key_suffix': '2462', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 25, 17, 46, 4, 451480), 'requests': 34, 'successes': 32, 'failures': 1, '429s': 1}, {'key_suffix': 'f2e4', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 25, 17, 46, 4, 957988), 'requests': 1, 'successes': 0, 'failures': 1, '429s': 1}]}
Using key #2: ****fbdb
Progress: 52/100 (52.0%) | QPS: 0.46 | ETA: 1.7m | Elapsed: 1.9m

2026-07-25 17:45:06,656 ERROR rag.pipeline.rag_pipeline: Query failed: No available OpenRouter API keys (all rate-limited/cooling down).

================================================================================
HTTP 402 (retryable) on ****fbdb
Error code: 402 - {'error': {'message': 'Insufficient credits. This account never purchased credits. Make sure your key is on the correct account or org, and if so, purchase more at https://openrouter.ai/settings/credits', 'code': 402}}
{'provider': 'openrouter', 'current_index': 2, 'keys': [{'key_suffix': 'e916', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 25, 17, 46, 5, 390389), 'requests': 3, 'successes': 0, 'failures': 3, '429s': 3}, {'key_suffix': 'b076', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 25, 17, 46, 5, 899037), 'requests': 6, 'successes': 4, 'failures': 2, '429s': 2}, {'key_suffix': 'fbdb', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 25, 17, 46, 6, 656553), 'requests': 48, 'successes': 45, 'failures': 3, '429s': 3}, {'key_suffix': '2462', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 25, 17, 46, 4, 451480), 'requests': 34, 'successes': 32, 'failures': 1, '429s': 1}, {'key_suffix': 'f2e4', 'available': False, 'cooldown_until': datetime.datetime(2026, 7, 25, 17, 46, 4, 957988), 'requests': 1, 'successes': 0, 'failures': 1, '429s': 1}]}

2026-07-25 17:45:06,712 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:06,721 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:06,731 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:06,740 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:06,749 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:06,760 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:06,770 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:06,782 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:06,794 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:06,829 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:06,843 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:06,861 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:06,873 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:06,889 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:06,903 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:06,918 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:06,929 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:06,941 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:06,958 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:06,975 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:06,988 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:07,001 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:07,018 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:07,033 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:07,047 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:07,060 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:07,076 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:07,090 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:07,102 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:07,117 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:07,133 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:07,152 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:07,165 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:07,179 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:07,199 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:07,209 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:07,219 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:07,230 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:07,241 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:07,252 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:07,263 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:07,273 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:07,283 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:07,293 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:07,302 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:07,309 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.

Progress: 100/100 (100.0%) | QPS: 0.86 | ETA: 0s | Elapsed: 1.9m
Progress: 20/100 (20.0%) | QPS: 285326.80 | ETA: 0s | Elapsed: 0s

2026-07-25 17:45:10,564 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:10,565 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:10,591 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:10,591 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:10,619 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:10,619 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:10,649 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:10,649 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:10,684 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:10,685 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:10,723 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:10,723 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:10,764 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:10,771 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:10,794 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:10,795 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:10,823 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:10,825 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:10,851 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:10,852 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,085 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,085 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,111 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,111 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,137 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,142 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,167 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,168 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,204 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,208 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,230 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,235 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,257 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,259 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,284 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,285 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,308 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,309 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,332 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,332 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,356 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,357 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,388 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,394 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,415 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,421 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,441 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,448 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,467 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,474 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,495 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,501 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.

Progress: 71/100 (71.0%) | QPS: 70.80 | ETA: 0s | Elapsed: 1s

2026-07-25 17:45:11,527 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,528 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,556 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,556 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,592 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,592 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,625 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,632 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,664 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,669 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,702 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,702 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,744 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,755 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,797 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,810 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,837 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,845 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,873 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,882 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,906 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,915 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,937 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,945 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,967 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,975 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,994 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.
2026-07-25 17:45:11,998 ERROR rag.pipeline.rag_pipeline: Query failed: All OpenRouter API keys are currently rate limited.

Progress: 100/100 (100.0%) | QPS: 49.77 | ETA: 0s | Elapsed: 2s

✅ Experiments completed!
  Ran 2 configurations
  - delucionqa_or_v1_baseline: 100 queries
  - delucionqa_or_v3_embed_bge: 100 queries

## 7b. Evaluate Existing JSONL Files

Run offline evaluation on already-generated JSONL files.
Uses experiment-level evaluation config — all configs are scored with the same judge model.

- `parallel_runs=True` — evaluate multiple configs simultaneously
- `parallel_config_run=True` — evaluate records within each config in parallel

In [20]:
# Discover all configs and build run dicts from existing JSONL files
configs = runner.load_configs()
runs = []
for cfg in configs:
    jsonl_path = experiment_config.temp_dir / f"{cfg.name}.jsonl"
    if jsonl_path.exists():
        runs.append({"config_name": cfg.name, "config": cfg, "jsonl_path": jsonl_path})
    else:
        print(f"  Skipping {cfg.name} — no JSONL found")

print(f"Found {len(runs)} configs with JSONL files")

# Evaluate all configs: parallel across configs + parallel within each config
eval_runs = runner.evaluate_runs(
    runs,
    parallel_runs=True,
    parallel_config_run=True,
)

# Use eval_runs for report generation downstream
runs = eval_runs
print(f"\n✅ Evaluation complete: {len(eval_runs)} configs")

Record 21 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 2 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 22 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 23 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 24 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 25 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 26 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 27 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 28 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 29 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 30 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 31 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 32 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 33 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 34 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 35 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 36 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 37 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 38 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 39 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 40 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 41 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 42 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 44 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 43 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 45 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 46 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 47 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 48 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 49 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 50 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 52 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 51 evaluation failed: All OpenRouter API keys are currently rate limited.
Record 53 evaluation failed: All OpenRouter API keys are currently rate limited.

Found 2 configs with JSONL files
[delucionqa_or_v1_baseline] Evaluation complete → rag-experiments/delucionqa-openrouter-experiment/temp/delucionqa_or_v1_baseline.jsonl
[delucionqa_or_v3_embed_bge] Evaluation complete → rag-experiments/delucionqa-openrouter-experiment/temp/delucionqa_or_v3_embed_bge.jsonl

✅ Evaluation complete: 2 configs

## 8. Generate Reports

Generate detailed reports for each configuration including:
- Per-query table with all TRACe scores
- Aggregate statistics (mean, std, MAE)
- Comparison with ground truth

In [21]:
# Generate reports
print("Generating reports...")
reports = runner.generate_reports(runs)

print(f"\n✅ Reports generated!")
print(f"  Saved to: {experiment_config.report_dir}")

Generating reports...

✅ Reports generated!
  Saved to: rag-experiments/delucionqa-openrouter-experiment/reports

## 9. Display Reports

Display the generated reports with per-query and aggregate metrics.

In [22]:
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 80)

for report in reports:
    print(f"\n{'='*80}")
    print(f"Configuration: {report.config_name}")
    print(f"{'='*80}")
    
    # Display per-query results
    print("\nPer-Query Results:")
    display(report.display())

================================================================================
Configuration: delucionqa_or_v1_baseline
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `delucionqa_or_v1_baseline`

**name**: delucionqa_or_v1_baseline  •  **mode**: test  •  **providers**: {'openrouter': {'type': 'openrouter', 'api_key_env': 'OPENROUTER_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'fixed_word', 'config': {'max_words': 160, 'overlap_words': 24}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'sentence-transformers/all-MiniLM-L6-v2', 'dimension': 384}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 384}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 5}}]}, 'query_transform': None, 'fusion': None, 'rerank': None}  •  **generation**: {'strategy': 'default', 'provider': 'openrouter', 'config': {'model': 'meta-llama/llama-3.3-70b-instruct', 'temperature': 0.0, 'max_tokens': 512, 'system_prompt': 'You are an automotive owner\'s-manual support assistant. Answer questions\nabout vehicle features, controls, and procedures using ONLY the provided\nowner\'s-manual passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use outside knowledge.\n2. Give exact, step-by-step procedures. Preserve exact control names, button\n   names, warning/CAUTION text, and feature labels verbatim.\n3. Include any safety warnings (WARNING/CAUTION) that the passages attach to\n   the procedure.\n4. Be concise and procedural - give the steps, not background.\n5. If the passages do not contain the answer, respond with exactly:\n   "The passages do not provide sufficient information to answer this question."\n6. Every claim must be directly supported by the passages provided.\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, give exact steps, control names, and any safety warnings):\n'}}  •  **evaluation**: {'type': 'trace', 'provider': 'openrouter', 'config': {'model': 'meta-llama/llama-3.3-70b-instruct', 'temperature': 0.0, 'max_tokens': 2000}}  •  **cache**: {'enabled': True, 'cache_dir': './cache_openrouter_delucionqa'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,What if I fail to latch the tailgate properly?,"[{'text': '', 'title': '', 'content': 'If the Tonneau Cover is installed, ma...",Failure to securely latch the tailgate could result in damage to the vehicle...,0.2500,0.1111,0.1389,0.3333,0.1111,0.2222,1.0000,1.0000,0.0000,0.0,1.0,-1.0
1,What kind of safety features are implemented in this car?,"[{'text': '', 'title': '', 'content': 'OCCUPANT RESTRAINT SYSTEMS Some of th...",The passages mention the following safety features: \n1. Restraint systems (...,NaN,0.2500,NaN,NaN,0.2500,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
2,When will the Automatic SOS be triggered?,"[{'text': '', 'title': '', 'content': 'Automatic SOS — If Equipped Automatic...",The passages do not provide sufficient information to answer this question.,0.3214,0.0244,0.2970,0.0357,0.0244,0.0113,0.1111,1.0000,-0.8889,1.0,1.0,0.0
3,What happens if I accidentally push the SOS Call button?,"[{'text': '', 'title': '', 'content': 'Connected Services SOS FAQs — If Equi...","If you accidentally push the SOS Call button, you have 10 seconds to cancel ...",0.3750,0.0820,0.2930,0.1875,0.0656,0.1219,0.3333,0.8000,-0.4667,0.0,1.0,-1.0
4,What is the DEF?,"[{'text': '', 'title': '', 'content': 'DEF tank DEF pump DEF injector Electr...","The passages do not provide a direct definition of DEF, but according to Doc...",0.1600,0.0625,0.0975,0.2000,0.0625,0.1375,0.5000,1.0000,-0.5000,0.0,1.0,-1.0
5,What may cause erratic or noisy performance of the radio?,"[{'text': '', 'title': '', 'content': 'Under certain conditions, the mobile ...","According to Document 1, the mobile phone being on in your vehicle can cause...",0.2759,0.1143,0.1616,0.2759,0.1143,0.1616,1.0000,1.0000,0.0000,0.0,1.0,-1.0
6,how to calculate the gross trailer weight?,"[{'text': '', 'title': '', 'content': 'Gross Trailer Weight (GTW) The GTW is...","To calculate the Gross Trailer Weight (GTW), follow these steps:\n\n1. Put y...",0.1579,0.2727,-0.1148,0.2105,0.2727,-0.0622,1.0000,1.0000,0.0000,0.0,1.0,-1.0
7,What can the ASIST button do?,"[{'text': '', 'title': '', 'content': 'If equipped, the ASSIST Button is use...","The ASSIST Button is used for contacting Roadside Assistance, Vehicle Care, ...",0.1818,0.4348,-0.2530,0.0303,0.4348,-0.4045,0.1667,1.0000,-0.8333,0.0,1.0,-1.0
8,What does the Door Off Mirror Kit do?,"[{'text': '', 'title': '', 'content': 'Door Off Mirror Kit — If Equipped If ...",The Door Off Mirror Kit allows exterior rearview mirrors to be installed ont...,0.3571,0.1304,0.2267,0.3571,0.1304,0.2267,0.7000,1.0000,-0.3000,0.0,1.0,-1.0
9,Can I manually activate or deactivate the air conditioner?,"[{'text': '', 'title': '', 'content': 'The Air Conditioning (A/C) button all...","To manually activate or deactivate the air conditioner, press and release th...",0.2553,0.0811,0.1742,0.5319,0.1351,0.3968,1.0000,0.6667,0.3333,0.0,1.0,-1.0
10,what does the The cartridge block heater do?,"[{'text': '', 'title': '', 'content': 'The cartridge block heater clips into...",The cartridge block heater clips into the engine block near the water jacket...,0.3659,0.0492,0.3167,0.3659,0.0492,0.3167,1.0000,1.0000,0.0000,0.0,1.0,-1.0
11,When will the illuminated entry system be activated?,"[{'text': '', 'title': '', 'content': 'and will remain fully illuminated unt...",The passages do not provide sufficient information to answer this question.,0.2258,0.0541,0.1717,0.0000,0.0811,-0.0811,0.0000,1.0000,-1.0000,1.0,1.0,0.0
12,"If the light remains on after the bulb check, it indicates what problem?","[{'text': '', 'title': '', 'content': 'Your vehicle is equipped with a sophi...","If the Vehicle Security Light remains on after the bulb check, it indicates ...",0.1053,0.1042,0.0011,0.0526,0.0208,0.0318,0.5000,0.2000,0.3000,0.0,1.0,-1.0
13,What is special about power windows?,"[{'text': '', 'title': '', 'content': 'The power windows feature allows for ...",The power windows feature allows for movement of the windows with the push o...,0.2444,0.2759,-0.0315,0.2222,0.1379,0.0843,0.8182,0.5000,0.3182,0.0,1.0,-1.0
14,What should I do to jump start the car?,"[{'text': '', 'title': '', 'content': 'of the engine compartment. If your ve...","To jump start the car, follow these steps: \n1. Apply the parking brake, \n2...",1.0000,0.4127,0.5873,0.6486,0.2063,0.4423,0.6486,0.5000,0.1486,0.0,1.0,-1.0
15,How to deactivate the cruise control?,"[{'text': '', 'title': '', 'content': 'Cruise Control can be dangerous where...","To deactivate the Cruise Control, follow these steps:\n\n1. A soft tap on th...",0.3571,0.4667,-0.1096,0.3571,0.4667,-0.1096,0.5000,0.8571,-0.3571,0.0,1.0,-1.0
16,Is it safe for me to park the vehicle in somewhere very hot?,"[{'text': '', 'title': '', 'content': 'Transporting Passengers NEVER TRANSPO...",WARNING: Do not leave children or animals inside parked vehicles in hot weat...,0.2143,0.1622,0.0521,0.1667,0.1892,-0.0225,0.7778,1.0000,-0.2222,0.0,1.0,-1.0
17,Any tips for driving downhill?,"[{'text': '', 'title': '', 'content': 'Driving Up Hill Once you have determi...","To drive downhill, follow these steps:\n1. Determine if the hill is too stee...",0.2619,0.5000,-0.2381,0.2619,0.5000,-0.2381,1.0000,1.0000,0.0000,1.0,1.0,0.0
18,what can the dimmer controls adjust?,"[{'text': '', 'title': '', 'content': 'Dimmer Control The dimmer control is ...",The dimmer control can adjust the following:\n\n1. Brightness of the instrum...,0.2857,0.5000,-0.2143,0.2143,0.5000,-0.2857,0.7500,1.0000,-0.2500,0.0,1.0,-1.0
19,how to use the key fob to unlock all the doors?,"[{'text': '', 'title': '', 'content': 'To Lock/Unlock The Doors And Tailgate...","To unlock all the doors using the key fob, push and release the unlock butto...",0.2647,0.0312,0.2334,0.0588,0.0312,0.0275,0.2222,1.0000,-0.7778,0.0,1.0,-1.0
20,how to activate the Autostop Mode?,"[{'text': '', 'title': '', 'content': 'To Activate The Autostop Mode, The Fo...","To Activate The Autostop Mode, The Following Must Occur: \n1. The system mus...",NaN,0.4194,NaN,NaN,0.3226,NaN,NaN,0.7692,NaN,NaN,1.0,NaN
21,Can I change the desired speed when the Cruise Control is on?,"[{'text': '', 'title': '', 'content': 'To Set A Desired Speed Turn the Cruis...",The passages do not provide sufficient information to answer this question.,NaN,0.1220,NaN,NaN,0.0976,NaN,NaN,0.8000,NaN,NaN,1.0,NaN
22,how to warm up the engine in cold weather?,"[{'text': '', 'title': '', 'content': 'Engine Warm-Up Avoid full throttle op...",To warm up the engine in cold weather:\n1. Avoid full throttle operation whe...,NaN,0.4194,NaN,NaN,0.3226,NaN,NaN,0.7692,NaN,NaN,1.0,NaN
23,how to do the ignition actuated test?,"[{'text': '', 'title': '', 'content': 'Your vehicle has a simple ignition ac...","To check if your vehicle's OBD II system is ready, you must do the following...",NaN,0.2889,NaN,NaN,0.2667,NaN,NaN,0.9231,NaN,NaN,1.0,NaN
24,Can I deactivate the DRLs?,"[{'text': '', 'title': '', 'content': 'assembly. DRLs are active when the lo...",The passages do not provide sufficient information to answer this question.,NaN,0.2500,NaN,NaN,0.1667,NaN,NaN,0.6667,NaN,NaN,0.0,NaN
25,Any tips about the usage of the windshield washer wiper control lever?,"[{'text': '', 'title': '', 'content': 'WINDSHIELD WIPERS AND WASHERS The win...","To use the windshield washer, follow these steps:\n1. Pull the windshield wi...",NaN,0.3182,NaN,NaN,0.2727,NaN,NaN,0.8571,NaN,NaN,1.0,NaN
26,Can I keep the top folded down for a long time?,"[{'text': '', 'title': '', 'content': 'If the temperature is below 72°F (24°...",The passages do not provide sufficient information to answer this question.,NaN,0.0571,NaN,NaN,0.0714,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
27,Can the passengers remain in the car when the car is jacked up?,"[{'text': '', 'title': '', 'content': 'Passengers should not remain in the v...",Passengers should not remain in the vehicle when the vehicle is being jacked...,NaN,0.0175,NaN,NaN,0.0175,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
28,How can I pull back the tailgate after closing?,"[{'text': '', 'title': '', 'content': 'Closing To close the tailgate, lift u...","To pull back the tailgate after closing, follow these steps:\n1. Close the t...",NaN,0.0667,NaN,NaN,0.1333,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
29,What should I pay attention to for the clutch pedal?,"[{'text': '', 'title': '', 'content': 'Shifting Fully press the clutch pedal...","According to the passages, for the clutch pedal, you should:\n1. Fully press...",NaN,0.2333,NaN,NaN,0.1667,NaN,NaN,0.7143,NaN,NaN,1.0,NaN
30,What are the steps to remove the Tonneau cover?,"[{'text': '', 'title': '', 'content': 'Tonneau Cover Removal To remove the T...","To remove the Tonneau Cover, proceed as follows:\n1. Open the tailgate.\n2. ...",NaN,0.5172,NaN,NaN,0.4138,NaN,NaN,0.8000,NaN,NaN,1.0,NaN
31,How can I activate the heated seat function?,"[{'text': '', 'title': '', 'content': 'Heated Seats — If Equipped The heated...","To activate the heated seat function, press the heated seat button once to t...",NaN,0.1860,NaN,NaN,0.1860,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
32,How can I replace the full doors with half doors?,"[{'text': '', 'title': '', 'content': 'Half-Door Installation To install the...","To replace the full doors with half-doors, proceed as follows: \n1. Remove t...",NaN,0.4576,NaN,NaN,0.4237,NaN,NaN,0.6667,NaN,NaN,1.0,NaN
33,what should I pay attention to when towing the car?,"[{'text': '', 'title': '', 'content': 'Towing Tips Before towing, practice t...","To tow a disabled vehicle, follow these steps:\n\n1. Use only tow bars and o...",NaN,0.3784,NaN,NaN,0.2703,NaN,NaN,0.7143,NaN,NaN,1.0,NaN
34,Are there any requirements for the portable battery booster pack?,"[{'text': '', 'title': '', 'content': 'When using a portable battery booster...","When using a portable battery booster pack, follow the manufacturer's operat...",NaN,0.1277,NaN,NaN,0.1277,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
35,What does ACC mean?,"[{'text': '', 'title': '', 'content': 'Adaptive Cruise Control (ACC) Operati...","The passages do not provide a direct definition of the acronym ""ACC"". Howeve...",NaN,0.2500,NaN,NaN,0.2500,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
36,How to make my steering wheel heated?,"[{'text': '', 'title': '', 'content': 'engine must be running for the heated...","To make your steering wheel heated, follow these steps:\n\n1. Ensure the eng...",NaN,0.4571,NaN,NaN,0.4571,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
37,The ABS Warning Light is on. What should I do?,"[{'text': '', 'title': '', 'content': 'the brake fluid level is low, or that...","If the ABS Warning Light is on, the brake system should be serviced as soon ...",NaN,0.4483,NaN,NaN,0.3103,NaN,NaN,0.6154,NaN,NaN,1.0,NaN
38,What are the default settings for the car?,"[{'text': '', 'title': '', 'content': 'check mark appears next to the settin...",The passages do not provide sufficient information to answer this question.,NaN,0.5714,NaN,NaN,0.3333,NaN,NaN,0.2500,NaN,NaN,1.0,NaN
39,Any tips if I have to drive across an incline?,"[{'text': '', 'title': '', 'content': 'Driving Across An Incline If at all p...","If it is necessary to drive across an incline, follow these steps:\n1. Know ...",NaN,0.3529,NaN,NaN,0.2353,NaN,NaN,0.6667,NaN,NaN,1.0,NaN
40,what does NHTSA stand for?,"[{'text': '', 'title': '', 'content': 'To contact nhtsa, you may call the ve...",The passages do not provide a direct definition of what NHTSA stands for. Ho...,NaN,0.1250,NaN,NaN,0.1250,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
41,What is CO?,"[{'text': '', 'title': '', 'content': 'Carbon Monoxide Warnings WARNING: Car...","According to the passages, CO is carbon monoxide, a colorless and odorless g...",NaN,0.2407,NaN,NaN,0.1852,NaN,NaN,0.6154,NaN,NaN,1.0,NaN
42,What to interrupt a voice response?,"[{'text': '', 'title': '', 'content': 'category. “ cancel ” to stop a curren...","To interrupt the help message or system prompts, push the VR button and say ...",NaN,0.0606,NaN,NaN,0.0606,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
43,how to activate the Uconnect voice recognition system?,"[{'text': '', 'title': '', 'content': 'Basic Voice Commands The following ba...","To activate the Uconnect Voice Recognition system, follow these steps:\n1. P...",NaN,0.1429,NaN,NaN,0.1429,NaN,NaN,0.3333,NaN,NaN,1.0,NaN
44,Any tips for off-road driving?,"[{'text': '', 'title': '', 'content': 'Off-Road Driving Tips', 'metadata': {...","To drive off-road, follow these steps:\n1. Be familiar with the terrain and ...",NaN,0.5854,NaN,NaN,0.5610,NaN,NaN,0.9167,NaN,NaN,1.0,NaN
45,what should I do to prevent fuel system trouble?,"[{'text': '', 'title': '', 'content': 'fuel system or emission control syste...","To prevent fuel system trouble, follow these steps:\n\n1. Use the correct fu...",NaN,0.1000,NaN,NaN,0.0800,NaN,NaN,0.8000,NaN,NaN,1.0,NaN
46,what should I pay attention to when shifting out of NEUTRAL?,"[{'text': '', 'title': '', 'content': 'NEUTRAL (N) Use this range when the v...","To shift out of NEUTRAL, follow these steps from Document 2: \n1. Bring the ...",NaN,0.4706,NaN,NaN,0.2059,NaN,NaN,0.4375,NaN,NaN,1.0,NaN
47,What can the Cruise Control system do?,"[{'text': '', 'title': '', 'content': 'Cruise Control can be dangerous where...",The Cruise Control system will keep your vehicle at a constant preset speed....,NaN,0.1515,NaN,NaN,0.1515,NaN,NaN,0.8000,NaN,NaN,1.0,NaN
48,Can you tell me instructions about how to reset the Manual Park Release?,"[{'text': '', 'title': '', 'content': 'the vehicle is securely connected to ...","To Reset The Manual Park Release: \n1. Pull upward on the tether strap, rele...",NaN,0.0769,NaN,NaN,0.0769,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
49,The temperature gauge is pointing to H and the car is continuously chiming. ...,"[{'text': '', 'title': '', 'content': '“H,” pull over and stop the vehicle. ...","If the temperature gauge reads ""H"" and you hear continuous chimes, follow th...",NaN,0.1618,NaN,NaN,0.1618,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
50,How to properly re-install the carpets in the car?,"[{'text': '', 'title': '', 'content': 'with the accelerator, brake, or clutc...","To properly re-install the carpets in the car, perform the following steps i...",NaN,0.4231,NaN,NaN,0.4231,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
51,What information do the Off-Road Pages provide?,"[{'text': '', 'title': '', 'content': 'OFF-ROAD PAGES — IF EQUIPPED If your ...","To access the information provided by the Off-Road Pages, press the Apps but...",NaN,0.3333,NaN,NaN,0.3333,NaN,NaN,1.0000,NaN,NaN,1.0,NaN
52,what should I do before sending the car to the emission inspection?,"[{'text': '', 'title': '', 'content': 'In some localities, it may be a legal...",To check if your vehicle's OBD II system is ready for the emission inspectio...,NaN,0.2642,NaN,NaN,0.2642,NaN,NaN,1.0000,NaN,NaN,1.0,NaN

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.2979,0.2490,0.1810,0.1663,0.1954
1,utilization_score,0.2374,0.2151,0.1668,0.1422,0.1781
2,completeness_score,0.6330,0.8423,0.3312,0.2132,0.3524
3,adherence_score,0.1579,0.9811,0.3646,0.1361,0.8421

None

================================================================================
Configuration: delucionqa_or_v3_embed_bge
================================================================================

Per-Query Results:

# RAG Multi-Config Evaluation Report

_Strategy: detailed_query_

## Config: `delucionqa_or_v3_embed_bge`

**name**: delucionqa_or_v3_embed_bge  •  **mode**: test  •  **providers**: {'openrouter': {'type': 'openrouter', 'api_key_env': 'OPENROUTER_API_KEY', 'params': {'cooldown_seconds': 60}}}  •  **chunking**: {'type': 'fixed_word', 'config': {'max_words': 160, 'overlap_words': 24}}  •  **embedding**: {'type': 'sentence_transformer', 'config': {'model_name': 'BAAI/bge-base-en-v1.5', 'dimension': 768}}  •  **vector_store**: {'type': 'faiss', 'config': {'dimension': 768}}  •  **retrieval**: {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 5}}]}, 'query_transform': None, 'fusion': None, 'rerank': None}  •  **generation**: {'strategy': 'default', 'provider': 'openrouter', 'config': {'model': 'meta-llama/llama-3.3-70b-instruct', 'temperature': 0.0, 'max_tokens': 512, 'system_prompt': 'You are an automotive owner\'s-manual support assistant. Answer questions\nabout vehicle features, controls, and procedures using ONLY the provided\nowner\'s-manual passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use outside knowledge.\n2. Give exact, step-by-step procedures. Preserve exact control names, button\n   names, warning/CAUTION text, and feature labels verbatim.\n3. Include any safety warnings (WARNING/CAUTION) that the passages attach to\n   the procedure.\n4. Be concise and procedural - give the steps, not background.\n5. If the passages do not contain the answer, respond with exactly:\n   "The passages do not provide sufficient information to answer this question."\n6. Every claim must be directly supported by the passages provided.\n', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, give exact steps, control names, and any safety warnings):\n'}}  •  **evaluation**: {'type': 'trace', 'provider': 'openrouter', 'config': {'model': 'meta-llama/llama-3.3-70b-instruct', 'temperature': 0.0, 'max_tokens': 2000}}  •  **cache**: {'enabled': True, 'cache_dir': './cache_openrouter_delucionqa'}  •  **start_index**: None  •  **end_index**: None  •  **logging_config**: {'enabled': True, 'level': 'INFO', 'show_progress': True}

### Per-query results

,query,retrieved_documents,answer,relevance_score__pred,relevance_score__gt,relevance_score__deviation,utilization_score__pred,utilization_score__gt,utilization_score__deviation,completeness_score__pred,completeness_score__gt,completeness_score__deviation,adherence_score__pred,adherence_score__gt,adherence_score__deviation
0,What if I fail to latch the tailgate properly?,"[{'text': '', 'title': '', 'content': 'Closing To close the tailgate, lift u...",Failure to securely latch the tailgate could result in damage to the vehicle...,0.3333,0.1111,0.2222,0.2333,0.1111,0.1222,0.6000,1.0000,-0.4000,0.0,1.0,-1.0
1,What kind of safety features are implemented in this car?,"[{'text': '', 'title': '', 'content': 'SAFETY FEATURES When the Safety/Drivi...",The passages mention the following safety features:\n\n1. Occupant Restraint...,0.3077,0.2500,0.0577,0.5385,0.2500,0.2885,0.6250,1.0000,-0.3750,0.0,1.0,-1.0
2,When will the Automatic SOS be triggered?,"[{'text': '', 'title': '', 'content': 'Automatic SOS — If Equipped Automatic...",The passages do not provide sufficient information to answer this question.,0.0303,0.0244,0.0059,0.0000,0.0244,-0.0244,0.0000,1.0000,-1.0000,1.0,1.0,0.0
3,What happens if I accidentally push the SOS Call button?,"[{'text': '', 'title': '', 'content': 'Connected Services SOS FAQs — If Equi...","If you accidentally push the SOS Call button, you have 10 seconds to cancel ...",0.2857,0.0820,0.2037,0.2000,0.0656,0.1344,0.4000,0.8000,-0.4000,0.0,1.0,-1.0
4,What is the DEF?,"[{'text': '', 'title': '', 'content': 'Adding Diesel Exhaust Fluid The DEF g...","The passages do not provide a direct definition of DEF. However, according t...",0.7778,0.0625,0.7153,0.3889,0.0625,0.3264,0.5000,1.0000,-0.5000,0.0,1.0,-1.0
5,What may cause erratic or noisy performance of the radio?,"[{'text': '', 'title': '', 'content': 'Under certain conditions, the mobile ...",The mobile phone being on in your vehicle can cause erratic or noisy perform...,0.4211,0.1143,0.3068,0.4211,0.1143,0.3068,1.0000,1.0000,0.0000,1.0,1.0,0.0
6,how to calculate the gross trailer weight?,"[{'text': '', 'title': '', 'content': 'Gross Trailer Weight (GTW) The GTW is...","To calculate the Gross Trailer Weight (GTW), follow these steps:\n\n1. Put y...",0.1579,0.2727,-0.1148,0.2105,0.2727,-0.0622,1.0000,1.0000,0.0000,0.0,1.0,-1.0
7,What can the ASIST button do?,"[{'text': '', 'title': '', 'content': 'If equipped, the ASSIST Button is use...",The ASSIST button is used to automatically connect you to any one of the fol...,0.1522,0.4348,-0.2826,0.2174,0.4348,-0.2174,0.8571,1.0000,-0.1429,0.0,1.0,-1.0
8,What does the Door Off Mirror Kit do?,"[{'text': '', 'title': '', 'content': 'For information on the Door Off Mirro...",The Door Off Mirror Kit allows exterior rearview mirrors to be installed ont...,0.4400,0.1304,0.3096,0.4400,0.1304,0.3096,0.6364,1.0000,-0.3636,0.0,1.0,-1.0
9,Can I manually activate or deactivate the air conditioner?,"[{'text': '', 'title': '', 'content': 'The Air Conditioning (A/C) button all...","To manually activate or deactivate the air conditioner, press and release th...",0.2000,0.0811,0.1189,0.3429,0.1351,0.2078,0.8571,0.6667,0.1904,0.0,1.0,-1.0
10,what does the The cartridge block heater do?,"[{'text': '', 'title': '', 'content': 'The cartridge block heater clips into...",The cartridge block heater clips into the engine block near the water jacket...,0.3000,0.0492,0.2508,0.3400,0.0492,0.2908,1.0000,1.0000,0.0000,0.0,1.0,-1.0
11,When will the illuminated entry system be activated?,"[{'text': '', 'title': '', 'content': 'When any of these situations occur, a...",The passages do not provide sufficient information to answer this question.,0.2424,0.0541,0.1883,0.0000,0.0811,-0.0811,0.0000,1.0000,-1.0000,1.0,1.0,0.0
12,"If the light remains on after the bulb check, it indicates what problem?","[{'text': '', 'title': '', 'content': 'If the Brake System Warning Light rem...","According to Document 2, if the Air Bag Warning Light ""stays on"" after the b...",0.3438,0.1042,0.2396,0.0625,0.0208,0.0417,0.1818,0.2000,-0.0182,0.0,1.0,-1.0
13,What is special about power windows?,"[{'text': '', 'title': '', 'content': 'The power windows feature allows for ...",The power windows feature allows for movement of the windows with the push o...,0.3810,0.2759,0.1051,0.3333,0.1379,0.1954,0.8125,0.5000,0.3125,1.0,1.0,0.0
14,What should I do to jump start the car?,"[{'text': '', 'title': '', 'content': 'of the engine compartment. If your ve...","To jump start the car, follow these steps: \n1. Apply the parking brake, \n2...",0.8810,0.4127,0.4683,0.6429,0.2063,0.4366,0.7297,0.5000,0.2297,0.0,1.0,-1.0
15,How to deactivate the cruise control?,"[{'text': '', 'title': '', 'content': 'When ACC is deactivated, the display ...","To deactivate the Cruise Control, follow these steps:\n1. A soft tap on the ...",0.2692,0.4667,-0.1975,0.3462,0.4667,-0.1205,0.7143,0.8571,-0.1428,0.0,1.0,-1.0
16,Is it safe for me to park the vehicle in somewhere very hot?,"[{'text': '', 'title': '', 'content': 'driving in hot weather, up mountain g...",WARNING: Do not leave children or animals inside parked vehicles in hot weat...,0.5800,0.1622,0.4178,0.3000,0.1892,0.1108,0.5172,1.0000,-0.4828,0.0,1.0,-1.0
17,Any tips for driving downhill?,"[{'text': '', 'title': '', 'content': 'Off-Road Driving Tips', 'metadata': {...","To drive downhill, follow these steps:\n1. Determine if the hill is too stee...",0.5366,0.5000,0.0366,0.5366,0.5000,0.0366,0.8182,1.0000,-0.1818,0.0,1.0,-1.0
18,what can the dimmer controls adjust?,"[{'text': '', 'title': '', 'content': 'Dimmer Control The dimmer control is ...",The dimmer control can adjust the following:\n\n1. Brightness of the instrum...,0.2857,0.5000,-0.2143,0.2857,0.5000,-0.2143,1.0000,1.0000,0.0000,1.0,1.0,0.0
19,how to use the key fob to unlock all the doors?,"[{'text': '', 'title': '', 'content': 'To Lock/Unlock The Doors And Tailgate...","To unlock all the doors using the key fob, push and release the unlock butto...",0.1333,0.0312,0.1021,0.0667,0.0312,0.0354,0.5000,1.0000,-0.5000,0.0,1.0,-1.0

### Aggregate TRACe scores (mean / ground truth / deviation)

,metric,mean_score,mean_ground_truth,std_score,std_ground_truth,mean_abs_error
0,relevance_score,0.3530,0.2060,0.2056,0.1651,0.2279
1,utilization_score,0.2953,0.1892,0.1731,0.1589,0.1781
2,completeness_score,0.6375,0.8762,0.3025,0.2242,0.3120
3,adherence_score,0.2500,1.0000,0.4330,0.0000,0.7500

None

## 10. Compare Configurations

Generate a comparison report across all configurations to see which performs best.

In [23]:
# Generate comparison report
print("Generating comparison report...")
comparison = runner.compare()

print(f"\n✅ Comparison report generated!")
print(f"  Saved to: {experiment_config.report_dir}/comparison.csv")

Generating comparison report...

✅ Comparison report generated!
  Saved to: rag-experiments/delucionqa-openrouter-experiment/reports/comparison.csv

In [24]:
# Display comparison
print("\nConfiguration Comparison:")
display(comparison.to_dataframe())

Configuration Comparison:

,config_name,relevance_score__mean,relevance_score__mae,utilization_score__mean,utilization_score__mae,completeness_score__mean,completeness_score__mae,adherence_score__mean,adherence_score__mae
0,delucionqa_or_v5_hybrid_rrf,0.1650,0.1236,0.1582,0.1069,0.7387,0.2826,0.1053,0.8947
1,delucionqa_or_v9_bge_sentence,0.2746,0.1700,0.2538,0.1555,0.6430,0.3026,0.2105,0.7895
2,delucionqa_or_v1_baseline,0.2979,0.1954,0.2374,0.1781,0.6330,0.3524,0.1579,0.8421
3,delucionqa_or_v3_embed_bge,0.3530,0.2279,0.2953,0.1781,0.6375,0.3120,0.2500,0.7500
4,delucionqa_or_v2_hybrid_wsum,0.1879,0.1545,0.1482,0.1172,0.6217,0.3709,0.1000,0.9000
5,delucionqa_or_v6_rerank_only,0.3494,0.1668,0.2861,0.1650,0.5997,0.3544,0.2000,0.8000
6,delucionqa_or_v7_hybrid_rerank,0.3639,0.1895,0.2622,0.1296,0.6291,0.2959,0.2500,0.7500
7,delucionqa_or_v4_chunk_sentence,0.4028,0.2419,0.2760,0.1647,0.5575,0.4034,0.2500,0.7500
8,delucionqa_or_v8_hyde,0.3707,0.1976,0.2692,0.1518,0.5349,0.3867,0.2500,0.7500

## 11. Summary

The ExperimentRunner provides a complete workflow for:

1. **Configuration-driven data loading** - Specify data source in YAML
2. **Automatic parsing** - Documents parsed using configured parser
3. **Multi-config evaluation** - Test multiple RAG configurations
4. **Parallel execution** - Speed up evaluation with parallel runs
5. **Comprehensive reporting** - Per-query and aggregate metrics
6. **Cross-config comparison** - Identify best performing config

### Key Benefits:

- **Reproducible** - Everything configured in YAML
- **Flexible** - Easy to change data source or parser
- **Scalable** - Parallel execution for faster evaluation
- **Comprehensive** - Detailed metrics and comparisons