# Production RAG Pipeline — Colab, Self-Contained (`gemma-4-26b-a4b-it` via Modal)

Self-contained Colab version of `production_pipeline_demo.ipynb`, validating the
**same winning retrieval recipe** from the original ablation sweep — dense-only
FAISS retrieval, `sentence-transformers/all-MiniLM-L6-v2`, per-dataset fixed-word
chunking, `top_k=5`, no reranking/fusion/query-transform — across all three
customer-support subsets (`techqa` / `emanual` / `delucionqa`) of
`galileo-ai/ragbench`, but with a single new generator+judge model:
**`gemma-4-26b-a4b-it`**, served from your own Modal endpoint.

**What's different from `production_pipeline_demo.ipynb`:** that notebook loads
its per-dataset RAG config from `experiment_configs/{dataset}_production_experiment.yaml`
*plus* `rag-experiments/{dataset}-production/config/*.yaml` — two separate files
you'd have to hand-edit to change the model/provider. Here, **section 5 below is
the only config** — one Python dict per dataset — and this notebook writes the
YAML the framework expects at runtime. Nothing to open or edit outside this file.

**What's reused unchanged:** the actual `rag_cust_support` framework code
(chunking/embedding/FAISS/TRACe-judge implementations) — this notebook mounts
your Drive copy of the repo and imports it, exactly like the original notebook
does, so none of that logic is reimplemented or duplicated here.

**Provider plumbing:** `gemma-4-26b-a4b-it` is not a new provider class — the
existing `openrouter` provider is already a generic OpenAI-compatible client
(reads `base_url` from its config), so it's just registered under the name
`modal` pointed at your Modal endpoint. Same model/provider is used for both
generation and the TRACe judge (no fallback provider — if Modal is down, the
run fails loudly rather than silently switching models).

**Isolated output dirs** (`rag-experiments/{dataset}-production-colab-gemma/`,
`cache_production_colab_gemma_{dataset}/`) so this never collides with the
existing OpenRouter/Llama production run's history or cache.

## 1. Setup — mount Drive & install dependencies

Mounting Drive (not `git clone`) because `rag_cust_support` is a private GitHub
repo — this matches how `production_pipeline_demo.ipynb` already does it, so no
extra GitHub-token secret is needed. If you'd rather clone directly, swap this
cell for `git clone https://<token>@github.com/bhupendra-bhoi/rag_cust_support.git`
using a token stored in Colab Secrets.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

get_ipython().system('pip install -q datasets faiss-cpu sentence-transformers torch groq openai pyyaml pandas rank_bm25 nltk')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## 2. Point at the repo + imports

In [ ]:
import sys
import os
import yaml
from pathlib import Path

# --- Point this at wherever the rag_cust_support repo lives in YOUR Drive. ---
PROJECT_ROOT = Path('/content/drive/MyDrive/Capstone/rag_cust_support')
assert PROJECT_ROOT.exists(), f'{PROJECT_ROOT} not found — update this path to your Drive copy of the repo.'

os.chdir(PROJECT_ROOT)
project_root = PROJECT_ROOT
# Make THIS repo win on sys.path (avoids importing a stale rag-foundry copy).
sys.path = [p for p in sys.path if 'rag-foundry' not in p]
if str(project_root) in sys.path:
    sys.path.remove(str(project_root))
sys.path.insert(0, str(project_root))

from experiment.experiment_config import ExperimentConfig
from experiment.experiment_runner import ExperimentRunner
from providers.config import ProviderConfig
from providers.provider_manager import ProviderManager
import experiment.experiment_runner as _er

print('Current directory:', Path.cwd())
print('experiment_runner loaded from:', _er.__file__)
assert 'rag-foundry' not in _er.__file__, 'Still importing the old rag-foundry code! Restart runtime.'

Current directory: /content/drive/MyDrive/Capstone/rag_cust_support
experiment_runner loaded from: /content/drive/MyDrive/Capstone/rag_cust_support/experiment/experiment_runner.py

## 3. Secrets — Modal endpoint for `gemma-4-26b-a4b-it`

Add both to the Colab **Secrets** tab (key icon in the left sidebar) and grant
this notebook access: `MODAL_BASE_URL` (your deployed endpoint's OpenAI-compatible
base URL, e.g. `https://<workspace>--<app-name>.modal.run/v1`) and
`MODAL_PROXY_KEY` (your Modal proxy key).

In [ ]:
from google.colab import userdata

MODAL_BASE_URL = userdata.get('MODAL_BASE_URL')
os.environ['MODAL_PROXY_KEY'] = userdata.get('MODAL_PROXY_KEY')

print('MODAL_BASE_URL loaded:', bool(MODAL_BASE_URL))
print('MODAL_PROXY_KEY loaded:', bool(os.environ.get('MODAL_PROXY_KEY')))

MODAL_BASE_URL loaded: True
MODAL_PROXY_KEY loaded: True

## 4. Sanity check — confirm the endpoint responds before spending on the full run

Registers the `modal` provider and sends one trivial no-context query. Catches a
wrong `MODAL_BASE_URL`/`MODAL_PROXY_KEY` or a cold/misconfigured endpoint here,
instead of partway through a long checkpointed pipeline run.

In [ ]:
MODEL_NAME = 'gemma-4-26b-a4b-it'  # <-- exact model id your Modal deployment expects

_sanity_provider_config = ProviderConfig(
    type='openai',
    api_key_env='MODAL_PROXY_KEY',
    params={'base_url': MODAL_BASE_URL, 'cooldown_seconds': 60},
)
ProviderManager.register('modal', _sanity_provider_config.type, _sanity_provider_config)

_resp = ProviderManager.get_provider('modal').generate(
    model=MODEL_NAME,
    messages=[{'role': 'user', 'content': 'Reply with just the word OK.'}],
    temperature=0.0, max_tokens=10,
)
_text = _resp.choices[0].message.content.strip()
print('[OK] modal endpoint responded:', repr(_text)) if _text else print('[EMPTY] modal endpoint returned no text — check MODAL_BASE_URL/MODEL_NAME')

Using key #0: ****kv8w
[OK] modal endpoint responded: 'OK'

## 5. The ONE config cell — per-dataset chunking + prompts

This replaces both external YAML files from the original notebook. Everything
you might want to tweak (chunk size, prompts, token budgets, sample count) lives
right here — edit this cell, not a file elsewhere. Retrieval settings (dense-only,
`all-MiniLM-L6-v2`, `top_k=5`) are the winning config from the original ablation
sweep and are intentionally the same for all three datasets; only chunk size and
the generation prompt are dataset-specific, exactly as in `production/configs/*.yaml`.

In [ ]:
END_INDEX = 20  # rows per dataset; raise up to each dataset's full test-split size
                # once you're ready — runs are checkpoint-resumable, so raising
                # this later re-costs nothing already completed.

DATASET_SETTINGS = {
    'techqa': {
        'limit': 314,
        'max_words': 200, 'overlap_words': 20,
        'max_tokens': 750,
        'system_prompt': (
            'You are an IBM technical-support question answering assistant.\n'
            'Your task is to answer questions using ONLY information from the retrieved\n'
            'technote passages.\n\n'
            'CRITICAL RULES:\n'
            '1. Answer ONLY from the passages provided. Do not use external knowledge.\n'
            '2. Include all relevant steps, error codes, product versions, APAR numbers,\n'
            '   and configuration details found in the passages.\n'
            '3. Preserve exact technical identifiers (version strings, file names,\n'
            '   parameter names, error messages) verbatim.\n'
            '4. Do NOT add phrases like "based on general knowledge" or hedge unnecessarily.\n'
            '5. If the passages do not contain enough information, respond with exactly:\n'
            '   "The passages do not provide sufficient information to answer this question."\n'
            '6. Every claim must be directly supported by the passages provided.'
        ),
        'user_prompt': (
            'Passages:\n{context}\n\n'
            'Question: {query}\n\n'
            'Answer (from passages only, include all relevant steps and technical details):'
        ),
    },
    'emanual': {
        'limit': 132,
        'max_words': 128, 'overlap_words': 20,
        'max_tokens': 512,
        'system_prompt': (
            'You are a consumer-electronics product-support assistant. Answer questions\n'
            'about device features and settings using ONLY the provided user-manual passages.\n\n'
            'CRITICAL RULES:\n'
            '1. Answer ONLY from the passages provided. Do not use outside knowledge.\n'
            '2. Give exact, step-by-step instructions. Preserve menu paths, button names,\n'
            '   setting names, and on-screen labels verbatim\n'
            '   (e.g. "Settings > Support > Self Diagnosis > Signal Information").\n'
            '3. Be concise and procedural - give the steps, not background.\n'
            '4. If the passages do not contain the answer, respond with exactly:\n'
            '   "The passages do not provide sufficient information to answer this question."\n'
            '5. Every step must be directly supported by the passages provided.'
        ),
        'user_prompt': (
            'Passages:\n{context}\n\n'
            'Question: {query}\n\n'
            'Answer (from passages only, give exact steps and menu paths):'
        ),
    },
    'delucionqa': {
        'limit': 184,
        'max_words': 160, 'overlap_words': 24,
        'max_tokens': 512,
        'system_prompt': (
            'You are an automotive owner\'s-manual support assistant. Answer questions\n'
            'about vehicle features, controls, and procedures using ONLY the provided\n'
            'owner\'s-manual passages.\n\n'
            'CRITICAL RULES:\n'
            '1. Answer ONLY from the passages provided. Do not use outside knowledge.\n'
            '2. Give exact, step-by-step procedures. Preserve exact control names, button\n'
            '   names, warning/CAUTION text, and feature labels verbatim.\n'
            '3. Include any safety warnings (WARNING/CAUTION) that the passages attach to\n'
            '   the procedure.\n'
            '4. Be concise and procedural - give the steps, not background.\n'
            '5. If the passages do not contain the answer, respond with exactly:\n'
            '   "The passages do not provide sufficient information to answer this question."\n'
            '6. Every claim must be directly supported by the passages provided.'
        ),
        'user_prompt': (
            'Passages:\n{context}\n\n'
            'Question: {query}\n\n'
            'Answer (from passages only, give exact steps, control names, and any safety warnings):'
        ),
    },
}

def build_rag_config(dataset):
    """Inner RAGConfig dict — dense-only retrieval + gemma-4-26b-a4b-it via Modal."""
    s = DATASET_SETTINGS[dataset]
    return {
        'mode': 'dev',
        'name': f'{dataset}_production_colab_gemma',
        'cache': {'enabled': True, 'cache_dir': f'./cache_production_colab_gemma_{dataset}'},
        'providers': {
            'modal': {
                'type': 'openai',
                'api_key_env': 'MODAL_PROXY_KEY',
                'params': {'base_url': MODAL_BASE_URL, 'cooldown_seconds': 60},
            },
        },
        'chunking': {
            'type': 'fixed_word',
            'config': {'max_words': s['max_words'], 'overlap_words': s['overlap_words']},
        },
        'embedding': {
            'type': 'sentence_transformer',
            'config': {'model_name': 'sentence-transformers/all-MiniLM-L6-v2', 'dimension': 384},
        },
        'vector_store': {'type': 'faiss', 'config': {'dimension': 384}},
        'retrieval': {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 5}}]}},
        'generation': {
            'strategy': 'default',
            'provider': 'modal',
            'config': {
                'model': MODEL_NAME,
                'temperature': 0.0,
                'max_tokens': s['max_tokens'],
                'system_prompt': s['system_prompt'],
                'user_prompt': s['user_prompt'],
            },
        },
        'evaluation': {
            'type': 'trace',
            'provider': 'modal',
            'config': {'model': MODEL_NAME, 'temperature': 0.0, 'max_tokens': 2000},
        },
    }

## 6. Build isolated experiment dirs + run

For each dataset: write the config from section 5 into a fresh, isolated
`config/` dir (this is the step that used to require hand-editing a YAML file —
here it's generated fresh from the dict above every run), then run the same
`ExperimentRunner` flow as the original notebook (load data → run pipeline →
evaluate with the TRACe judge → generate report).

In [ ]:
DATASETS = ['techqa', 'emanual', 'delucionqa']

runners = {}
reports = {}

for dataset in DATASETS:
    print(f'\n{"="*80}\n{dataset.upper()} — production config (Colab, gemma-4-26b-a4b-it)\n{"="*80}')

    exp_root = project_root / 'rag-experiments' / f'{dataset}-production-colab-gemma'
    config_dir = exp_root / 'config'
    config_dir.mkdir(parents=True, exist_ok=True)
    # Fresh config every run — this is the file that replaces manual YAML editing.
    with open(config_dir / f'{dataset}_production_colab_gemma.yaml', 'w') as f:
        yaml.safe_dump(build_rag_config(dataset), f, sort_keys=False)

    experiment_config = ExperimentConfig(
        config_dir=config_dir,
        report_dir=exp_root / 'reports',
        temp_dir=exp_root / 'temp',
        start_index=0,
        end_index=END_INDEX,
        cache={'enabled': True, 'cache_dir': f'./cache_production_colab_gemma_{dataset}'},
        data_loader={
            'type': 'huggingface',
            'config': {
                'dataset_name': 'galileo-ai/ragbench',
                'subset': dataset,
                'split': 'test',
                'limit': DATASET_SETTINGS[dataset]['limit'],
            },
        },
        data_parser='noop',
        evaluation={
            'type': 'trace',
            'provider': 'modal',
            'config': {'model': MODEL_NAME, 'temperature': 0.0, 'max_tokens': 2000},
        },
    )
    runner = ExperimentRunner(experiment_config)
    runners[dataset] = runner

    documents, raw_data = runner.load_data()
    print(f'Loaded {len(raw_data)} raw rows -> {len(documents)} parsed documents')

    configs = runner.load_configs()
    assert len(configs) == 1, f'Expected exactly 1 config for {dataset}, found {len(configs)}'
    print(f'Running config: {configs[0].name}')

    runs = runner.run(documents, raw_data)
    runs = runner.evaluate_runs(runs)
    reports[dataset] = runner.generate_reports(runs)

================================================================================
TECHQA — production config (Colab, gemma-4-26b-a4b-it)
================================================================================
Loading HuggingFace dataset: galileo-ai/ragbench/techqa (test)...
Loaded 314 samples
Loaded 314 raw rows -> 1570 parsed documents
Running config: techqa_production_colab_gemma
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 0sUsing key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 3sUsing key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Progress: 5/20 (25.0%) | QPS: 1.25 | ETA: 12s | Elapsed: 4sUsing key #0: ****kv8w
Progress: 6/20 (30.0%) | QPS: 1.00 | ETA: 14s | Elapsed: 6sUsing key #0: ****kv8w
Progress: 7/20 (35.0%) | QPS: 0.87 | ETA: 15s | Elapsed: 8sUsing key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Progress: 12/20 (60.0%) | QPS: 1.33 | ETA: 6s | Elapsed: 9sUsing key #0: ****kv8w
Using key #0: ****kv8w
Progress: 14/20 (70.0%) | QPS: 1.40 | ETA: 4s | Elapsed: 10sUsing key #0: ****kv8w
Progress: 15/20 (75.0%) | QPS: 1.36 | ETA: 4s | Elapsed: 11sUsing key #0: ****kv8w
Progress: 20/20 (100.0%) | QPS: 1.43 | ETA: 0s | Elapsed: 14s
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
[techqa_production_colab_gemma] Evaluation complete → /content/drive/MyDrive/Capstone/rag_cust_support/rag-experiments/techqa-production-colab-gemma/temp/techqa_production_colab_gemma.jsonl

================================================================================
EMANUAL — production config (Colab, gemma-4-26b-a4b-it)
================================================================================
Loading HuggingFace dataset: galileo-ai/ragbench/emanual (test)...
Loaded 132 samples
Loaded 132 raw rows -> 396 parsed documents
Running config: emanual_production_colab_gemma
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 0sUsing key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Progress: 3/20 (15.0%) | QPS: 2.99 | ETA: 6s | Elapsed: 1sUsing key #0: ****kv8w
Progress: 4/20 (20.0%) | QPS: 2.00 | ETA: 8s | Elapsed: 2sUsing key #0: ****kv8w
Progress: 5/20 (25.0%) | QPS: 1.66 | ETA: 9s | Elapsed: 3sUsing key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Progress: 11/20 (55.0%) | QPS: 2.75 | ETA: 3s | Elapsed: 4sUsing key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Progress: 20/20 (100.0%) | QPS: 3.33 | ETA: 0s | Elapsed: 6s
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
[emanual_production_colab_gemma] Evaluation complete → /content/drive/MyDrive/Capstone/rag_cust_support/rag-experiments/emanual-production-colab-gemma/temp/emanual_production_colab_gemma.jsonl

================================================================================
DELUCIONQA — production config (Colab, gemma-4-26b-a4b-it)
================================================================================
Loading HuggingFace dataset: galileo-ai/ragbench/delucionqa (test)...
Loaded 184 samples
Loaded 184 raw rows -> 552 parsed documents
Running config: delucionqa_production_colab_gemma
Progress: 0/20 (0.0%) | QPS: 0.00 | ETA: Unknown | Elapsed: 0sUsing key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Progress: 4/20 (20.0%) | QPS: 3.99 | ETA: 4s | Elapsed: 1sUsing key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Progress: 9/20 (45.0%) | QPS: 4.49 | ETA: 2s | Elapsed: 2sUsing key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Progress: 14/20 (70.0%) | QPS: 4.66 | ETA: 1s | Elapsed: 3sUsing key #0: ****kv8w
Using key #0: ****kv8w
Progress: 20/20 (100.0%) | QPS: 3.99 | ETA: 0s | Elapsed: 5s
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w

WARNING:evaluation.runner:Record 15 evaluation failed: Expecting ',' delimiter: line 218 column 6 (char 5714)

Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
Using key #0: ****kv8w
[delucionqa_production_colab_gemma] Evaluation complete → /content/drive/MyDrive/Capstone/rag_cust_support/rag-experiments/delucionqa-production-colab-gemma/temp/delucionqa_production_colab_gemma.jsonl

In [ ]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 80)

for dataset in DATASETS:
    print(f'\n{"="*80}\n{dataset.upper()}\n{"="*80}')
    print(f'Raw reports for {dataset}: {reports.get(dataset, "No report found")}')
    try:
        comparison = runners[dataset].compare()
        display(comparison.to_dataframe())
    except Exception as e:
        print(f'Error generating comparison for {dataset}: {e}')

================================================================================
TECHQA
================================================================================
Raw reports for techqa: [Report(title='RAG Multi-Config Evaluation Report', strategy_name='detailed_query', sections=[ReportSection(config_name='techqa_production_colab_gemma', per_query=                                                                              query  \
0   Using cobol copybooks Sometimes, there will be errors/fields missing in type...
1   Is WebSphere Transformation Extender (WTX) supported for IBM Integration Bus...
2   Want to find out if Microsoft Edge is supported with ICC? Want to find out M...
3   What IBM Business Process Manager version is affected by the Apache Commons ...
4   Error while installing SpSS modeler trial version I have downloaded the SPSS...
5   Where can I find more details about WMB Fix Pack 8.0.0.5? Where can find mor...
6   How to resolve the StaleConnectionException in WebSphere Application Server?...
7   How do I resolve a WSVR0605W hung thread issue in the WebSphere MQ Resource ...
8   I need to transfer my SPSS 24 licence to a new computer I need to transfer m...
9   How can I export a private key from DataPower Gateway Appliance? \n\nHow can...
10  When should I use conversation sharing in DataPower MQ queue managers? MQ ve...
11  Help with Security Bulletin: IBM WebSphere MQ Administration command could c...
12  Help with Security Bulletin: IIB is affected by Node.js security vulnerabili...
13  Help with Security Bulletin: Multiple vulnerabilities in IBM Java SDK affect...
14  Error #2070 I purchased the SPSS grad pack and put one of the licenses on on...
15  Where I can get ITNM 4.2.0.1 GA version download details with Part number?. ...
16  Help with Action required for IIB H.E.V9 and WMB H.E. V8 for security vulner...
17  Help with Security Bulletin: IBM WebSphere MQ is affected by a privilege esc...
18  What's the procedure to drop an user in Cognos Disclosure Management? \n\nO....
19  What things are important to consider when installing a fix pack for IIB run...

                                                                retrieved_documents  \
0   [{'text': '', 'title': '', 'content': 'TECHNOTE (TROUBLESHOOTING) PROBLEM(AB...
1   [{'text': '', 'title': '', 'content': '8.4.0.2; WTX 8.4.0.2; 8.3.2; HIPAA 4....
2   [{'text': '', 'title': '', 'content': 'ICC 4.0.1 prerequisites. http://www-0...
3   [{'text': '', 'title': '', 'content': 'SECURITY BULLETIN SUMMARY There are m...
4   [{'text': '', 'title': '', 'content': 'TECHNOTE (TROUBLESHOOTING) PROBLEM(AB...
5   [{'text': '', 'title': '', 'content': 'http://www.ibm.com/support/fixcentral...
6   [{'text': '', 'title': '', 'content': 'Stale Connection Exception; StaleConn...
7   [{'text': '', 'title': '', 'content': 'about using the WebSphere MQ messagin...
8   [{'text': '', 'title': '', 'content': 'product key authorization license TEC...
9   [{'text': '', 'title': '', 'content': 'TECHNOTE (FAQ) QUESTION How do I expo...
10  [{'text': '', 'title': '', 'content': 'TECHNOTE (TROUBLESHOOTING) PROBLEM(AB...
11  [{'text': '', 'title': '', 'content': 'SECURITY BULLETIN SUMMARY WebSphere M...
12  [{'text': '', 'title': '', 'content': 'node.js; nodejs; vulnerable; vulnerab...
13  [{'text': '', 'title': '', 'content': 'SECURITY BULLETIN SUMMARY There are m...
14  [{'text': '', 'title': '', 'content': 'TECHNOTE (TROUBLESHOOTING) PROBLEM(AB...
15  [{'text': '', 'title': '', 'content': 'DOWNLOADABLE FILES ABSTRACT This docu...
16  [{'text': '', 'title': '', 'content': 'IIB WMB FLASH (ALERT) ABSTRACT IBM In...
17  [{'text': '', 'title': '', 'content': 'SECURITY BULLETIN SUMMARY IBM WebSphe...
18  [{'text': '', 'title': '', 'content': 'are applicable to IBM Cognos Disclosu...
19  [{'text': '', 'title': '', 'content': 'I have 1000 servers to apply FP, what...

                                                                             answer  \
0   The provided passages do not contain information regarding a specific format...
1       The passages do not provide sufficient information to answer this question.
2   Microsoft Edge is supported starting with IBM Content Collector 4.0.1 Fix Pa...
3       The passages do not provide sufficient information to answer this question.
4       The passages do not provide sufficient information to answer this question.
5       The passages do not provide sufficient information to answer this question.
6   Based on the provided documents, there are different ways to resolve `com.ib...
7   The provided passages do not contain sufficient information to answer this q...
8       The passages do not provide sufficient information to answer this question.
9   HSM-enabled DataPower appliances support the export of private keys using th...
10  There are three use cases for configuring Sharing Conversations in the DataP...
11      The passages do not provide sufficient information to answer this question.
12      The passages do not provide sufficient information to answer this question.
13      The passages do not provide sufficient information to answer this question.
14      The passages do not provide sufficient information to answer this question.
15  To download and install IBM Tivoli Network Manager IP Edition Version 4.2 Fi...
16  IBM Integration Bus Hypervisor Edition V9.0 and WebSphere Message Broker Hyp...
17      The passages do not provide sufficient information to answer this question.
18      The passages do not provide sufficient information to answer this question.
19      The passages do not provide sufficient information to answer this question.

    relevance_score__pred  relevance_score__gt  relevance_score__deviation  \
0                  0.6857               0.0117                      0.6740
1                  0.0000               0.0270                     -0.0270
2                  0.1600               0.0027                      0.1573
3                  0.0000               0.0000                      0.0000
4                  0.2727               0.0833                      0.1894
5                  0.1111               0.0000                      0.1111
6                  0.9778               0.0000                      0.9778
7                  0.2778               0.0146                      0.2632
8                  0.3896               0.0543                      0.3353
9                  0.5500               0.0627                      0.4873
10                 1.0000               0.0187                      0.9813
11                 0.0000               0.0701                     -0.0701
12                 0.0000               0.0280                     -0.0280
13                 0.0000               0.0850                     -0.0850
14                 0.0000               0.0738                     -0.0738
15                 0.1633               0.0610                      0.1023
16                 0.5000               0.1875                      0.3125
17                 0.0465               0.0000                      0.0465
18                 0.0000               0.0000                      0.0000
19                 0.0000               0.0367                     -0.0367

    utilization_score__pred  utilization_score__gt  \
0                    0.5714                 0.0117
1                    0.0000                 0.0270
2                    0.0800                 0.0013
3                    0.0000                 0.0000
4                    0.0000                 0.0463
5                    0.0000                 0.0000
6                    0.3333                 0.0000
7                    0.2222                 0.0146
8                    0.0000                 0.0543
9                    0.4000                 0.0627
10                   0.6744                 0.0187
11                   0.0000                 0.0590
12                   0.0000                 0.0000
13                   0.0000                 0.0650
14                   0.0000                 0.0336
15                   0.1633                 0.0235
16                   0.5000                 0.0469
17                   0.0000                 0.0000
18                   0.0000                 0.0000
19                   0.0000                 0.0000

    utilization_score__deviation  completeness_score__pred  \
0                         0.5597                    0.8333
1                        -0.0270                    0.0000
2                         0.0787                    0.5000
3                         0.0000                    0.0000
4                        -0.0463                    0.0000
5                         0.0000                    0.0000
6                         0.3333                    0.3409
7                         0.2076                    0.8000
8                        -0.0543                    0.0000
9                         0.3373                    0.7273
10                        0.6557                    0.6744
11                       -0.0590                    0.0000
12                        0.0000                    0.0000
13                       -0.0650                    0.0000
14                       -0.0336                    0.0000
15                        0.1398                    1.0000
16                        0.4531                    1.0000
17                        0.0000                    0.0000
18                        0.0000                    0.0000
19                        0.0000                    0.0000

    completeness_score__gt  completeness_score__deviation  \
0                   1.0000                        -0.1667
1                   1.0000                        -1.0000
2                   0.5000                         0.0000
3                   1.0000                        -1.0000
4                   0.5556                        -0.5556
5                   1.0000                        -1.0000
6                   1.0000                        -0.6591
7                   1.0000                        -0.2000
8                   1.0000                        -1.0000
9                   1.0000                        -0.2727
10                  1.0000                        -0.3256
11                  0.8421                        -0.8421
12                  0.0000                         0.0000
13                  0.7647                        -0.7647
14                  0.4545                        -0.4545
15                  0.3846                         0.6154
16                  0.2500                         0.7500
17                  1.0000                        -1.0000
18                  1.0000                        -1.0000
19                  0.0000                         0.0000

    adherence_score__pred  adherence_score__gt  adherence_score__deviation
0                     1.0                  0.0                         1.0
1                     1.0                  1.0                         0.0
2                     1.0                  1.0                         0.0
3                     1.0                  1.0                         0.0
4                     1.0                  1.0                         0.0
5                     1.0                  0.0                         1.0
6                     1.0                  0.0                         1.0
7                     1.0                  0.0                         1.0
8                     1.0                  1.0                         0.0
9                     1.0                  1.0                         0.0
10                    1.0                  1.0                         0.0
11                    1.0                  1.0                         0.0
12                    1.0                  0.0                         1.0
13                    1.0                  1.0                         0.0
14                    1.0                  1.0                         0.0
15                    1.0                  0.0                         1.0
16                    1.0                  0.0                         1.0
17                    1.0                  1.0                         0.0
18                    1.0                  0.0                         1.0
19                    1.0                  0.0                         1.0  , summary=               metric  mean_score  mean_ground_truth  std_score  \
0     relevance_score      0.2567             0.0409     0.3186
1   utilization_score      0.1472             0.0232     0.2181
2  completeness_score      0.2938             0.7376     0.3846
3     adherence_score      1.0000             0.5500     0.0000

   std_ground_truth  mean_abs_error
0            0.0450          0.2479
1            0.0237          0.1525
2            0.3456          0.5803
3            0.4975          0.4500  , config_summary={'name': 'techqa_production_colab_gemma', 'mode': 'test', 'providers': {'modal': {'type': 'openai', 'api_key_env': 'MODAL_PROXY_KEY', 'params': {'base_url': 'https://thetripsbay--ep-gemma-4-26b-a4b-it-server.us-west.modal.direct/v1', 'cooldown_seconds': 60}}}, 'chunking': {'type': 'fixed_word', 'config': {'max_words': 200, 'overlap_words': 20}}, 'embedding': {'type': 'sentence_transformer', 'config': {'model_name': 'sentence-transformers/all-MiniLM-L6-v2', 'dimension': 384}}, 'vector_store': {'type': 'faiss', 'config': {'dimension': 384}}, 'retrieval': {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 5}}]}, 'query_transform': None, 'fusion': None, 'rerank': None}, 'generation': {'strategy': 'default', 'provider': 'modal', 'config': {'model': 'gemma-4-26b-a4b-it', 'temperature': 0.0, 'max_tokens': 750, 'system_prompt': 'You are an IBM technical-support question answering assistant.\nYour task is to answer questions using ONLY information from the retrieved\ntechnote passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use external knowledge.\n2. Include all relevant steps, error codes, product versions, APAR numbers,\n   and configuration details found in the passages.\n3. Preserve exact technical identifiers (version strings, file names,\n   parameter names, error messages) verbatim.\n4. Do NOT add phrases like "based on general knowledge" or hedge unnecessarily.\n5. If the passages do not contain enough information, respond with exactly:\n   "The passages do not provide sufficient information to answer this question."\n6. Every claim must be directly supported by the passages provided.', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, include all relevant steps and technical details):'}}, 'evaluation': {'type': 'trace', 'provider': 'modal', 'config': {'model': 'gemma-4-26b-a4b-it', 'temperature': 0.0, 'max_tokens': 2000}}, 'cache': {'enabled': True, 'cache_dir': './cache_production_colab_gemma_techqa'}, 'start_index': None, 'end_index': None, 'logging_config': {'enabled': True, 'level': 'INFO', 'show_progress': True}})])]

,config_name,relevance_score__mean,relevance_score__mae,utilization_score__mean,utilization_score__mae,completeness_score__mean,completeness_score__mae,adherence_score__mean,adherence_score__mae
0,techqa_production_colab_gemma,0.2567,0.2479,0.1472,0.1525,0.2938,0.5803,1.0,0.45

================================================================================
EMANUAL
================================================================================
Raw reports for emanual: [Report(title='RAG Multi-Config Evaluation Report', strategy_name='detailed_query', sections=[ReportSection(config_name='emanual_production_colab_gemma', per_query=                                                                              query  \
0                            I want to  enter into Ambient mode. How can I do that?
1                                              Where do I find signal information ?
2   How can I view the channels that are serached by auto program function and H...
3                                                             Can I configure Tint?
4                                      How do I fix the missing/wrong color issue ?
5                                        How do I fix blurring issues on TV screen?
6                                               What is the use of universal guide?
7                                               What is the feature of Bixby guide?
8                                    How to launch the last used app automatically?
9                                 Where do I find the list of my favorite channels?
10                         I want to setup a  beautiful screens. How can I do that?
11                                   How do I record using time Timeshift function?
12                                  My IP auto setting failed. How to configure it?
13                                    How can I connect my mobile device to the TV?
14                                         How to configure Contrast and Sharpness?
15                                             What are the steps to reset network?
16                     How do I view a list of mobile devices registered to the TV?
17               I get this error 'some files cannot be played'. How do I fix this?
18                                             How do I set scheduled viewing time?
19                                               Can I scan TV for malicious code ?

                                                                retrieved_documents  \
0   [{'text': '', 'title': '', 'content': 'beautiful screens, various visual inf...
1   [{'text': '', 'title': '', 'content': 'Viewing Broadcast Information at a Gl...
2   [{'text': '', 'title': '', 'content': 'Viewing and selecting channels on Fav...
3   [{'text': '', 'title': '', 'content': 'Setting the screen to black and white...
4   [{'text': '', 'title': '', 'content': 'Inverting the screen color. Settings ...
5   [{'text': '', 'title': '', 'content': 'Setting the screen to black and white...
6   [{'text': '', 'title': '', 'content': 'Accessibility Guidance. Provides a me...
7   [{'text': '', 'title': '', 'content': 'button, say a command, and then relea...
8   [{'text': '', 'title': '', 'content': 'Launching the last used app automatic...
9   [{'text': '', 'title': '', 'content': 'Viewing and selecting channels on Fav...
10  [{'text': '', 'title': '', 'content': 'the Ambient Mode browser will be prov...
11  [{'text': '', 'title': '', 'content': 'to Using the Recording and Timeshift'...
12  [{'text': '', 'title': '', 'content': 'turned on. If it is, turn it off and ...
13  [{'text': '', 'title': '', 'content': 'Connecting Your Mobile Device. Connec...
14  [{'text': '', 'title': '', 'content': 'Configuring advanced picture settings...
15  [{'text': '', 'title': '', 'content': 'Resetting Your Network. Settings Gene...
16  [{'text': '', 'title': '', 'content': 'Managing Mobile Devices. Settings Gen...
17  [{'text': '', 'title': '', 'content': 'My File Won't Play. When files don't ...
18  [{'text': '', 'title': '', 'content': 'Setting Up a Schedule Viewing. Config...
19  [{'text': '', 'title': '', 'content': 'Scanning the TV and connected storage...

                                                                             answer  \
0                                          To enter Ambient Mode, press the button.
1                          Settings > Support > Self Diagnosis > Signal Information
2   To view the channels that have been automatically searched and the first fiv...
3       The passages do not provide sufficient information to answer this question.
4       The passages do not provide sufficient information to answer this question.
5   To sharpen blurred edges caused by colors, follow these steps:\n\nSettings >...
6       The passages do not provide sufficient information to answer this question.
7   To view the Bixby guide:\n\n1. Press the button once.\n2. When the Using Bix...
8   To launch the last used app automatically, follow this menu path:\n\nSetting...
9   Live TV Channel List > Press the right directional button on your remote con...
10  In the Ambient Mode browser screen, move the focus to , and then press the S...
11  When a program is being recorded, you can press the down directional button ...
12  Configure the settings in IP Settings Settings General Network Network Statu...
13  1. Turn on the TV.\n2. Start the SmartThings app on your mobile device.\n3. ...
14               Settings > Picture > Expert Settings:\n\n1. Contrast\n2. Sharpness
15                           Settings > General > Network > Reset Network > Try Now
16  Settings > General > External Device Manager > Device Connect Manager > Devi...
17      The passages do not provide sufficient information to answer this question.
18  To set up a scheduled viewing, follow these steps:\n\n1. First, set the TV's...
19  To scan the TV and connected storage for malicious code, follow these steps:...

    relevance_score__pred  relevance_score__gt  relevance_score__deviation  \
0                  0.3889               0.0204                      0.3685
1                  0.2000               0.1111                      0.0889
2                  0.5185               0.4211                      0.0974
3                  0.0000               0.0323                     -0.0323
4                  0.2500               0.0893                      0.1607
5                  0.2500               0.0357                      0.2143
6                  1.0000               0.2778                      0.7222
7                  0.1071               0.1333                     -0.0262
8                  0.3333               0.0682                      0.2651
9                  0.3704               0.4167                     -0.0463
10                 0.2222               0.0328                      0.1894
11                 0.4000               0.2000                      0.2000
12                 0.1111               0.1154                     -0.0043
13                 0.5238               0.3929                      0.1309
14                 0.2500               0.0769                      0.1731
15                 0.2353               0.0370                      0.1983
16                 0.1333               0.1111                      0.0222
17                 0.2500               0.2105                      0.0395
18                 0.2500               0.3500                     -0.1000
19                 0.2222               0.7692                     -0.5470

    utilization_score__pred  utilization_score__gt  \
0                    0.1111                 0.0408
1                    0.1000                 0.1111
2                    0.4444                 0.1579
3                    0.0000                 0.0323
4                    0.0000                 0.1786
5                    0.2500                 0.0357
6                    0.0000                 0.1667
7                    0.1071                 0.1333
8                    0.1667                 0.0455
9                    0.2963                 0.3333
10                   0.2222                 0.0492
11                   0.2000                 0.1000
12                   0.1111                 0.1538
13                   0.1429                 0.3571
14                   0.2500                 0.0769
15                   0.2353                 0.0370
16                   0.1333                 0.0741
17                   0.0000                 0.1579
18                   0.2500                 0.1500
19                   0.1481                 0.5385

    utilization_score__deviation  completeness_score__pred  \
0                         0.0703                    0.2857
1                        -0.0111                    0.5000
2                         0.2865                    0.8571
3                        -0.0323                    0.0000
4                        -0.1786                    0.0000
5                         0.2143                    1.0000
6                        -0.1667                    0.0000
7                        -0.0262                    1.0000
8                         0.1212                    0.5000
9                        -0.0370                    0.8000
10                        0.1730                    1.0000
11                        0.1000                    0.5000
12                       -0.0427                    1.0000
13                       -0.2142                    0.2727
14                        0.1731                    1.0000
15                        0.1983                    1.0000
16                        0.0592                    1.0000
17                       -0.1579                    0.0000
18                        0.1000                    1.0000
19                       -0.3904                    0.6667

    completeness_score__gt  completeness_score__deviation  \
0                   1.0000                        -0.7143
1                   1.0000                        -0.5000
2                   0.3750                         0.4821
3                   1.0000                        -1.0000
4                   0.4000                        -0.4000
5                   1.0000                         0.0000
6                   0.6000                        -0.6000
7                   1.0000                         0.0000
8                   0.6667                        -0.1667
9                   0.8000                         0.0000
10                  1.0000                         0.0000
11                  0.5000                         0.0000
12                  0.6667                         0.3333
13                  0.9091                        -0.6364
14                  1.0000                         0.0000
15                  1.0000                         0.0000
16                  0.6667                         0.3333
17                  0.2500                        -0.2500
18                  0.4286                         0.5714
19                  0.7000                        -0.0333

    adherence_score__pred  adherence_score__gt  adherence_score__deviation
0                     1.0                  1.0                         0.0
1                     1.0                  1.0                         0.0
2                     0.0                  1.0                        -1.0
3                     1.0                  1.0                         0.0
4                     1.0                  1.0                         0.0
5                     1.0                  1.0                         0.0
6                     1.0                  1.0                         0.0
7                     1.0                  1.0                         0.0
8                     1.0                  1.0                         0.0
9                     1.0                  1.0                         0.0
10                    1.0                  1.0                         0.0
11                    1.0                  1.0                         0.0
12                    1.0                  1.0                         0.0
13                    1.0                  1.0                         0.0
14                    0.0                  1.0                        -1.0
15                    1.0                  0.0                         1.0
16                    1.0                  1.0                         0.0
17                    1.0                  0.0                         1.0
18                    1.0                  1.0                         0.0
19                    1.0                  1.0                         0.0  , summary=               metric  mean_score  mean_ground_truth  std_score  \
0     relevance_score      0.3008             0.1951     0.2051
1   utilization_score      0.1584             0.1465     0.1117
2  completeness_score      0.6191             0.7481     0.3911
3     adherence_score      0.9000             0.9000     0.3000

   std_ground_truth  mean_abs_error
0            0.1870          0.1813
1            0.1258          0.1377
2            0.2503          0.3010
3            0.3000          0.2000  , config_summary={'name': 'emanual_production_colab_gemma', 'mode': 'test', 'providers': {'modal': {'type': 'openai', 'api_key_env': 'MODAL_PROXY_KEY', 'params': {'base_url': 'https://thetripsbay--ep-gemma-4-26b-a4b-it-server.us-west.modal.direct/v1', 'cooldown_seconds': 60}}}, 'chunking': {'type': 'fixed_word', 'config': {'max_words': 128, 'overlap_words': 20}}, 'embedding': {'type': 'sentence_transformer', 'config': {'model_name': 'sentence-transformers/all-MiniLM-L6-v2', 'dimension': 384}}, 'vector_store': {'type': 'faiss', 'config': {'dimension': 384}}, 'retrieval': {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 5}}]}, 'query_transform': None, 'fusion': None, 'rerank': None}, 'generation': {'strategy': 'default', 'provider': 'modal', 'config': {'model': 'gemma-4-26b-a4b-it', 'temperature': 0.0, 'max_tokens': 512, 'system_prompt': 'You are a consumer-electronics product-support assistant. Answer questions\nabout device features and settings using ONLY the provided user-manual passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use outside knowledge.\n2. Give exact, step-by-step instructions. Preserve menu paths, button names,\n   setting names, and on-screen labels verbatim\n   (e.g. "Settings > Support > Self Diagnosis > Signal Information").\n3. Be concise and procedural - give the steps, not background.\n4. If the passages do not contain the answer, respond with exactly:\n   "The passages do not provide sufficient information to answer this question."\n5. Every step must be directly supported by the passages provided.', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, give exact steps and menu paths):'}}, 'evaluation': {'type': 'trace', 'provider': 'modal', 'config': {'model': 'gemma-4-26b-a4b-it', 'temperature': 0.0, 'max_tokens': 2000}}, 'cache': {'enabled': True, 'cache_dir': './cache_production_colab_gemma_emanual'}, 'start_index': None, 'end_index': None, 'logging_config': {'enabled': True, 'level': 'INFO', 'show_progress': True}})])]

,config_name,relevance_score__mean,relevance_score__mae,utilization_score__mean,utilization_score__mae,completeness_score__mean,completeness_score__mae,adherence_score__mean,adherence_score__mae
0,emanual_production_colab_gemma,0.3008,0.1813,0.1584,0.1377,0.6191,0.301,0.9,0.2

================================================================================
DELUCIONQA
================================================================================
Raw reports for delucionqa: [Report(title='RAG Multi-Config Evaluation Report', strategy_name='detailed_query', sections=[ReportSection(config_name='delucionqa_production_colab_gemma', per_query=                                                                       query  \
0                             What if I fail to latch the tailgate properly?
1                  What kind of safety features are implemented in this car?
2                                  When will the Automatic SOS be triggered?
3                   What happens if I accidentally push the SOS Call button?
4                                                           What is the DEF?
5                  What may cause erratic or noisy performance of the radio?
6                                 how to calculate the gross trailer weight?
7                                              What can the ASIST button do?
8                                      What does the Door Off Mirror Kit do?
9                 Can I manually activate or deactivate the air conditioner?
10                              what does the The cartridge block heater do?
11                      When will the illuminated entry system be activated?
12  If the light remains on after the bulb check, it indicates what problem?
13                                      What is special about power windows?
14                                   What should I do to jump start the car?
15                                     How to deactivate the cruise control?
16              Is it safe for me to park the vehicle in somewhere very hot?
17                                            Any tips for driving downhill?
18                                      what can the dimmer controls adjust?
19                           how to use the key fob to unlock all the doors?

                                                                retrieved_documents  \
0   [{'text': '', 'title': '', 'content': 'If the Tonneau Cover is installed, ma...
1   [{'text': '', 'title': '', 'content': 'OCCUPANT RESTRAINT SYSTEMS Some of th...
2   [{'text': '', 'title': '', 'content': 'Automatic SOS — If Equipped Automatic...
3   [{'text': '', 'title': '', 'content': 'Connected Services SOS FAQs — If Equi...
4   [{'text': '', 'title': '', 'content': 'DEF tank DEF pump DEF injector Electr...
5   [{'text': '', 'title': '', 'content': 'Under certain conditions, the mobile ...
6   [{'text': '', 'title': '', 'content': 'Gross Trailer Weight (GTW) The GTW is...
7   [{'text': '', 'title': '', 'content': 'If equipped, the ASSIST Button is use...
8   [{'text': '', 'title': '', 'content': 'Door Off Mirror Kit — If Equipped If ...
9   [{'text': '', 'title': '', 'content': 'The Air Conditioning (A/C) button all...
10  [{'text': '', 'title': '', 'content': 'The cartridge block heater clips into...
11  [{'text': '', 'title': '', 'content': 'and will remain fully illuminated unt...
12  [{'text': '', 'title': '', 'content': 'Your vehicle is equipped with a sophi...
13  [{'text': '', 'title': '', 'content': 'The power windows feature allows for ...
14  [{'text': '', 'title': '', 'content': 'of the engine compartment. If your ve...
15  [{'text': '', 'title': '', 'content': 'Cruise Control can be dangerous where...
16  [{'text': '', 'title': '', 'content': 'Transporting Passengers NEVER TRANSPO...
17  [{'text': '', 'title': '', 'content': 'Driving Up Hill Once you have determi...
18  [{'text': '', 'title': '', 'content': 'Dimmer Control The dimmer control is ...
19  [{'text': '', 'title': '', 'content': 'To Lock/Unlock The Doors And Tailgate...

                                                                             answer  \
0   Failure to securely latch the tailgate could result in damage to the vehicle...
1   Some of the most important safety features in your vehicle are the restraint...
2   Automatic SOS is a hands-free safety service that can immediately connect yo...
3   If you accidentally push the SOS Call button on the mirror or overhead conso...
4       The passages do not provide sufficient information to answer this question.
5   Under certain conditions, the mobile phone being on in your vehicle can caus...
6   The recommended way to measure GTW is to put your fully loaded trailer on a ...
7   If equipped, the ASSIST Button is used for contacting Roadside Assistance, V...
8   If equipped with the Door Off Mirror Kit, exterior rearview mirrors can be i...
9   The Air Conditioning (A/C) button allows the operator to manually activate o...
10  The cartridge block heater clips into the engine block near the water jacket...
11      The passages do not provide sufficient information to answer this question.
12      The passages do not provide sufficient information to answer this question.
13  The power windows feature allows for movement of the windows with the push o...
14  To prepare for jump starting, follow these steps:\n\n1. Apply the parking br...
15  To deactivate the cruise control, use the following methods depending on the...
16  WARNING: Do not leave children or animals inside parked vehicles in hot weat...
17  Before driving down a steep hill, you need to determine the following:\n* Wh...
18  With the parking lights or headlights on, the dimmer control can adjust:\n* ...
19  Push and release the unlock button on the key fob twice to unlock all the do...

    relevance_score__pred  relevance_score__gt  relevance_score__deviation  \
0                  0.1200               0.1111                      0.0089
1                  0.1724               0.2500                     -0.0776
2                  0.0769               0.0244                      0.0525
3                  0.4286               0.0820                      0.3466
4                  0.8000               0.0625                      0.7375
5                  0.0690               0.1143                     -0.0453
6                  0.5000               0.2727                      0.2273
7                  0.3636               0.4348                     -0.0712
8                  0.1250               0.1304                     -0.0054
9                  0.3409               0.0811                      0.2598
10                 0.0962               0.0492                      0.0470
11                 0.0000               0.0541                     -0.0541
12                 0.1316               0.1042                      0.0274
13                 0.6842               0.2759                      0.4083
14                    NaN               0.4127                         NaN
15                 0.3636               0.4667                     -0.1031
16                 0.0800               0.1622                     -0.0822
17                 0.1333               0.5000                     -0.3667
18                 0.5357               0.5000                      0.0357
19                 0.0690               0.0312                      0.0378

    utilization_score__pred  utilization_score__gt  \
0                    0.1200                 0.1111
1                    0.1724                 0.2500
2                    0.0769                 0.0244
3                    0.4286                 0.0656
4                    0.0000                 0.0625
5                    0.0690                 0.1143
6                    0.3750                 0.2727
7                    0.3636                 0.4348
8                    0.1250                 0.1304
9                    0.1364                 0.1351
10                   0.0962                 0.0492
11                   0.0000                 0.0811
12                   0.0000                 0.0208
13                   0.6842                 0.1379
14                      NaN                 0.2063
15                   0.5455                 0.4667
16                   0.0800                 0.1892
17                   0.1333                 0.5000
18                   0.5357                 0.5000
19                   0.0690                 0.0312

    utilization_score__deviation  completeness_score__pred  \
0                         0.0089                    1.0000
1                        -0.0776                    1.0000
2                         0.0525                    1.0000
3                         0.3630                    1.0000
4                        -0.0625                    0.0000
5                        -0.0453                    1.0000
6                         0.1023                    0.7500
7                        -0.0712                    1.0000
8                        -0.0054                    1.0000
9                         0.0013                    0.4000
10                        0.0470                    1.0000
11                       -0.0811                    0.0000
12                       -0.0208                    0.0000
13                        0.5463                    0.9231
14                           NaN                       NaN
15                        0.0788                    0.8333
16                       -0.1092                    1.0000
17                       -0.3667                    1.0000
18                        0.0357                    1.0000
19                        0.0378                    1.0000

    completeness_score__gt  completeness_score__deviation  \
0                   1.0000                         0.0000
1                   1.0000                         0.0000
2                   1.0000                         0.0000
3                   0.8000                         0.2000
4                   1.0000                        -1.0000
5                   1.0000                         0.0000
6                   1.0000                        -0.2500
7                   1.0000                         0.0000
8                   1.0000                         0.0000
9                   0.6667                        -0.2667
10                  1.0000                         0.0000
11                  1.0000                        -1.0000
12                  0.2000                        -0.2000
13                  0.5000                         0.4231
14                  0.5000                            NaN
15                  0.8571                        -0.0238
16                  1.0000                         0.0000
17                  1.0000                         0.0000
18                  1.0000                         0.0000
19                  1.0000                         0.0000

    adherence_score__pred  adherence_score__gt  adherence_score__deviation
0                     1.0                  1.0                         0.0
1                     1.0                  1.0                         0.0
2                     1.0                  1.0                         0.0
3                     1.0                  1.0                         0.0
4                     1.0                  1.0                         0.0
5                     1.0                  1.0                         0.0
6                     1.0                  1.0                         0.0
7                     1.0                  1.0                         0.0
8                     1.0                  1.0                         0.0
9                     1.0                  1.0                         0.0
10                    1.0                  1.0                         0.0
11                    1.0                  1.0                         0.0
12                    0.0                  1.0                        -1.0
13                    1.0                  1.0                         0.0
14                    NaN                  1.0                         NaN
15                    1.0                  1.0                         0.0
16                    1.0                  1.0                         0.0
17                    1.0                  1.0                         0.0
18                    1.0                  1.0                         0.0
19                    1.0                  1.0                         0.0  , summary=               metric  mean_score  mean_ground_truth  std_score  \
0     relevance_score      0.2679             0.2060     0.2262
1   utilization_score      0.2111             0.1892     0.2039
2  completeness_score      0.7845             0.8762     0.3681
3     adherence_score      0.9474             1.0000     0.2233

   std_ground_truth  mean_abs_error
0            0.1651          0.1576
1            0.1589          0.1112
2            0.2242          0.1770
3            0.0000          0.0526  , config_summary={'name': 'delucionqa_production_colab_gemma', 'mode': 'test', 'providers': {'modal': {'type': 'openai', 'api_key_env': 'MODAL_PROXY_KEY', 'params': {'base_url': 'https://thetripsbay--ep-gemma-4-26b-a4b-it-server.us-west.modal.direct/v1', 'cooldown_seconds': 60}}}, 'chunking': {'type': 'fixed_word', 'config': {'max_words': 160, 'overlap_words': 24}}, 'embedding': {'type': 'sentence_transformer', 'config': {'model_name': 'sentence-transformers/all-MiniLM-L6-v2', 'dimension': 384}}, 'vector_store': {'type': 'faiss', 'config': {'dimension': 384}}, 'retrieval': {'search': {'searches': [{'type': 'dense', 'config': {'top_k': 5}}]}, 'query_transform': None, 'fusion': None, 'rerank': None}, 'generation': {'strategy': 'default', 'provider': 'modal', 'config': {'model': 'gemma-4-26b-a4b-it', 'temperature': 0.0, 'max_tokens': 512, 'system_prompt': 'You are an automotive owner\'s-manual support assistant. Answer questions\nabout vehicle features, controls, and procedures using ONLY the provided\nowner\'s-manual passages.\n\nCRITICAL RULES:\n1. Answer ONLY from the passages provided. Do not use outside knowledge.\n2. Give exact, step-by-step procedures. Preserve exact control names, button\n   names, warning/CAUTION text, and feature labels verbatim.\n3. Include any safety warnings (WARNING/CAUTION) that the passages attach to\n   the procedure.\n4. Be concise and procedural - give the steps, not background.\n5. If the passages do not contain the answer, respond with exactly:\n   "The passages do not provide sufficient information to answer this question."\n6. Every claim must be directly supported by the passages provided.', 'user_prompt': 'Passages:\n{context}\n\nQuestion: {query}\n\nAnswer (from passages only, give exact steps, control names, and any safety warnings):'}}, 'evaluation': {'type': 'trace', 'provider': 'modal', 'config': {'model': 'gemma-4-26b-a4b-it', 'temperature': 0.0, 'max_tokens': 2000}}, 'cache': {'enabled': True, 'cache_dir': './cache_production_colab_gemma_delucionqa'}, 'start_index': None, 'end_index': None, 'logging_config': {'enabled': True, 'level': 'INFO', 'show_progress': True}})])]

,config_name,relevance_score__mean,relevance_score__mae,utilization_score__mean,utilization_score__mae,completeness_score__mean,completeness_score__mae,adherence_score__mean,adherence_score__mae
0,delucionqa_production_colab_gemma,0.2679,0.1576,0.2111,0.1112,0.7845,0.177,0.9474,0.0526

## 7. Results

In [ ]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 80)

for dataset in DATASETS:
    print(f'\n{"="*80}\n{dataset.upper()}\n{"="*80}')
    comparison = runners[dataset].compare()
    display(comparison.to_dataframe())

================================================================================
TECHQA
================================================================================

,config_name,relevance_score__mean,relevance_score__mae,utilization_score__mean,utilization_score__mae,completeness_score__mean,completeness_score__mae,adherence_score__mean,adherence_score__mae
0,techqa_production_colab_gemma,0.2567,0.2479,0.1472,0.1525,0.2938,0.5803,1.0,0.45

================================================================================
EMANUAL
================================================================================

,config_name,relevance_score__mean,relevance_score__mae,utilization_score__mean,utilization_score__mae,completeness_score__mean,completeness_score__mae,adherence_score__mean,adherence_score__mae
0,emanual_production_colab_gemma,0.3008,0.1813,0.1584,0.1377,0.6191,0.301,0.9,0.2

================================================================================
DELUCIONQA
================================================================================

,config_name,relevance_score__mean,relevance_score__mae,utilization_score__mean,utilization_score__mae,completeness_score__mean,completeness_score__mae,adherence_score__mean,adherence_score__mae
0,delucionqa_production_colab_gemma,0.2679,0.1576,0.2111,0.1112,0.7845,0.177,0.9474,0.0526

## 8. Conclusion

This validates `gemma-4-26b-a4b-it` (via Modal) as generator + judge on the
customer-support domain's already-chosen retrieval architecture (dense-only,
`all-MiniLM-L6-v2`, `top_k=5`, per-dataset fixed-word chunking) — the retrieval
side is unchanged from `production/configs/*.yaml`; only the model/provider
changed, to compare directly against the `meta-llama/llama-3.3-70b-instruct`
(OpenRouter) baseline in the original `production_pipeline_demo.ipynb`.

**Known open limitation, carried over from the original sweep, not specific to
this model**: techqa's real (non-refusal) adherence stayed near-zero regardless
of retrieval strategy in the original sweep — worth checking whether that
persists with this generator too, since it looked like a generation-prompt/
domain issue rather than a retrieval problem.

To swap models/providers again later, edit `MODEL_NAME`/`MODAL_BASE_URL` and the
`providers` block in section 5 — no other file in this notebook or the repo
needs to change.